Fix date field being parsed with a timezone
strapi/strapi pull request #10033
Opened 2021-04-13 21:33 UTC by derrickmehaffy

Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

### What does it do?

Stops using the built in Javascript date which reads the systems timezone by replacing `new Date()` with the date-fns function `parseISO` [see it's docs here](https://date-fns.org/v2.20.3/docs/parseISO)

### Why is it needed?

if the string value passed from upstream in Strapi is `2021-04-14`:

date-fns function
```js
const cast = parseISO(value);
// returns: 2021-04-14T07:00:00.000Z
```

javascript native function
```js
const cast = new Date(value);
const castString = cast.toString();
// returns: Tue Apr 13 2021 17:00:00 GMT-0700 (Mountain Standard Time)
```

The problem is that the built in Javascript `Date()` will use the local systems timezone, and instead the date-fns has the ability to just parse the raw date string and not pass in the system timezone.

### How to test it?

Your system must be set to a timezone that is +/- GMT by at least 1 hour

1. Create a project
2. Create a model with a date field
3. Add a new date via any means
4. See date doesn't move backwards or forwards

### Related issue(s)/PR(s)

fixes #9576

2021-04-14 12:19 UTC, alexandrebodin reviewed
why isn't it necesssary on the other types like datetime ? 

Seems like the test are breaking now

2021-04-14 15:13 UTC, derrickmehaffy commented
> why isn't it necesssary on the other types like datetime ?
> 
> Seems like the test are breaking now

Honestly I have no idea, it's extremely difficult for me to track down how or why the local system timezone is being pulled in. The backend should -only- function in UTC. The Admin panel should be doing the time conversion but the date field specifically is the only field that shouldn't even be working with time but the default JS `Date()` generates a date with a time (and timezone).

2021-04-15 08:06 UTC, petersg83 commented
In your example, why does it return `2021-04-14T07:00:00.000Z` (with hours to 7)?
Here is what I have on my computer :
![Capture d’écran 2021-04-15 à 09 55 52](https://user-images.githubusercontent.com/11708220/114834455-da877180-9dd0-11eb-9f30-27239c3a00e0.png)

I'm thinking that the best would be that the front sends a `YYYY-MM-DD` string. At the moment the front sends a datetime with a timezone (see bellow). And no matter how we parse it, we won't be able to know what date was displayed to the user when they save.
![Capture d’écran 2021-04-15 à 10 02 57](https://user-images.githubusercontent.com/11708220/114835360-c55f1280-9dd1-11eb-927b-94de1fe64761.png)

2021-04-19 18:27 UTC, derrickmehaffy commented
> In your example, why does it return `2021-04-14T07:00:00.000Z` (with hours to 7)?
> Here is what I have on my computer :
> ![Capture d’écran 2021-04-15 à 09 55 52](https://user-images.githubusercontent.com/11708220/114834455-da877180-9dd0-11eb-9f30-27239c3a00e0.png)
> 
> I'm thinking that the best would be that the front sends a `YYYY-MM-DD` string. At the moment the front sends a datetime with a timezone (see bellow). And no matter how we parse it, we won't be able to know what date was displayed to the user when they save.
> ![Capture d’écran 2021-04-15 à 10 02 57](https://user-images.githubusercontent.com/11708220/114835360-c55f1280-9dd1-11eb-927b-94de1fe64761.png)

That is the issue @petersg83 is we are using parsing functions which is converting it to a datetime (with TZ information).

Realistically we shouldn't be parsing the date other than maybe to change formats (US uses `mm/dd/year` / Europe uses `dd/mm/year` / programming typically uses `year/mm/dd`).

What we need is for the frontend to only send UTC/GMT and parse it on the server like that without reading the system timezone, but we also need to customize this in case some users for whatever reason change the database timezone (which can be done on SQL databases)

2021-04-22 16:36 UTC, alexandrebodin requested changes

2021-04-22 16:36 UTC, alexandrebodin commented on packages/strapi-connector-bookshelf/lib/formatter.js
>      return isValid(cast) ? formatISO(cast, { representation: 'date' }) : null;
We can extract only the date part from the UTC ISO so it stays consistent all the way. we could consider doing this

```suggestion
    return isValid(cast) ? cast.toISOString().split('T')[0] : null
```

2021-04-28 14:15 UTC, petersg83 commented
@soupette I only changed the input data, not the filter. I think it's good enough for the moment, I don't have time to dig if there is a problem with how we handle the dates with the filter

2021-05-11 07:26 UTC, merged