Add plugins and providers to send event
strapi/strapi pull request #10073
Opened 2021-04-19 15:07 UTC by markkaylor

### What does it do?

Adds plugins and providers to 'didStartServer' send event

2021-04-19 15:10 UTC, markkaylor commented on packages/strapi/lib/Strapi.js
> +        .value();
🤷‍♂️

2021-04-20 12:43 UTC, alexandrebodin requested changes
We should avoid read package.json files

2021-04-20 12:43 UTC, alexandrebodin commented on packages/strapi/lib/Strapi.js
> +        if (this.plugins[plugin].package.author.name === 'Strapi team') {
Checking hte package info is not going to be a safe info. 
When loading the plugins you should add a flag to say they are local or not but all strapi-plugin-xxx are external plugins even if not maintained by us. We should just ignore local plugins for now

2021-04-20 12:43 UTC, alexandrebodin commented on packages/strapi/lib/Strapi.js
> +      const providers = _(this.plugins)
You should check the strapi-provider-xxx pacakges in strapi package json not for each plugin as this won't find manually installed providers. 

* Avoid using lodash chaining api

2021-04-21 09:56 UTC, alexandrebodin approved these changes
LGTM

2021-04-21 09:56 UTC, merged