Remove window.strapi.notification
strapi/strapi pull request #10330
Opened 2021-05-17 14:02 UTC by soupette

### What does it do?

It removes the global `window.strapi.notification`

2021-05-17 14:22 UTC, soupette commented on packages/core/admin/admin/src/components/Notifications/index.js
> +const Notifications = ({ children }) => {
@HichamELBSI @mfrachet do you think we should move the component to the helper-plugin?

2021-05-17 21:48 UTC, HichamELBSI requested changes

2021-05-18 05:29 UTC, mfrachet commented on packages/core/admin/admin/src/hooks/useSettingsForm/index.js
> +  const toggleNotificationRef = useRef(toggleNotification);
I agree with Hicham. Not sure it's necessary to put everything in refs

2021-05-18 06:22 UTC, soupette commented on packages/core/admin/admin/src/hooks/useSettingsForm/index.js
> +  const toggleNotificationRef = useRef(toggleNotification);
You are right it is not needed since the useNotification already makes sure the ref does not change.

2021-05-18 06:38 UTC, soupette commented on packages/core/admin/admin/src/components/Notifications/index.js
> +const Notifications = ({ children }) => {
In fact, I don't think it's needed anymore, putting this component in the helper plugin will only make the package heavier whereas, now with the hook and provider system de Notifications are available in the entire app by using a simple hook. I think it's better for now to leave it this way.

2021-05-18 06:50 UTC, merged