Rename containers to pages
strapi/strapi pull request #10347
Opened 2021-05-19 12:22 UTC by HichamELBSI

### What does it do?

Rename the `containers` folder to `pages` in the content manager

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2021-05-19 12:33 UTC, mfrachet approved these changes

2021-05-19 12:35 UTC, soupette requested changes

2021-05-19 12:35 UTC, soupette commented on packages/core/content-manager/admin/src/components/DragLayer/index.js
> +import LayoutDndProvider from '../../pages/LayoutDndProvider';
Shouldn't this be moved in the components folder?

2021-05-19 12:35 UTC, soupette commented on packages/core/content-manager/admin/src/components/Wysiwyg/index.js
> +import WysiwygProvider from '../../pages/WysiwygProvider';
Same here

2021-05-24 09:19 UTC, soupette approved these changes
LGTM

2021-05-24 09:19 UTC, merged