change common beginning to common path
strapi/strapi pull request #10509
Opened 2021-06-18 09:13 UTC by tonny008

### What does it do?

Change common beginning to common path

### Why is it needed?
server.js
url: http://example.com/api
admin.url http://example.com/admin

use common beginning the admin path will be `dmin`

2021-06-18 09:13 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=10509) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=10509) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=10509) it.</sub>

2021-06-21 12:24 UTC, petersg83 commented
Hi :)
Thanks for you contribution. The code can be improved indeed.

I read your code, here is a proposition of something even shorter and generic:
```js
const getCommonBeginning = (...strings) => takeWhile(
  strings[0],
  (char, index) => strings.every(string => string[index] === char)
).join('');
```

Can you directly change the function `getCommonBeginning` in `/packages/core/utils/lib/string-formatting.js`?
Also can you add some tests for this function in `/packages/core/utils/lib/__tests__/string-formatting.test.js`

2021-06-21 12:35 UTC, petersg83 requested changes
Hi :)
Thanks for you contribution. The code can be improved indeed.

I read your code, here is a proposition of something even shorter and generic:
```js
const getCommonBeginning = (...strings) => takeWhile(
  strings[0],
  (char, index) => strings.every(string => string[index] === char)
).join('');
```

Can you directly change the function `getCommonBeginning` in `/packages/core/utils/lib/string-formatting.js`?
Also can you add some tests for this function in `/packages/core/utils/lib/__tests__/string-formatting.test.js`?

2021-06-25 12:14 UTC, tonny008 commented
I don’t think it’s common beginnings here.

Given:
http://example.com/api
http://example.com/admin

common beginnings is http://example.com/a,
Common path is http://example.com

use common beginning the admin path will be dmin

2021-06-28 08:26 UTC, petersg83 commented
You're right I didn't see that. Thank you.
Can you please move the function next to `commonBeginning` in `/packages/core/utils/lib/string-formatting.js`?
And if you have time to write a few tests in `/packages/core/utils/lib/__tests__/string-formatting.test.js`, it would be perfect.
Otherwise I can do it too

2021-06-28 12:16 UTC, petersg83 reviewed
Thank you, you did everything :D 
I proposed a couple more tests. What do you think?

2021-06-28 12:16 UTC, petersg83 commented on packages/strapi-utils/lib/__tests__/string-formatting.test.js
> +      [['http://ab.com/admin', 'http://ab.com/api'], 'http://ab.com'],
Can you add:
```js
[['http://ab.com/admin', 'http://ab.com/admin/'], 'http://ab.com/admin'],
[['http://ab.com/admin', 'http://ab.com/admin'], 'http://ab.com/admin'],
```

2021-06-28 12:16 UTC, petersg83 commented on packages/strapi-utils/lib/__tests__/string-formatting.test.js
> +      [['ab/cd', 'ab/c'], 'ab/c'],
Can you add:
```js
[['abc', 'abc'], 'abc'],
```

2021-06-30 06:23 UTC, petersg83 submitted a review, later dismissed
It looks good to me! Thank you for this contribution!

2021-07-01 07:59 UTC, alexandrebodin commented on packages/strapi-utils/lib/string-formatting.js
> +  const [segments, ...otherSegments] = paths.map(it=>_.split(it, '/'));
can you add some spacing to make the code more readable.

2021-08-04 08:03 UTC, alexandrebodin commented
Hi there 👋  Do you think you will be able to finish the changes requested at some point ?

2021-08-11 07:36 UTC, petersg83 approved these changes

2021-08-17 11:25 UTC, merged