add marketplace banner that links to strapi awesome
strapi/strapi pull request #10677
Opened 2021-08-02 15:15 UTC by markkaylor

### What does it do?

Adds a banner on the marketplace page that links to strapi awesome: https://github.com/strapi/awesome-strapi 

### Why is it needed?

Helps people find community plugins

### How to test it?

Run strapi admin locally and go to the marketplace page

2021-08-02 18:38 UTC, derrickmehaffy reviewed
LGTM, thanks for adding this!

2021-08-03 12:52 UTC, mfrachet submitted a review, later dismissed
LGTM 👍🏻

2021-08-03 15:28 UTC, HichamELBSI requested changes

2021-08-03 15:28 UTC, HichamELBSI commented on packages/strapi-admin/admin/src/containers/MarketplacePage/PluginBanner/index.js
> +      <img className="bannerImage" src={LogoStrapi} alt="A strapi rocket logo" />
as you did for the `<FormattedMessage id="app.components.PluginBanner" />`

2021-08-04 09:32 UTC, HichamELBSI approved these changes
LGTM good job @markkaylor !

2021-08-04 09:58 UTC, merged