Migration/app layout
strapi/strapi pull request #10689
Opened 2021-08-04 13:27 UTC by mfrachet

### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2021-08-04 13:30 UTC, mfrachet commented on packages/core/admin/admin/src/StrapiApp.js
> +      <ThemeProvider theme={lightTheme}>
ℹ️ This is the same modif as the one @HichamELBSI has done on his PR for the login pages

2021-08-04 13:30 UTC, mfrachet commented on packages/core/admin/admin/src/components/GlobalStyle/index.js
> +const GlobalStyle = createGlobalStyle``;
ℹ️ Letting it blank because for now, the icons in the main nav are using font awesome and this file imports fontawesome

2021-08-04 13:31 UTC, mfrachet commented on packages/core/helper-plugin/lib/src/hooks/usePersistentState/index.js
> +const usePersistentState = (key, defaultValue) => {
ℹ️ like useState, but stores and resolves the value from local storage

2021-08-06 07:40 UTC, mfrachet commented on packages/core/admin/admin/src/components/LeftMenu/index.js
> +      : get(userInfo, 'username', '');
Readability is key! Thanks for the suggestion :blush:

2021-08-06 07:42 UTC, mfrachet commented on packages/core/admin/admin/src/components/LeftMenu/index.js
> +        icon={<img src={menuLogo} alt="" />}
In this case, the NavBrand components hides the img from ATs using `aria-hidden` (https://github.com/strapi/parts/blob/develop/packages/strapi-parts/src/MainNav/NavBrand.js#L27). I'm not 100% sure it's necessary to announce "Strapi" every time someone scans the page. We can switch this behaviour if necessary 😊

2021-08-06 07:45 UTC, mfrachet commented on packages/core/admin/admin/src/components/LeftMenu/index.js
> +        icon={<img src={menuLogo} alt="" />}
Thinking of it, an empty alt should be enough and hiding it using aria-hidden is probably overkill. Will fix this in the DS 👍🏻

2021-08-06 08:06 UTC, HichamELBSI requested changes
Good job 👍🏽

2021-08-06 08:06 UTC, HichamELBSI commented on packages/core/admin/admin/src/components/LeftMenu/index.js
> +        {condensed ? 'Expanded the navbar' : 'Collapse the navbar'}
Can we use translated messages here please 😄

2021-08-06 08:06 UTC, HichamELBSI commented on packages/core/admin/admin/src/layouts/AppLayout.js
> +      <SkipToContent>Skip to main content</SkipToContent>
Same here, we should use translated messages

2021-08-06 09:02 UTC, merged