DS providers listview (draft)
strapi/strapi pull request #10744
Opened 2021-08-17 16:59 UTC by ronronscelestes

## What
DS integration in providers list view

## Issue
State => draft
SettingsIcon svg's size in Th is forced to 0.35rem in DS (used VisuallyHidden until fixed)
Switch component in listview? (user has to enter client ID / secret before switching status state)
Row + Stack : need align items + margin for icon && name

## Demo
<img width="1438" alt="Capture d’écran 2021-08-17 à 18 57 58" src="https://user-images.githubusercontent.com/71838159/129768899-e1095506-71b6-4e96-9ac0-66fbd8a9d9de.png">

2021-08-17 16:59 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=10744) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=10744) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=10744) it.</sub>

2021-08-18 14:45 UTC, maevalienard commented
By any chance, is it possible to add a Capital letter at the beginning of "Enable" & "Disable"? :)

2021-08-18 15:22 UTC, ronronscelestes commented
> By any chance, is it possible to add a Capital letter at the beginning of "Enable" & "Disable"? :)

Yes I will do that and use translated messages everywhere, I forgot about it!

2021-08-20 06:14 UTC, soupette requested changes
Can you also add some tests?

2021-08-20 06:14 UTC, soupette commented on packages/plugins/users-permissions/admin/src/pages/Providers/index.js
> +// import { Header, List } from '@buffetjs/custom';
You can remove these lines

2021-08-20 06:14 UTC, soupette commented on packages/plugins/users-permissions/admin/src/pages/Providers/index.js
> +  console.log(updatePermissions);
You can remove this also

2021-08-20 06:14 UTC, soupette commented on packages/plugins/users-permissions/admin/src/pages/Providers/index.js
> +    // isLoading,
Can you add a loading state ?

2021-08-20 06:14 UTC, soupette commented on packages/plugins/users-permissions/admin/src/pages/Providers/index.js
> +          title={formatMessage({ id: getTrad('HeaderNav.link.providers') })}
`formatMessage({ id: getTrad('HeaderNav.link.providers', defaultMessage: 'Providers' })`

2021-08-20 06:14 UTC, soupette commented on packages/plugins/users-permissions/admin/src/pages/Providers/index.js
> +                      {formatMessage({ id: getTrad('Providers.image') })}
`{formatMessage({ id: getTrad('Providers.image') , defaultMessage: 'Image' })}`

2021-08-20 06:14 UTC, soupette commented on packages/plugins/users-permissions/admin/src/pages/Providers/index.js
> +                  <TableLabel>{formatMessage({ id: getTrad('Providers.name') })}</TableLabel>
Same for the others can you add a `defaultMessage` ?

2021-08-23 11:17 UTC, soupette approved these changes
LGTM

2021-08-23 12:08 UTC, merged