UpgradePlanModal
strapi/strapi pull request #10881
Opened 2021-09-03 14:24 UTC by ronronscelestes

## What / Why

Integrated UpgradePlanModal with new DS to replace the old one
+ tests + storybook

## Demo

<img width="1440" alt="Capture d’écran 2021-09-03 à 16 24 08" src="https://user-images.githubusercontent.com/71838159/132021253-765c4592-7a0f-4984-9fde-ee6feba92595.png">

2021-09-06 09:10 UTC, bulby97 requested changes
Good job :)

2021-09-06 09:10 UTC, bulby97 commented on packages/core/admin/admin/src/components/UpgradePlanModal /UpgradePlanModal.stories.mdx
> +<!--- UpgradePlanModal.stories.mdx --->
Maybe I'm missing something, do we have storybook in the core admin ?. I thought it was installed in parts and helper-plugin.

2021-09-06 09:10 UTC, bulby97 commented on packages/core/admin/admin/src/components/UpgradePlanModal /index.js
> +const TextBold = styled(Text)`
we don't need this compo we have `<Text bold />`

2021-09-06 09:10 UTC, bulby97 commented on packages/core/admin/admin/src/components/UpgradePlanModal /index.js
> +const UpragdeWrapper = styled.div`
'Upgrade' :)

2021-09-06 09:10 UTC, bulby97 commented on packages/core/admin/admin/src/utils/useLockScroll.js
> +import { useEffect } from 'react';
We should be it in the helper-plugin

2021-09-06 09:10 UTC, bulby97 commented on packages/core/admin/admin/src/utils/setOpacity.js
> +const setOpacity = (hex, alpha) =>
We should put it in helper plugin and rename it (something like setHexOpacity maybe)

2021-09-06 13:47 UTC, soupette requested changes

2021-09-06 13:47 UTC, soupette commented on packages/core/helper-plugin/lib/src/utils/setHexOpacity.js
> +const setHexOpacity = (hex, alpha) =>
Can you add a small story for this so we have some kind of documentation?

You can put it in the utils section.

2021-09-06 13:47 UTC, soupette commented on packages/core/helper-plugin/lib/src/utils/useLockScroll.js
> +const useLockScroll = lockScroll => {
This should be in the hooks folder. Can you also add a story?

2021-09-07 06:20 UTC, soupette approved these changes
LGTM

2021-09-07 06:20 UTC, merged