migration/roles search
strapi/strapi pull request #10921
Opened 2021-09-09 08:40 UTC by markkaylor

### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2021-09-10 04:27 UTC, soupette requested changes
The UI does not seem to match the design 

<img width="776" alt="Screenshot 2021-09-10 at 06 26 46" src="https://user-images.githubusercontent.com/13311463/132799646-7fdc4f5b-f49e-4705-9eeb-4e1ccaaddb92.png">

2021-09-10 04:40 UTC, soupette requested changes

2021-09-10 04:40 UTC, soupette commented on packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/index.js
> +  const rolesList = sortedRoles.length ? sortedRoles : roles;
I don't think this is needed you can use the sortedRoles directly.

2021-09-10 04:40 UTC, soupette commented on packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/index.js
> +  const rowCount = roles && roles.length + 1;
`const rowCount = (roles?.length || 0 ) + 1 `

2021-09-10 04:40 UTC, soupette commented on packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/index.js
> +                  </Th>
Can you add another th for the actions?

```
<Th>
            <VisuallyHidden>
              {formatMessage({
                id: 'components.TableHeader.actions-label',
                defaultMessage: 'Actions',
              })}
            </VisuallyHidden>
          </Th>
```

2021-09-10 04:40 UTC, soupette commented on packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/tests/index.test.js
> +  useQueryParams: jest.fn(() => [{}]),
You don't need to mock this hook and the Search component you just need to change your App :

```
import { Router } from 'react-router-dom';
import { createMemoryHistory } from 'history';

jest.mock('@strapi/helper-plugin', () => ({
  ...jest.requireActual('@strapi/helper-plugin'),
  useTracking: jest.fn(() => ({ trackUsage: jest.fn() })),
  useNotification: jest.fn(),
  useRBAC: jest.fn(),
  CheckPermissions: ({ children }) => children,
}));


const makeApp = history => (
  <Router history={history}>
    <ThemeProvider theme={lightTheme}>
      <QueryClientProvider client={client}>
        <IntlProvider locale="en" messages={{ en: {} }} textComponent="span">
          <RoleListPage />
        </IntlProvider>
      </QueryClientProvider>
    </ThemeProvider>
  </Router>
);

```

And in your tests:

```js
const history = createMemoryHistory();
    const App = makeApp(history);
    const {
      container: { firstChild },
    } = render(App);
```

2021-09-10 07:54 UTC, markkaylor commented on packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/index.js
> +            </Row>
@soupette got this from the admin Users/LIstPage so that at least there is some consistency 🤷‍♂️

2021-09-13 16:55 UTC, soupette approved these changes
LGTM

2021-09-14 03:23 UTC, merged