Add empty state components
strapi/strapi pull request #10934
Opened 2021-09-10 15:08 UTC by mfrachet

Add components:

- NoPermissions
- NoContent
- NoMedia

And a story to initiate a default page template

2021-09-10 16:14 UTC, ronronscelestes approved these changes
LGTM 🔥

2021-09-12 07:33 UTC, mfrachet commented on packages/core/helper-plugin/lib/src/components/PageTemplate/PageTemplate.stories.mdx
> +                {(data && data.length === 0) && <NoContent content="No content available" action={<Button>Add content</Button>}/>}
```suggestion
                {(canRead && data && data.length === 0) && <NoContent content="No content available" action={<Button>Add content</Button>}/>}
```

2021-09-13 03:51 UTC, soupette requested changes

2021-09-13 03:51 UTC, soupette commented on packages/core/helper-plugin/lib/src/components/NoContent/NoContent.stories.mdx
> +      <NoContent content="There's no content" action={<Button>Add content</Button>} />
Can you add the content as a defaultProps so we don't have to recreate the translation nor look up for one each time we use this component?

2021-09-13 03:51 UTC, soupette commented on packages/core/helper-plugin/lib/src/components/PageTemplate/PageTemplate.stories.mdx
> +                primaryAction={<Button startIcon={<AddIcon />}>Add an entry</Button>}
It would be good if in the template you could use the translation messages.

2021-09-13 04:25 UTC, merged