Change project structure to use src/ folder
strapi/strapi pull request #10982
Opened 2021-09-15 14:52 UTC by petersg83

Using new src/ structure
```
config/
public/
database/ (not implemented yet)
src/
  admin/
  api/
  middlewares/
  policies/
  plugins/
  components/
```

It seems to work fine, tell me if you find unhandled usecases

2021-09-16 08:50 UTC, Elhebert submitted a review, later dismissed
LGTM 👌

2021-09-16 09:06 UTC, alexandrebodin requested changes
can we have a `strapi.srcDir` so when we make this configurable we won't have to find all the places with do the join ?

2021-09-20 07:30 UTC, alexandrebodin requested changes
This looks good but It's missing the templates copying logic to move the files to the right folders :)

2021-09-21 11:20 UTC, alexandrebodin approved these changes

2021-09-21 11:21 UTC, merged