Add static list of reserved names
strapi/strapi pull request #11434
Opened 2021-11-02 13:15 UTC by Elhebert

### What does it do?

Add a list of reserved names.

I've tested the values we had in v3 and removed the ones that were no longer breaking Strapi. I might have missed edge cases thought. I tried some MySQL reserved words as well to see if we needed to add them to the list, but we are good on that side.

2021-11-02 13:24 UTC, alexandrebodin requested changes

2021-11-02 13:24 UTC, alexandrebodin commented on packages/core/content-type-builder/server/services/builder.js
> +      attributes: ['id', 'created_at', 'updated_at', 'created_by', 'updated_by', 'published_at'],
You will need the camelCase values too

2021-11-02 15:34 UTC, alexandrebodin approved these changes
Good 1st version to start with

2021-11-02 23:29 UTC, derrickmehaffy commented
@Elhebert is this based on this tracking issue?
https://github.com/strapi/strapi/issues/1198

2021-11-03 08:19 UTC, Elhebert commented
@derrickmehaffy I was not aware of this issue. 
@alexandrebodin should I go through all the strings in the issue to see if we still need to safeguard them?

2021-11-03 08:32 UTC, alexandrebodin commented
I don't think you need to as you said we won't have problem with pluralization of the CTs. 

Let's see if the pbl is coming from the main branch maybe. I'm pinging the FE team

2021-11-03 09:22 UTC, Elhebert commented
In case it's needed here's the same unit test locally with node 14:
![Screen Shot 2021-11-03 at 10 20 41 AM](https://user-images.githubusercontent.com/3165079/140035482-1ed108e8-7d2d-4e43-9f5b-57b4fa02efda.png)

2021-11-03 10:09 UTC, alexandrebodin commented
let's merge and check on the main PR

2021-11-03 10:09 UTC, merged