QA/ Fix add component
strapi/strapi pull request #11442
Opened 2021-11-02 16:00 UTC by ronronscelestes

## What

Made "add component" box in CM clickable

## Demo

Go to a CT in CM
Create or edit an entry
When no entry in rep or not rep component click on the box to create one

2021-11-02 16:32 UTC, HichamELBSI requested changes

2021-11-02 16:32 UTC, HichamELBSI commented on packages/core/admin/admin/src/content-manager/components/ComponentInitializer/index.js
> +      onClick={handleBoxClick}
You don't need any ref here. You can use `onClick={onClick}`

2021-11-02 16:32 UTC, HichamELBSI commented on packages/core/admin/admin/src/content-manager/components/ComponentInitializer/index.js
> +    <CursorBox
You need to add `as` and `type` here. We should not use onClick on div.

```js
...
as='button'
type='button'
...
```

2021-11-02 16:32 UTC, HichamELBSI commented on packages/core/admin/admin/src/content-manager/components/ComponentInitializer/index.js
> +  };
You don't need that

2021-11-02 16:32 UTC, HichamELBSI commented on packages/core/admin/admin/src/content-manager/components/ComponentInitializer/index.js
>  const IconButton = styled(BaseButton)`
Can you change this to a span please.

```js
const IconWrapper = styled.span`...`;
```

2021-11-02 16:32 UTC, HichamELBSI commented on packages/core/admin/admin/src/content-manager/components/ComponentInitializer/index.js
> +    <CursorBox
and also, add the disabled props `disabled={isReadOnly}`

2021-11-02 16:32 UTC, HichamELBSI commented on packages/core/admin/admin/src/content-manager/components/ComponentInitializer/index.js
> +          <IconButton ref={addEntryButtonRef} disabled={isReadOnly} onClick={onClick}>
Here, you should use only icon wrapper and remove all the props.

```js
<IconWrapper>
   <PlusCircle />
</IconWrapper>
```

2021-11-03 08:46 UTC, soupette approved these changes
LGTM

2021-11-03 08:46 UTC, merged