v4/ Marketplace coming soon
strapi/strapi pull request #11504
Opened 2021-11-08 15:08 UTC by ronronscelestes

## What

Integrated new page layout for marketplace coming soon view

## Snapshot 

<img width="1438" alt="Screenshot 2021-11-08 at 16 08 23" src="https://user-images.githubusercontent.com/71838159/140766678-ad7522d4-34bf-461c-9862-2c3300fc8d74.png">

2021-11-09 16:00 UTC, HichamELBSI requested changes

2021-11-10 07:49 UTC, soupette requested changes
Can you add a test like a snapshot?

2021-11-10 07:49 UTC, soupette commented on packages/core/admin/admin/src/pages/MarketplacePage/index.js
> +  pxToRem,
Can you remove all the comments?

2021-11-10 07:49 UTC, soupette commented on packages/core/admin/admin/src/translations/en.json
> +  "app.components.InstallPluginPage.illustration": "marketplace illustration",
The translations should start by the following: `admin.pages.MarketPlacePage.`

2021-11-10 07:50 UTC, soupette commented on packages/core/admin/admin/src/pages/MarketplacePage/index.js
> +import MarketplacePicture from '../../assets/images/marketplace-coming-soon.png';
Can you put the png file inside the MarketPlace folder?

`admin/admin/src/pages/MarketplacePage/assets/marketplace-coming-soon.png`

2021-11-10 10:49 UTC, soupette approved these changes
LGTM

2021-11-15 08:23 UTC, merged