[V4] make lastname optional
strapi/strapi pull request #11587
Opened 2021-11-16 09:22 UTC by vincentbpro

### What does it do?

Makes the lastname optional for admin users

#### Front-end
Lastname field made optional at:
- register first admin form
- create admin user form
- update admin user form
- user profile form (admin/me)

Updated references to lastname across the app to handle an empty string

#### Back-end

Updated validations to accept empty lastname

### Why is it needed?

To reduce friction during the first admin registration

2021-11-17 10:54 UTC, HichamELBSI requested changes

2021-11-17 10:54 UTC, HichamELBSI commented on packages/core/admin/admin/src/utils/getFullName.js
> +};
Can you add some test for this file please

2021-11-17 12:44 UTC, alexandrebodin reviewed
Overall looks good 👍

2021-11-23 14:21 UTC, HichamELBSI approved these changes
LGTM

2021-11-23 14:27 UTC, alexandrebodin commented
just a conflict in a test file apparently

2021-11-23 16:05 UTC, merged