Make The User Name Required & Unique
strapi/strapi pull request #11812
Opened 2021-12-05 13:03 UTC by Louai99k

### What does it do?

It prevents the registering from '/api/auth/local/register' without specifying username and that username should be unique

### Why is it needed?

In the User from users-permissions plugin there is a place for username and in content-types it's unique (so when you create user from administration panel you should pass unique username) but it's not unique when we register from the specified endpoint

### How to test it?

If we try to make request to '/api/auth/local/register' from any request maker (e.g. Postman) we will be able to make new user without a username param

### Related issue(s)/PR(s)

The related issue: [](https://github.com/strapi/strapi/issues/11810)

2021-12-05 13:03 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=11812) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=11812) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=11812) it.</sub>

2021-12-06 12:04 UTC, nixxoff commented on packages/strapi-plugin-users-permissions/controllers/Auth.js
> +    // Username is required.
I think its overcommenting

2021-12-06 12:07 UTC, nixxoff commented on packages/strapi-plugin-users-permissions/controllers/Auth.js
> +    const username = await strapi.query('user', 'users-permissions').findOne({
instead of making username as result better to make variable as boolean for example is isUsernameUnique

2021-12-14 09:39 UTC, alexandrebodin commented
Hello, this PR is utdated with master. Could you udpate it ?

2021-12-14 17:17 UTC, petersg83 requested changes
Thank you for your PR!
I propose you to handle it differently.
Can you replace all strapi.query(...) calls by strapi.entityService calls ? (https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/crud.html#create)

The entity service does check the constraints whereas strapi.query does not. It would solve the issue since the constraints are correctly written in the schema `packages/plugins/users-permissions/server/content-types/user/index.js`.

Also you can add the username constraint in `registerBodySchema` in `packages/plugins/users-permissions/server/controllers/validation/auth.js` so there are checks both before being written in the db and at the request validation level.

If you don't feel doing it, please tell me so I do it on my side :)

2021-12-18 03:05 UTC, jamesfm-dev commented
> Also you can add the username constraint in `registerBodySchema` in `packages/plugins/users-permissions/server/controllers/validation/auth.js` so there are checks both before being written in the db and at the request validation level.

these results will be a breaking change on `/api/auth/local/register` api since it will have a min char limit, required field and must be unique based on `packages/plugins/users-permissions/server/content-types/user/index.js` to match the schema when creating a user on admin/ui panel.
```js
const registerBodySchema = yup.object().shape({
  username: yup
    .string()
    .min(3)
    .required(),

   some codes....
});
```

username unique checking should be done here `packages/plugins/users-permissions/server/controllers/auth.js` right?
```js
async register(ctx) {

  params.username
  some logic here....
}
```

2022-01-04 08:03 UTC, soupette commented
Hello @Louai99k your PR is outdated with master can you update it?

2022-01-04 08:24 UTC, alexandrebodin commented
Hello, This PR has been staled for more than 20 days. I will close it for now. If you want to pick it up, let us know :)

2022-01-04 08:24 UTC, closed without merging