Add unit tests for the entity validators
strapi/strapi pull request #11883
Opened 2021-12-13 13:23 UTC by Elhebert

### What does it do?

It add unit test for the different validators we have for the entities.

2021-12-13 15:53 UTC, alexandrebodin requested changes
That's looking very cool. 

Do we already have a test suite for the actually entity validator too ?

2021-12-13 15:53 UTC, alexandrebodin commented on packages/core/strapi/lib/services/entity-validator/__tests__/biginteger-validators.test.js
> +const entityValidator = require('../validators');
shouldn't this be called validators ?

2021-12-14 08:51 UTC, Elhebert commented
I had a look, but haven't seen anything. It might be tested through some of our e2e tho. But nothing specific.

I'll add some UT in there and will try to include as many cases as I can.

2021-12-15 09:52 UTC, alexandrebodin approved these changes
LGTM. Great improvements here

2021-12-15 09:53 UTC, merged