Translate en.json into traditional Chinese.
strapi/strapi pull request #11924
Opened 2021-12-15 16:12 UTC by duncanhsieh

### What does it do?

Translate en.json into traditional Chinese(zh.json).
Enable the traditional Chinese interface language. 

### Why is it needed?

Solve the problem of no Chinese interface language.

### How to test it?

Switch the interface language to Chinese and check the display status.
No additional features are added, and no new test code is required.

### Related issue(s)/PR(s)

none

2021-12-15 16:21 UTC, alexandrebodin requested changes

2021-12-15 16:21 UTC, alexandrebodin commented on packages/generators/app/lib/resources/files/src/admin/app.js
> +      'zh',
you can remove this

2021-12-15 16:42 UTC, duncanhsieh commented on packages/generators/app/lib/resources/files/src/admin/app.js
> +      'zh',
The new commit removes this change

2021-12-20 15:55 UTC, alexandrebodin approved these changes
LGTM. Thank you !

2021-12-20 16:40 UTC, merged