Adding support for using a relationships entry title as a repeatable entry title
strapi/strapi pull request #11938
Opened 2021-12-17 09:30 UTC by timbrandin

### What does it do?

Adding support for using relationships entry title as a repeatable entry title

### Why is it needed?

When a repeatable dynamic zone has a relationship to another node, what's displayed today is only a number, and one have to toggle open the section to see which item it is.

### How to test it?

1. Create a Person collection type with a field i.e name and add some people of that type.
2. Create a Page collection type that has a repeatable component field with a component that references a Person.
3. Create a page and add a couple persons to the field, it should now say the name of the person on the collapsed row rather than the a number.

### Before
![image](https://user-images.githubusercontent.com/1715834/146521743-81e15a5a-f103-4739-9b3e-41491a258d0b.png)

### After
![image](https://user-images.githubusercontent.com/1715834/146522066-337dd4df-04e8-43fd-a70d-a54a804ce4a8.png)

2021-12-17 09:30 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=11938) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=11938) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=11938) it.</sub>

2021-12-20 16:14 UTC, HichamELBSI requested changes

2021-12-20 16:14 UTC, HichamELBSI commented on packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/utils/select.js
> +    get(modifiedData, displayValuePath, '')
Hello @timbrandin,

Thanks for your contribution. IMO, for a better readability you can use `lodash/get` for `nestedObjectField` & `nestedObjectTitle` too.

```js
import get from 'lodash/get';
import toString from 'lodash/toString';

...

const defaultMainField = get(schema, ['settings', 'mainField'], 'id');
const mainField = get(
  schema,
  ['layouts', 'edit', 0, 0, 'metadatas', 'mainField', 'name'],
  defaultMainField
);
const nestedObjectField = get(schema, ['layouts', 'edit', 0, 0, 'name'], undefined);
const displayValuePath = nestedObjectField
  ? [...componentFieldName.split('.'), nestedObjectField, mainField]
  : [...componentFieldName.split('.'), defaultMainField];
const displayedValue = toString(get(modifiedData, displayValuePath, ''));
```

2021-12-20 16:14 UTC, HichamELBSI commented on packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/utils/select.js
> +    get(modifiedData, displayValuePath, '')
Can you also remove the useless `useMemo` please

2021-12-21 08:42 UTC, soupette commented
The displayed value of the repeatable component is a setting that is configurable in the setting view of the edit layout.

I think that the proposed solution is not the best one and we should instead allow the user to set a relation as a mainfield but this will require further enhancements in both the front-end and the back-end.

I am closing this PR as the implementation does not currently suits our need maybe we could open an issue in order to get insights from the Strapi team.

Thank you for so much for your contribution!

2021-12-21 08:42 UTC, closed without merging