Add all missing french translations
strapi/strapi pull request #11944
Opened 2021-12-18 19:55 UTC by maximeMD

### What does it do?

Add all missing french translations in the core/admin package

2021-12-18 19:55 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=11944) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=11944) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=11944) it.</sub>

2021-12-20 00:01 UTC, maximeMD commented on packages/core/admin/admin/src/translations/en.json
> -  "app.components.EmptyStateLayout.content-document": "No content found",
duplicate with line 259

2021-12-21 09:07 UTC, vincentbpro requested changes
Thanks for your contribution! Just one small change, the rest looks good to me.

2021-12-21 10:06 UTC, maximeMD commented
@vincentbpro done ! 😃

2021-12-21 10:09 UTC, vincentbpro approved these changes
LGTM!

2021-12-22 08:03 UTC, merged