Remove region from S3 Upload Provider Middleware Docs
strapi/strapi pull request #12252
Opened 2022-01-19 18:07 UTC by tsmith1024

### What does it do?

Updates S3 upload provider documentation to remove region from the Security Middleware Configuration.

### Why is it needed?

When including the region in the configuration, I was unable to see the thumbnails as expected. I was able to correct this issue by removing the region information from the `img-src` and `media-src` directives. S3 is region-less, so including the region is likely unneeded and that may explain why the issue was present.

### How to test it?

Using the S3 upload provider, set the `img-src` and `media-src` directives to include a region as originally documented, with a string like `yourBucketName.s3.yourRegion.amazonaws.com`. Notice if the thumbnails for uploaded images are shown as expected. Remove the region from the string and observe the new state of the thumbnails.

### Related issue(s)/PR(s)

No issues related to this issue found in a quick check.

2022-01-19 19:56 UTC, derrickmehaffy requested changes
See above note

2022-01-19 22:22 UTC, tsmith1024 commented
Thanks for the feedback and the link to the example project.

I took a look at our settings for my S3 bucket, and we're not using replication or cloud front. We are on `us-east-1`, but I'm not sure if that has an impact at all on it.

After testing with the example project, I am still seeing the same issue as before when including the region in the security policy directives. When it is included, the thumbnails don't load, and when I remove the region, the images load as expected.

I checked the console in the browser (Safari, if that matters), and am seeing this message (bucket/image names hidden):

*"Refused to load https://$BUCKET_NAME.s3.amazonaws.com/thumbnail_$IMAGE_NAME?width=1920&height=1920 because it does not appear in the img-src directive of the Content Security Policy."*

It'd be great to fully understand why we're seeing differences when we're using the same setup, with the exception of our AWS settings. I can put in an issue for now if you'd prefer, so there can be some tracking of this. If I get a chance, I hope to try soon with another region, likely us-west-2 given your test, to see if that shows any difference in results.

Another option, if you would prefer, would be to include a note here to try removing the region if thumbnails don't load with the region included.

Thanks for the help with this and I look forward to figuring out what's going on with it!

2022-01-20 02:27 UTC, tsmith1024 commented
Just did a test with `us-west-2` using, as best as I can tell, the same settings as my `us-east-1` bucket and it requires the region to be included.

2022-01-20 17:03 UTC, derrickmehaffy commented
> Just did a test with `us-west-2` and `us-east-2` using, as best as I can tell, the same settings as my `us-east-1` bucket and they both required the region to be included.

So you can confirm it is needed? maybe us-east-1 is the  only one that doesn't need a region. I've never tested this region due to the "issues" it commonly has we never deploy anything there :sweat_smile: 

If you want to add a note about if you are using us-east-1 and the proper domain for that. I find it odd that AWS would only do this for one region though.

2022-03-08 16:39 UTC, derrickmehaffy commented
Going to set this as closed as it only applies to us-east-1 all other regions need it

2022-03-08 16:39 UTC, closed without merging