Check that plugin name is kebab-cased upon generation
strapi/strapi pull request #12312
Opened 2022-01-26 12:15 UTC by WalkingPizza

### What does it do?

Checks that the plugin the user is about to generate has a kebab-cased name.

### Why is it needed?

Strapi only allows kebab-cased plugin names, but the `generate` utility does not check that this requirement is met upon plugin generation.

### How to test it?

Try generating a plugin with a non-kebab-cased name.

### Related issue(s)/PR(s)

Solves #12311

2022-03-10 10:27 UTC, markkaylor reviewed
@WalkingPizza this suggestion looks good.

I'm just wondering if we could format the user input ourself so that it is cased the way we want in the template file.

Maybe we could do that with inquirer somehow by transforming the input or use [case modifiers](https://plopjs.com/documentation/#case-modifiers) in the template file directly.

I think that would be interesting and we could also add `displayName` property to the package json strapi object using `titleCase`

Let me know what you think @WalkingPizza, if you agree with this approach and are willing to make the change that would be great. Otherwise we can merge this and I can explore that myself later on.

2022-03-10 10:38 UTC, WalkingPizza commented
Hey @markkaylor!

I think transforming the user input automatically is a very good idea, but what would we do when a user tries to generate a plugin with a non-kebab-cased name which converts to something that is already taken?

E.g.
1. User generates the `sample-plugin` plugin.
2. User generates the `samplePlugin` plugin, whose name is then automatically converted to `sample-plugin`, which is already taken.

I 100% agree with the automatic `displayName` property too, and I am more than happy to make the changes before this is merged.

2022-03-16 09:51 UTC, markkaylor commented
As it is right now if I generate a plugin with the same name the CLI throws an error. The generator should generate file paths in kebab case as well and then I think it wouldn't be possible to generate a plugin with the same name regardless of user input, right? Let me know if you spot something I'm not seeing. 

- User generates `sample-plugin` => `path/to/sample-plugin`
- User generates. `samplePlugin` (converted to sample-plugin) => `path/to/sample-plugin`
- CLI throws: `File already exists, abort` 

Here's what I'm thinking:

```hbs
// templates/plugin-package.json.hbs
 "name": "{{ pluginName }}", // kebab-case
  "version": "0.0.0",
  "description": "This is the description of the plugin.",
  "strapi": {
    "name": "{{ pluginName }}", // kebab-case
    "description": "Description of {{ pluginName }} plugin", // Title Case
    "kind": "plugin"
    "displayName":: {{ pluginName }} // Title Case
  },
```

```javascript
// plops/plugin.js
{
  type: 'add',
  path: 'plugins/{{ pluginName }}/package.json', // kebab-case
  templateFile: 'templates/plugin-package.json.hbs',
},
```

2022-03-28 09:20 UTC, WalkingPizza commented
@markkaylor I have:

1. Added a utility in `@strapi/utils` to convert strings to kebab-case since Lodash is not accessible directly inside the generators.
2. Added a warning when users try to generate a plugin whose name is automatically converted to kebab-case to notify them that Strapi only supports kebab-cased names and that the new plugin has been automatically renamed.
3. Added the displayName property to the newly generated `package.json`.

Let me know what you think!

2022-03-29 08:01 UTC, markkaylor requested changes
Awesome, this works great! Thanks @WalkingPizza, I just have one small comment and then I think we can approve and merge.

2022-03-29 08:08 UTC, WalkingPizza commented on packages/generators/generators/lib/templates/plugin-package.json.hbs
>      "description": "Description of {{ pluginName }} plugin",
Done!

2022-03-29 08:10 UTC, markkaylor submitted a review, later dismissed

2022-05-19 21:17 UTC, derrickmehaffy commented
@WalkingPizza can you resolve the conflicts?

2022-05-19 21:18 UTC, alexandrebodin approved these changes
Thank @WalkingPizza 💯

2022-05-20 07:02 UTC, merged