Docs: Update contributing guide
strapi/strapi pull request #12356
Opened 2022-01-31 08:38 UTC by gu-stav

### What does it do?

While going through the contributing guide for the first time today, I realized it needed some updates for v4. The PR also improves some wordings.

### Why is it needed?

The ensure a smooth setup experience.

2022-01-31 08:38 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=12356) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=12356) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=12356) it.</sub>

2022-02-04 09:01 UTC, pwizla submitted a review, later dismissed
Hey @gu-stav , thanks! I've reviewed your PR and suggested a few minor changes. Other than that, I think it looks much cleaner!

2022-02-04 10:22 UTC, gu-stav commented
@pwizla Thanks for you feedback. I've included all of it and made even more improvements. If you find the time, I'd appreciate another round of review 🚀

2022-02-04 12:53 UTC, pwizla commented
Thanks @gu-stav, I'll add this to my to-do list for next week.

2022-03-09 14:03 UTC, alexandrebodin requested changes
A few comments but that looks nice!

2022-03-09 14:03 UTC, alexandrebodin commented on CONTRIBUTING.md
> +- You have [Node.js](https://nodejs.org/en/) at version >= v12 and <= v16 and [Yarn](https://yarnpkg.com/en/) at v1.2.0+ installed.
To run the unit tests you need node 14 now we can increase the require version of contributing

2022-03-11 12:56 UTC, alexandrebodin commented on CONTRIBUTING.md
> +- You have [Node.js](https://nodejs.org/en/) at version >= v12 and <= v16 and [Yarn](https://yarnpkg.com/en/) at v1.2.0+ installed.
Wasn't updated :)

2022-03-11 12:58 UTC, gu-stav commented on CONTRIBUTING.md
> +Larger chunks of changes in Strapi, that might effect many users, require a thorough design phase before starting working on a PR.
Good suggestion. I have added a note and ran the whole document through Grammarly in 375f41d716dd086a9226c8b78ef6f06d4c3d874f

2022-03-11 13:17 UTC, alexandrebodin commented on CONTRIBUTING.md
> +Larger chunks of changes in Strapi, that might effect many users, require a thorough design phase before starting working on a PR.
Good idea 👍

2022-03-11 13:20 UTC, alexandrebodin approved these changes
LGTM

2022-03-14 07:44 UTC, merged