Handle direct quotes in JSON field
strapi/strapi pull request #12474
Opened 2022-02-10 17:32 UTC by petersg83

fix https://github.com/strapi/strapi/issues/12040

2022-02-10 21:48 UTC, soupette requested changes
I haven't tested it yet but I have noticed we have a bug when saving string values in the editor. To reproduce you can check out the getstarted app, the go the the `address`n collection type and set `"coucou"` in the JSON field. You will notice that after saving the value will be changed to `coucou` .

Can you take a look at it [here is the problematic line](https://github.com/strapi/strapi/blob/c106d19dd54b5e8adaab1ad5c3458967e38f6541/packages/core/admin/admin/src/content-manager/components/InputJSON/index.js#L83)

2022-02-15 09:53 UTC, soupette requested changes

2022-02-15 09:53 UTC, soupette commented on packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/schema.js
> +          isObject(value) ||
`isObject` returns true for arrays so you could either use `isPlainObject` && `Array.isArray` or just `isObject`

2022-02-15 09:53 UTC, soupette commented on packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/schema.js
> +          isObject(value) ||
Also can you split the imports of lodash function as follows:

`import get from 'lodash/get'; ` as it treeshakes better?

2022-02-15 11:01 UTC, HichamELBSI approved these changes

2022-02-16 13:27 UTC, soupette approved these changes

2022-02-16 14:05 UTC, merged