Upgrade purest to 4.x
strapi/strapi pull request #12635
Opened 2022-02-23 16:02 UTC by kwang1198

### What does it do?

Upgraded the version of purest to 4.x and modified `services/providers.js` to respect the updated interface.
Remove @purest/providers since it is no longer needed.

The following providers have been tested:

- [x] auth0
- [x] cognito
- [x] discord
- [x] facebook
- [x] github
- [x] google
- [x] linkedin
- [x] microsoft
- [x] reddit
- [x] twitch
- [x] twitter
- [ ] cas
- [ ] vk

Since `request()` in purest 4.x removes the callback argument and uses `Promise` instead, I also remove `callback` in `getProfile` in `services/provider.js` and the corresponding usage in `controllers/auth.js`.

### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

### Main update on the:

- [ ] Admin
- [ ] Documentation
- [ ] Framework
- [x] Plugin

### Manual testing done on the following databases:

- [x] Not applicable
- [ ] MongoDB
- [ ] MySQL
- [ ] Postgres
- [ ] SQLite

2022-02-23 16:02 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=12635) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=12635) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=12635) it.</sub>

2022-03-09 17:47 UTC, kwang1198 commented
@alexandrebodin sure, I can do it!

2022-03-10 08:38 UTC, alexandrebodin commented
Hi @kwang1198  thank you for the update. We merged a slight refactor that reorganizes the files. This will conflict with your PR but will make it easier to review once it is updated :)

2022-03-11 08:05 UTC, kwang1198 commented
@alexandrebodin I've adjusted my code to solve the conflicts.

2022-03-11 08:30 UTC, alexandrebodin requested changes

2022-03-11 08:30 UTC, alexandrebodin commented on packages/plugins/users-permissions/server/services/providers-list.js
>            github
We are missing a return here. the promise will resolve undefined instead of the object

2022-03-11 13:28 UTC, alexandrebodin commented
I'm sorry @kwang1198  but it appears purest is using a dependency coming from an external source and not a yarn or npm registry. 

We consider this as a potential security threat and this will block the merging to this PR :/ this would need to be changed in the purest lib itself before we can move forward.

2022-03-11 14:29 UTC, kwang1198 commented
@alexandrebodin that's unfortunate... I might ask the author if he'd like to publish the package it depends.

2022-03-12 07:50 UTC, simov commented
Hi, I stumbled upon this PR by chance .. yes, I had to patch the extend library because I needed this https://github.com/simov/node-deep-extend/commit/e26b5aca2535299db00cbc35cd891c0923a01fd6 I will take a look and see if I can find a replacement.

2022-03-12 12:56 UTC, simov commented
Published v4.0.2 where I am depending on my own fork of `deep-extend` over here: https://www.npmjs.com/package/@simov/deep-extend

All of my tags on GitHub are signed: https://github.com/simov/node-deep-extend/releases/tag/v1.0.0

Also added a Snyk badge for it: https://snyk.io/test/npm/purest though we will have to wait a little be for them to re-craw for the latest version.

Also migrated to GitHub Actions for running the tests: https://github.com/simov/purest/actions/runs/1973297316 since TravisCI no longer works.

Let me know if you have any issues.

2022-03-15 17:55 UTC, alexandrebodin commented
We are going to need a yarn conflict fix :)

2022-03-16 05:31 UTC, kwang1198 commented
@alexandrebodin I've fixed it.

2022-03-18 08:46 UTC, alexandrebodin commented
Hey @kwang1198  I don't seem to be able to update your branch I think your fork might be private or sth :) do you mind doing it ?

2022-03-18 09:05 UTC, kwang1198 commented
@alexandrebodin It looks like my fork is public. Not sure why you can't edit.

2022-03-18 09:33 UTC, simov commented
> @alexandrebodin It looks like my fork is public. Not sure why you can't edit.

@kwang1198 maybe checking this option https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2022-03-18 09:50 UTC, kwang1198 commented
@simov thanks! That option is already checked.

2022-03-24 12:58 UTC, alexandrebodin commented
Hey 👋 , we are having trouble with our CI I think you pulled and got some errors coming from outside your code, it should be fixed if you update your branch again. Sorry about asking again and again I usually can do it on my side

2022-03-24 16:49 UTC, kwang1198 commented
@alexandrebodin I rebased my branch with the lateset master but test still fails.  3 suites fail running `test:front`. Not sure whether it's normal or there's something wrong with my environment.

2022-04-06 15:35 UTC, alexandrebodin approved these changes
LGTM. Thank you for the upgrade :)

2022-04-06 15:35 UTC, merged