Fix sanitization of datetime type in query param
strapi/strapi pull request #12725
Opened 2022-03-03 02:31 UTC by luanorlandi

### What does it do?

Adds a separated verification for date type in the filter. Currently filters with type `Date` are being incorrectly handled as objects when sanitizing.

Currently, the result it's parsing a date/datetime value as an operator, due to `isObject(date)` from lodash handling dates as Objects, but with this PR it should parse as a primitive value.

### Why is it needed?

Filters of date and datetime are broken in GraphQL API. The query returns the entities without applying the filter.

### How to test it?

See the issue mentioned below, the steps should be similar but for the `example/getstarted`.

### Related issue(s)/PR(s)

Fix #12706 

The bug resulted from password sanitization in PR https://github.com/strapi/strapi/pull/11917 when released [v4.0.8](https://github.com/strapi/strapi/releases/tag/v4.0.8)

2022-03-03 02:31 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=12725) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=12725) before we can accept your contribution.<br/><hr/>**Luan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=12725) it.</sub>

2022-03-03 15:29 UTC, petersg83 commented
Thank you for your PR :) As mentioned in the issue, it seems already fixed by `4.1.2` which was released yesterday. If it's ok for you I will close this PR then :)

2022-03-04 01:00 UTC, luanorlandi commented
Hello @petersg83, thank you for looking into this issue. I believe is not fixed in `v4.1.2`.

See more details here: https://github.com/strapi/strapi/issues/12706#issuecomment-1058719547

2022-03-04 13:24 UTC, petersg83 requested changes
Thank you for you PR! It works on my side :)
I have a suggestion to make it more generic.
Can you, instead of handling dates, replace `isObject` by `isPlainObject` on line 289 and 352?

Also, if you have time, could you create a test for the field datetime (in a new file)? Otherwise no problem, I'll do it after the PR is merged :)

2022-03-04 22:01 UTC, luanorlandi commented
@petersg83 Thank you for the review, I applied your suggestions

The `isPlainObject` is working for `examples/getstarted` app and in e2e tests

2022-03-09 09:25 UTC, gu-stav approved these changes
Looks good to me now. Thanks for adding the `DateTime` tests 🌻

2022-03-11 09:28 UTC, MarionLemaire approved these changes
Tested on Getstarted using Chrome with GraphQL : filtering on date and dateTime is OK

2022-03-11 10:52 UTC, merged