Fix CTB reloading state
strapi/strapi pull request #12977
Opened 2022-03-28 14:57 UTC by soupette

Signed-off-by: soupette <cyril@strapi.io>

### What does it do?

It makes sure to wait for the server to have restarted before displaying the CTB.

### Why is it needed?

To improve the content modelling experience.

### How to test it?

Tests should be done in all 3 example apps (getstarted, kitchensink, kitchensink-ts)
1. Go to the ctb and create :
  - collection type
  - single type
  - a component
  A make sure it is working correctly
2. Do the same for PUT methods (add some field, edit some...)
3. Test the DELETE method for all created data structure.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2022-03-29 07:54 UTC, gu-stav approved these changes
I haven't tested it functionally, but the code looks good to. Two small suggestions, which you can ignore if you feel like they aren't that important.

2022-03-29 07:54 UTC, gu-stav commented on packages/core/admin/admin/src/reducers.js
> +  'strapi-admin_app': appReducer,
Just a suggestion: no need to change it: What do you think about naming it `admin_app` instead? All the others aren't prefixed with strapi either and there isn't another admin ...

2022-03-29 07:54 UTC, gu-stav commented on packages/core/content-type-builder/admin/src/components/DataManagerProvider/utils/request.js
> +          throw new Error('not available');
Could we improve the wording of this error message? :)

2022-03-29 15:31 UTC, Convly requested changes
Only one small suggestion

2022-03-30 07:38 UTC, Convly approved these changes
LGTM

2022-03-30 14:29 UTC, merged