Sanitize hidden attributes from admin API responses
strapi/strapi pull request #13185
Opened 2022-04-26 12:55 UTC by Convly

### What does it do?

It removes hidden attributes from responses in the admin API responses.

### Why is it needed?

Since `hidden` attributes are meant to be hidden from the admin panel, it makes no sense to return them in the API responses. 

### How to test it?

1. Set any attribute of any content type as "hidden"
2. Create some data for that specific content type
3. Go to the edit view or the list view of the admin panel
4. Check the network console of your browser to see if the attribute is omitted in the GET call.

2022-05-02 17:09 UTC, alexandrebodin reviewed
Can you had end to end test that verify the data is not present in the CM responses ? in the list and get one apis?

2022-05-10 05:03 UTC, Convly commented
> Looks good! Can you add end to end test that verify the data is not present in the CM responses ? in the list and get one apis?

Done :heavy_check_mark: 

On a side note, we'll probably need to update the sanitation flow for the admin users in next iterations so that it uses the permissions manager sanitize instead of the custom one defined in the services. WDYT?

2022-05-11 08:33 UTC, alexandrebodin requested changes
Overall looks good, just one last thing

2022-05-11 08:56 UTC, alexandrebodin commented on packages/core/content-type-builder/server/services/schema-builder/component-builder.js
> +        .set('config', infos.config)
I thought you wanted to allow setting the config via the API so It was missing. But if we only use it through the services that's fine 👍

2022-05-11 08:56 UTC, alexandrebodin approved these changes

2022-05-11 08:58 UTC, merged