Add more injection zones
strapi/strapi pull request #13434
Opened 2022-05-31 15:42 UTC by WalkingPizza

### What does it do?

This PR aims at adding additional injection zones into Strapi, mainly for plugin development.
It related to both [this RFC](https://github.com/strapi/rfcs/pull/37) and [this other one](https://github.com/strapi/rfcs/pull/44).

The injection zones being added in this PR are the following:

**Homepage**
1) `before-content` lets developers add content before the content blocks and social links.
2) `after-content` lets developers add content after the content blocks and social links.

**List view**
1) `header-actions` lets developers add content next to the _Create new entry_ button.
2) `action-icons` lets developer add content next to the edit/duplicate/delete icons.
3) `bulk-actions` lets developers add content next to the _Delete_ button when multiple entries have been selected.

**Edit view**
1) `before-form` lets developers add content before the content form and information cards.
2) `after-form` lets developers add content after the content form and information cards.
3) `header-actions` lets developers add content next to the _Save_ and _Publish_ buttons.

### Why is it needed?

The list of existing injection zones was pretty scarce, and discussing with other plugin developers, I realized there was a need for more injection zones. This will hopefully allow devs to improve their plugin's UX and allow for a more customizable admin panel.

### How to test it?

You can embed [this snippet](https://gist.github.com/WalkingPizza/32dd633d2a01c628eb73e6d453a9bd57) in the `bootstrap` function of your plugin to add placeholders in the new injection zones and see their positioning on your own admin panel, or look at the attached screenshots.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/34224657/171214063-ef1d282e-5fb5-4bd1-abe8-7db67b458333.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/34224657/171214165-79418dfa-1e54-4fec-922a-a71996fc9875.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/34224657/171214211-a22272f6-ba8d-4e26-8997-acf8e7409933.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/34224657/171214244-8cd53658-e53e-4a13-8daf-1b745008cb8a.png">

2022-06-03 07:37 UTC, soupette requested changes
I am not sure we can accept this PR at the moment injection zones it's a whole new can of worms and we need to be careful when creating new ones.

I'll let @maevalienard decide if wether or not we should merge it

2022-06-03 07:49 UTC, WalkingPizza commented on packages/core/admin/admin/src/content-manager/components/DynamicTable/index.js
> +      additionalBulkActions={[
Which hooks are you talking about?

2022-06-03 07:54 UTC, soupette commented on packages/core/admin/admin/src/content-manager/components/DynamicTable/index.js
> +      additionalBulkActions={[
https://github.com/strapi/strapi/blob/98c8b5360439af4ac6ecde3c9503200ab5fb166c/packages/core/admin/admin/src/exposedHooks.js#L6

2022-06-03 14:31 UTC, maevalienard commented
Hello 👋 First of all, thanks for opening this RFC/PR.

Injection zones are a tricky and complex topic. It could quickly become like Pandora's box if we don't pay attention. One of our objectives at Strapi is to be able to allow enough customization for anyone who would like to use the product. 

As of now, we are not ready in terms of interface scalability and documentation to open such many doors. I agree that in terms of customization, it gives a lot of freedom but we also have to think of scalability, responsiveness, and user experience. The List and Edit views of the Content Manager are 2 of the most important pages of Strapi as a CMS, and we need as much clarity as possible on these 2. 

When I mention scalability, it's considering the fact that we have to imagine what the Content Manager looks like if a project has the Draft/publish system enabled, and downloaded 3 plugins with 1 main Call-to-Actions each (in the header-actions zone highlighted above). Should all 5 buttons be displayed next to each other? Should we have a dropdown button? Should we technically limit to a specific number of buttons and how do we do that? 
It's one example among many others but we have to prepare the interface and the guidelines for that first. 

In a near future, we'll for sure open a few more injection zones. We need to deepen the work first (and if you are interested in the journey, I'll be happy to be your buddy), by anticipating all types of situations and open them step by step  :)

2022-06-06 13:27 UTC, torchsmith commented
@maevalienard 
> One of our objectives at Strapi is to be able to allow enough customization for anyone who would like to use the product. ... I agree that in terms of customization, it gives a lot of freedom but we also have to think of scalability, responsiveness, and user experience.

I think that you should be letting the plugin developers worry about responsiveness and user experience here. You say one of Strapi's objectives is "to allow enough customization for anyone who would like to use the product", and you agree with the PR hitting that goal "I agree that in terms of customization, it gives a lot of freedom..."; so why not let the plugin developers worry about responsiveness, and user experience?

I understand the issues with potential future issues with scalability, but if InjectionZone locations are going to be removed or changed, isn't that what deprecation is for?

@soupette 
> at the moment injection zones it's a whole new can of worms and we need to be careful when creating new ones.

I can see InjectionZones all the way back to [v4.0.0-beta.2](https://github.com/strapi/strapi/releases/tag/v4.0.0-beta.2) , so I'm not sure why they would be unstable (or something like that) enough that we need to be careful creating new ones.

Kind regards,
Isaac

2022-06-06 15:34 UTC, derrickmehaffy commented
In terms behind our meaning of "unstable", it's more so leaning towards the fact they are subject to change (including breaking changes) without jumping a major version. The main worry as I understand is not implementing anything we can can't change without causing breaking changes.

2022-07-25 07:57 UTC, maevalienard commented
Hi! We're still figuring out the best way to introduce new injection zones for now. I'll close this PR for now, but please be aware that we took into account the need of your side. We're working on it :)

2022-07-25 07:57 UTC, closed without merging

2022-08-19 19:18 UTC, torchsmith commented
It's been a month. Any news @maevalienard. My clients don't want or need to see the Docs, Code samples, Tutorials, Blog, or the "Join the community" section.

2022-08-20 17:11 UTC, WalkingPizza commented
> It's been a month. Any news @maevalienard. My clients don't want or need to see the Docs, Code samples, Tutorials, Blog, or the "Join the community" section.

Hey @torchsmith, sorry if I jump in even though I'm not a Strapi employee.

Have you considered modifying the homepage using patch-package instead?

Having discussed injection zones with Maeva and some other Strapiers in the past, and being very familiar with plugin development, I have the feeling that even if an injection zone were to be added in that area, you'll probably not be able to swap out the content but rather add additional blocks to it.

If you are not familiar with patch-package and need help with it and the homepage customization, feel free to ping me on the Strapi Discord, I'm KevinRI on there!

2022-08-22 12:41 UTC, maevalienard commented
@torchsmith The homepage injection zone will probably not be the first one we'll start with. We still have the topic in mind, but this will take a little more time. I'm sorry this suffers from delays. 

The solution suggested by @WalkingPizza might be a great help for your usecase indeed :)

2023-02-23 21:48 UTC, justinyjsong commented
Any updates on this item? Would appreciate if we have `bulk-actions` injections zones for bulk-publish.

2023-03-01 23:30 UTC, torchsmith commented
They'll probably never get around to making these adjustments lol.