[marketplace] add providers tabs
strapi/strapi pull request #13462
Opened 2022-06-03 15:17 UTC by markkaylor

What does it do?
Adds tabs for the marketplace to support Plugins and Providers

Why is it needed?
To make it easy to distinguish between plugins and providers

How to test it?
Go the Markateplace page and select the different tabs:

You should only see plugins on the plugins tab and providers on the providers tab

Note:
I realized we didn't consider how to handle installed providers so aren't marked as such in this PR.

@remidej I think we should discuss and handle it in another PR based off this one so we can keep moving forward with the search as well.

2022-06-03 16:05 UTC, remidej requested changes
We'll also have to remember to add tests in another PR

2022-06-03 16:05 UTC, remidej commented on packages/core/admin/admin/src/pages/MarketplacePage/index.js
> +                  <Tab>Providers ({marketplaceProvidersResponse.data.length})</Tab>
These may need to have translation, or at least it's worth checking with Emilie

2022-06-03 16:05 UTC, remidej commented on packages/core/admin/admin/src/pages/MarketplacePage/index.js
> +            <TabGroup label="Some stuff for the label" id="tabs" variant="simple">
Don't we have anyhting to put here as a label?

2022-06-07 07:59 UTC, markkaylor commented
> We'll also have to remember to add tests in another PR
What test case do we need to check here? For some reason I thought even with these changes the snapshot test was enough... 🤔

2022-06-07 10:09 UTC, remidej reviewed
All the code changes look good to me, thanks!

For the tests: first we'd have to update the snapshot (the checks currently fail because of it).

But I was thinking we could add a smarter test for the tabs:

- check that by default the plugins tab is active, and we see a list of plugins
- simulate a click on providers
- check that the providers tab is now active, and we see a list of providers

2022-06-13 12:13 UTC, merged