Enhancement/user
strapi/strapi pull request #13657
Opened 2022-06-30 07:57 UTC by ivanThePleasant

### What does it do?

This PR adds functionality to create a unique ID for admin registrations. For the first admin, unique admin id is added at the time of registration. For any other admin roles unique admin id is added only when the user follows the link to complete the registration. This is to avoid adding unnecessary identification to users that haven't completed registration. Any non-admin users are not affected. Unique admin ID is also added when new admin user is registered via the CLI command.

### Why is it needed?

The goal is to be able to use this unique admin id with Amplitude in order to better understand which admin roles use what functionality in Strapi. However, we will not use the actual unique admin id, only its hash. The goal is to be able to confidently distinguish unique users, their role and their actions in Strapi without being able identify the actual person. This will help us to understand what functionality in Strapi is redundant, what is needed and will help us to better plan for new features.

### How to test it?

Run `getstarted` application, register the admin, then you can check the sqlite db file to the the generated `unique_user_id` column and the corresponding data.

2022-06-30 09:39 UTC, ivanThePleasant commented
Apologies for the force push, I have rebased the branch in order to get rid of the merge conflict

2022-07-01 07:10 UTC, alexandrebodin requested changes
I really don't think we should add a property in the db for this.
We would either have to manage migration for existing projects or just not have the data which in both cases isn't great.

Have you considered using a hash(projectUUID + userId) to get that consistent value without having to store it?

2022-07-01 07:23 UTC, ivanThePleasant commented
Hey @alexandrebodin, thanks for your reply! 
I considered using a hash of project uuid + userId, but decided not to go with it for the following reason: since we're using SQL databases, userID auto-increments; hence, if the project changes db (say deletes their sqlite db file) and start over without migrating data, new hashes can start pointing to different same users thus skewing our data. Kinda sounds like a really thin edge case, but I thought it's possible. Admittedly, I might be missing something in this approach, so happy to get your opinion on it 😊
In regards to manage migration for existing projects - do you mean migration on Amplitude or migration in their project DBs?

2022-07-01 07:47 UTC, fdel-car commented
We already discussed doing it with the `projectUuid` + `userId`, and I still think it's the way to go.

> and start over without migrating data, new hashes can start pointing to different same users thus skewing our data

To counteract that, we could use `projectUuid` + "creation time of this user" (`created_at` I think, Strapi uses snake casing for that) + `userId` and there you will have a unique ID per user across environments/databases.

2022-07-01 07:56 UTC, ivanThePleasant commented
What about the case where same db is migrated to a new project with a new `projectUuid`? 🤔

2022-07-01 08:10 UTC, fdel-car commented
1. I don't think it will happen often, and changing the `projectUuid` is already creating new projects on our analytics, so it wouldn't shock me if that case would create new users in our analytics as well.

2. If you really wanna fix that and use the same users on Amplitude, then what we could do is compute the result of hash(`projectUuid` + `created_at` + `userId`) only if it's not already in the database, and store it afterward for future analytics calls. So it will be in the database, but no migration is needed, it's easy to compute on the first analytics call.

I would not do 2. though, I don't think migrating to a new project with a new `projectUuid` would skew the data, but maybe I missed something.

2022-07-01 08:25 UTC, ivanThePleasant commented
I agree that 2 is a bit too much. But regarding the new projectUuid - that's kinda the whole idea with cohorts, as the same user could be identified across different projects. That would allow to understand user migrations, how often they switch projects by migrating db, etc. Unfortunately, I can't estimate how often this could happen and that was my motivation to keep id in db. But on the other hand swapping to having a dynamic hash is quick, so if everyone says that's the preferred way, I can do it no problem

2022-07-11 15:11 UTC, ivanThePleasant commented
I will now close this PR since, after considering hashing admin credentials on the fly, it makes more sense. Instead of updating this PR, I'll make a new one.

2022-07-11 15:11 UTC, closed without merging