[Custom Fields] Add custom fields registry on server
strapi/strapi pull request #13708
Opened 2022-07-06 12:39 UTC by markkaylor

### What does it do?

Add a custom fields registry on the Strapi instance

### Why is it needed?

To allow users to add the configuration for a custom field to Strapi

### How to test it?

- The example custom field plugin is registering a custom field. You should be able to see it by running:
`yarn strapi console` => `strapi.container.get('custom-fields').getAll()`
- In `examples/getstarted/src/plugins/mycustomfields/server/register.js` replace the register function with the following to test registering multiple custom fields at once:
```js
  strapi.customFields.register([
    {
      name: 'color',
      plugin: 'mycustomfields',
      type: 'text',
    },
    {
      name: 'map',
      plugin: 'mycustomfields',
      type: 'json',
    },
  ]);
```
You should see both your custom fields when re-running `yarn strapi console` => `strapi.container.get('custom-fields').getAll()`
- Remove `plugin` from one of the test objects, the custom field should be registered as: `global::color` instead of `plugin::mycustomfields.color`
- Remove name or type, or both, you should get an error
- Register the same custom field twice, you should get an error

2022-07-06 14:19 UTC, remidej approved these changes
Looks good to me

2022-07-06 15:50 UTC, alexandrebodin requested changes
You are missing the necessary unit tests :)

2022-07-06 15:50 UTC, alexandrebodin commented on packages/core/strapi/lib/core/registries/custom-fields.js
> +    register(customField) {
it's too bad it doesn't match with the other registries. 

I think we probably want to split the user API vs the internal registry.

2022-07-06 15:53 UTC, remidej commented on packages/core/strapi/lib/core/registries/custom-fields.js
> +          : `global::${strapi.config.uuid}.${name}`;
I think to get the same value on the frontend we'd need to make an API call. Could we maybe pick something more hardcoded instead? Like `global::global.${name}` or `global::${name}.${name}`

2022-07-06 15:56 UTC, alexandrebodin requested changes

2022-07-12 07:27 UTC, alexandrebodin commented on packages/core/strapi/lib/core/registries/custom-fields.js
> +          : `global::global.${name}`;
```suggestion
          : `global::${name}`;
```

2022-07-12 07:27 UTC, alexandrebodin commented on packages/core/strapi/lib/core/registries/custom-fields.js
> +        const namespace = strapi.plugin(plugin)
```suggestion
        const uid = strapi.plugin(plugin)
```

2022-07-12 07:27 UTC, alexandrebodin commented on packages/core/strapi/lib/Strapi.js
> +    return createCustomFields(this);
this will recreate the service everytime.  You will want to do this in the constructor instead here.

2022-07-13 13:24 UTC, merged