Fix 13774: Add support for mysql2 driver
strapi/strapi pull request #13775
Opened 2022-07-14 01:55 UTC by benderillo

### What does it do?

When `mysql` client is specified in database settings, Strapi will test for multiple possible packages that could be used as the driver for this type of the client (in order of priority: `mysql2`, `mysql`).

### Why is it needed?

This fixes the issue https://github.com/strapi/strapi/issues/13774
When a developer wants to use `mysql2` driver it is currently impossible as knex is configured to look for `mysql` only.

### How to test it?

1. Create a strapi project and configure database client as "mysql".
2. Install `mysql2` driver (`npm install mysql2`). Make sure you don't install the mysqljs (`mysql`).
3. Run strapi and check that it starts normally without failing to find a package.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/13774

2022-07-14 13:46 UTC, derrickmehaffy reviewed
Hey now we are getting somewhere, keeping compatibility for mysql (v2) is a must. I'll test this out.

2022-07-14 13:48 UTC, derrickmehaffy commented
FYI we will need tests for this also

2022-07-14 17:08 UTC, derrickmehaffy commented
hey @benderillo I was comparing this PR to: https://github.com/strapi/strapi/pull/12918 as this is the PR where we introduced the better-sqlite3, @vscode/sqlite3, and sqlite3 legacy system.

I would like to keep a similar structure with mysql2 vs mysql as I'm not 100% sure that the mysql2 package will work properly with MariaDB yet (need to test).

And I was mirroring some of the logic (haven't tested it yet) but wanted to see what you thought: https://github.com/strapi/strapi/compare/21f510eaea06d772638e8eb6f0ad5ea94f3c2a72...dm/test-mysql2

Also we will need to add tests for mysql2 much like we do with sqlite3

2022-08-04 00:43 UTC, benderillo commented
@derrickmehaffy I don't mind to keep the `mysql` package prioritised over the `mysql2`. This still solves the problem. Those who use mysql will not be affected and those who has both installed will continue be on `mysql`.
Only those who made conscious choice for `mysql2` will be using it then.

Can't promise anything in terms of dev effort on this PR though. 
I am up to tits in my own work and just back from holidays so....

With regards to the tests, there needs to be a guide somewhere or an example how do you test stuff like this.
As my learning time pretty limited, I am unable to go reverse-engineering path on this.

2022-11-28 02:50 UTC, limichange reviewed
LGTM

2022-11-28 02:53 UTC, limichange commented
https://railway.app/ and https://planetscale.com/ need mysql2 client to work, I just test it, which is an excellent job. 👍

2023-01-27 03:18 UTC, drizztdourden08 commented
Support for better connection security to a MySQL database should be a priority in my opinion. This pull request work perfectly fine. I just did the change manually to the core package in my installation and it went flawlessly and Strapi can access the database without any issues.

This should be reviewed, approved and merged.

The one over on the feedback is marked as complete while this is untrue: https://feedback.strapi.io/developer-experience/p/add-support-for-mysql2-mysql-v8-auth-system

2023-02-19 21:28 UTC, 4matic commented
Agree with @drizztdourden08 - this should be reviewed, approved and merged as soon as possible.

2023-02-27 20:32 UTC, alexandrebodin requested changes
Hi, this looks just fine. Could you look at how we do the test for the different sqlite version in the github workflows and add one for the mysql 2 package ?

2023-02-27 20:35 UTC, derrickmehaffy commented
For reference:

https://github.com/strapi/strapi/blob/948dbb3121330ffd43f3a4f55522c797770e0b2a/.github/workflows/tests.yml#L215-L237

And:

https://github.com/strapi/strapi/blob/948dbb3121330ffd43f3a4f55522c797770e0b2a/.github/workflows/tests.yml#L326-L352

2023-04-03 14:30 UTC, closed without merging