fix/typescript-webpack-config-not-loaded-in-building-13754
strapi/strapi pull request #13905
Opened 2022-07-29 15:02 UTC by simotae14

What does it do?
It resolve the bug "Custom admin webpack config does not resolve to compiled js in TS project" [https://github.com/strapi/strapi/issues/13754](https://github.com/strapi/strapi/pull/url)
fix {https://github.com/strapi/strapi/issues/13754}

Why is it needed?
Because it wasn't possible to define a webpack.config file with the typescript extension, now it is possible to provide the .js and the .ts versions and to compile the typescript version in javascript

How to test it?
Just create a webpack.config.ts inside one example projects and then build the example

2022-07-29 15:33 UTC, innerdvations reviewed
I noticed we also have [this check](https://github.com/strapi/strapi/blob/74a2b908df75bc8001d72f9dc8571c4b7a2da337/packages/core/admin/utils/should-build-admin.js#L37) that might need to be updated as well

2022-08-01 09:08 UTC, Convly requested changes

2022-08-01 09:08 UTC, Convly commented on packages/core/admin/utils/get-custom-webpack-config.js
> +  if (fs.existsSync(adminConfigPathJS) || fs.existsSync(adminConfigPathTS)) {
Could you extract those `fs.existsSync` calls to some variables so that you don't need to recompute it a second time on line 18?

2022-08-01 09:08 UTC, Convly commented on packages/generators/app/lib/resources/json/ts/tsconfig-server.json.js
> -    'src/admin/',
Since this is the server tsconfig file, I don't think we should remove the `src/admin` directory from the excluded property here.

2022-08-03 13:13 UTC, Convly approved these changes
Tested on my side, it works great.

LGTM

2022-08-03 13:19 UTC, Convly approved these changes

2022-08-03 13:22 UTC, merged