Fix upload of menu logo
strapi/strapi pull request #13964
Opened 2022-08-03 13:54 UTC by petersg83

### What does it do?

[Fix ](https://github.com/strapi/strapi/issues/13762) (allow users to change the logo in the settings)

### Why is it needed?

To fix the bug

### How to test it?

Try to change the logo, see success

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/13762
https://github.com/strapi/strapi/issues/13906

2022-08-03 14:32 UTC, vincentbpro approved these changes
Nice catch :wink: LGTM

2022-08-03 18:43 UTC, gu-stav requested changes

2022-08-03 18:43 UTC, gu-stav commented on yarn.lock
> -"@internationalized/number@^3.1.1":
This doesn't look good to me 🤔 . Could you rebase on the latest master and regenerate the lockfile? Looks like there is a version mis-match of the design-system dependency.

2022-08-04 08:26 UTC, gu-stav approved these changes
🌞 🚀

2022-08-04 08:38 UTC, petersg83 commented
waiting for QA :)

2022-08-09 16:40 UTC, MarionLemaire approved these changes
Tested on Getstarted using Chrome, changing logo in EE 3 times and saving them then going back to initial logo : OK 
![image](https://user-images.githubusercontent.com/97893822/183708742-ac969d70-c9fd-43ad-83a2-c8b345bd8a2a.png)

2022-08-09 16:41 UTC, merged