Fix CVE-2022-24434 and GHSA-2fvv-qxrq-7jq6
strapi/strapi pull request #14439
Opened 2022-09-16 18:38 UTC by derrickmehaffy

Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

Fixes https://github.com/advisories/GHSA-wm7h-9275-46v2
Fixes https://github.com/advisories/GHSA-2fvv-qxrq-7jq6

I didn't see any breaking changes on GraphQL upload even though it was a bunch of major version upgrades: https://github.com/jaydenseric/graphql-upload/releases

Prob need some people to test and verify though. 

You can manually apply these fixes until the next release if you are using yarn by setting the following in your `package.json`:

```json
"resolutions": {
    "apollo-server-core": "3.10.2",
    "graphql-upload": "16.0.2"
  },
```

2022-09-20 08:25 UTC, Convly requested changes
This break the imports since `graphql-upload` now requires importing using full path + .mjs extension. Also, need to update the path there:

**packages/plugins/graphql/server/bootstrap.js**
`const { graphqlUploadKoa } = require('graphql-upload/graphqlUploadKoa.mjs');`
 +
**packages/plugins/graphql/server/services/internals/scalars/index.js**
`const { GraphQLUpload } = require('graphql-upload/Upload.mjs');`

Which we cannot do since we cannot use import statements

@alexandrebodin do you think supporting .mjs import is something we could want? I'm not sure to have all the implications in mind.

2022-09-20 11:56 UTC, alexandrebodin commented
> This break the imports since `graphql-upload` now requires importing using full path + .mjs extension. Also, need to update the path there:
> 
> **packages/plugins/graphql/server/bootstrap.js** `const { graphqlUploadKoa } = require('graphql-upload/graphqlUploadKoa.mjs');` + **packages/plugins/graphql/server/services/internals/scalars/index.js** `const { GraphQLUpload } = require('graphql-upload/Upload.mjs');`
> 
> Which we cannot do since we cannot use import statements
> 
> @alexandrebodin do you think supporting .mjs import is something we could want? I'm not sure to have all the implications in mind.

I don't think we can import mjs from common js to start with 🤔 it only works the other way around. So we are stuck for now. 

There is a way for package maintainers to export both cjs and mjs in their packages but sadly it's not done by everyone so it creates a gap in the ecosystem until we all migrate to mjs. (v5 for us if not TS)

2022-09-20 12:20 UTC, derrickmehaffy commented
I might be able to drop the upload package to v15 as it looks like the migration to v16 was the implementation of .mjs

2022-10-20 14:46 UTC, derrickmehaffy commented
@alexandrebodin I chatted with @Convly yesterday and we both believe we need your sign-off to move forward with this one as it poses a security risk to switch to another fork but for the moment it's the only easy option other than ripping out the code form this package and including it directly in our code-base or going and finding an alternative (I looked but didn't see anything easy to implement).

What the author of the package did is pretty lazy switching to straight ESM.

2023-02-27 20:23 UTC, alexandrebodin commented
I think we can close this as they fixed it on their side if I recall

2023-02-27 20:23 UTC, closed without merging