Fixing error when building without src/admin
strapi/strapi pull request #14459
Opened 2022-09-22 04:16 UTC by CleberRossi

Checking if folder src/admin exists before checking for files inside.

Committer: Cleber Jose de Rossi
Changes to be committed:
	modified:   packages/core/admin/utils/__tests__/get-custom-app-config-file.test.js
	modified:   packages/core/admin/utils/get-custom-app-config-file.js

### What does it do?
Fixed a problem that when you did not have a src/admin folder strapi build command would give an Error. What I did was: ¨I checked if the folder /src/admin existed before trying to read the files inside."

### Why is it needed?
Seems like on strapi v3 people did not have this kind of need, having /scr/admin, so a lot of people when migrating to strapi v4 is facing this type of error

### How to test it?
Remove /src/admin folder and try to run `yarn build`

### Related issue(s)/PR(s)
#13975

2022-09-22 04:16 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=14459) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=14459) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=14459) it.</sub>

2022-09-28 13:28 UTC, Convly requested changes
Hey @CleberRossi thanks for opening this PR & contributing to Strapi :slightly_smiling_face: 

I've tested your fix, and it works great, thank you for that :slightly_smiling_face: 
Could you update your branch with the latest changes so that we can merge the PR on main please?

2022-09-28 13:37 UTC, Convly approved these changes
LGTM, waiting for the tests to pass & merging

2022-09-28 14:23 UTC, CleberRossi commented
> LGTM, waiting for the tests to pass & merging

@Convly  All done :)

2022-09-28 14:24 UTC, merged