[POC] Fix i18n overriding initialData
strapi/strapi pull request #14476
Opened 2022-09-27 16:31 UTC by ronronscelestes

## What

As stated in the #13988 issue, the content-manager is not supposed to know anything about what is coming from i18n.
It means that when we are "filling from another locale" we are actually updating the `redux-store`, updating `initialValues` passed to `EditViewDataManagerProvider`, which in response dispatch `INIT_FORM`. It causes `initialData` to be replaced by the i18n values.
The Save button then stays disabled because `modifiedData` and `initialData` are equal.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/71838159/192578283-29353e8b-5c28-4ce0-8e0c-996b74250ae8.png">

## Solutions opened to discussion

**1. Create a content-manager dispatch that would allow recovering lost values**

This is the redux dispatch that causes `initialValues` to change:

```
dispatch({ type: 'ContentManager/CrudReducer/GET_DATA_SUCCEEDED', data: cleanedData });
```

First solution explored was to dispatch a `RECOVER_INITIALDATA` accessible through `useCMEditViewDataManager` that would recover this data
This solution doesn't work because we cannot control in which order those dispatches are done.

**2. Create another dispatch in the crudReducer**

We could create another kind of dispatch in the `ContentManager/CrudReducer` which could pass information to the `content-manager` to let it know it is an update coming from `i18n`.
There could be different ways to do that but they all involve a change of paradigm which is to let the `content-manager` know something about `i18n`.

**3. Strapi in core and/or update the state management**

This could be a v5 conversation:
We also could question why i18n is not included in the core of Strapi.
Could we reconsider the usage of Context and closed reducers, to move most concerns to the redux store?

2022-09-28 12:52 UTC, joshuaellis commented
So to be clear a typical flow for updating an entry is as follows(?):

* Load page
* `initialData` populates entry
* Update the field
* `modifiedData` has been changed so save button is enabled
* Click save
* `modifiedData` is posted to API
* page is refetched
* `initialData` populates the entry, `modifiedData` is empty

_If_ this is correct, can we not expose something in the `useCMEditViewDataManager` to allow updates to the `modifiedData`? could be a valuable addition to allow plugins to update the state of the content manager? So therefore, when the plugin copies the data from one locale to the other instead of setting initialData in the FE (where it is now out of sync with the BE) we set modified data which populates the correct fields & allows saving (to resync with the BE).

2022-09-28 14:17 UTC, jhoward1994 commented
We could modify the INIT_FORM reducer to something like this? To detect when the re-initialisation is a change of locale and omit the change to initialValues
```
      case 'INIT_FORM': {
        draftState.formErrors = {};
        draftState.modifiedData = action.initialValues;
        draftState.modifiedDZName = null;
        draftState.shouldCheckErrors = false;

        if (
          !isNil(draftState.initialData.locale) &&
          draftState.initialData.locale !== action.initialValues.locale
        ) {
          break;
        }
        draftState.initialData = action.initialValues;
        break;
      }
```

2022-09-28 15:43 UTC, ronronscelestes commented
> So to be clear a typical flow for updating an entry is as follows(?):

Small difference but that holds the main issue:

* Load page
* `initialData` and `modifiedData` are populated with the data, `modifiedData` is the data used to populate the entry/the fields
* Update the field
* `modifiedData` has been changed so save button is enabled - yes because we can compare `modifiedData` and `initialData` and see a difference between them
* Click save
* `modifiedData` is posted to API
* page is refetched
* `initialData` is filled with updated data, `modifiedData` is ~~empty~~ equal to `initialData`


> _If_ this is correct, can we not expose something in the `useCMEditViewDataManager` to allow updates to the `modifiedData`? could be a valuable addition to allow plugins to update the state of the content manager? So therefore, when the plugin copies the data from one locale to the other instead of setting initialData in the FE (where it is now out of sync with the BE) we set modified data which populates the correct fields & allows saving (to resync with the BE).

🤔 I think that could be a workaround indeed - but when I chatted about that with @soupette it didn't seem possible to remove this dispatch

```
dispatch({ type: 'ContentManager/CrudReducer/GET_DATA_SUCCEEDED', data: cleanedData });
```

and this one makes the `INIT_FORM` dispatch happening after the update on `modifiedData` like you are suggesting, which results in the same issue we have currently
I'm not sure **if and why** we can't remove it / what would be the impact though 👀

2022-09-28 15:50 UTC, ronronscelestes commented
> We could modify the INIT_FORM reducer to something like this? To detect when the re-initialisation is a change of locale and omit the change to initialValues


thanks for the proposition! 
I thought about it while doing some random tests and I think that could be a fix indeed - I didn't fully test it though, I will to make sure it would work 👀
that still implies we accept the idea that the `content-manager` treats `i18n` specific use-case / knows something about `i18n` which is a change of paradigm we've had so far
I'm not against it personally but since it's been built this way I wanted to open the discussion with everyone first

2022-11-16 14:17 UTC, joshuaellis requested changes

2022-12-08 08:47 UTC, ronronscelestes commented
fix implemented in #15098

2022-12-08 08:48 UTC, closed without merging