add getNumberOfDraftRelations route
strapi/strapi pull request #14547
Opened 2022-10-05 16:48 UTC by petersg83

### What does it do?

Add a Content-Manager route to get the number of draft relations an entity has.

### Why is it needed?

To display a warning message to the user in case they wants to publish an entity that is still linked to draft entities

2022-10-07 09:44 UTC, jhoward1994 requested changes
I found a small problem when plugging the FE in to the BE for single types. WDYT?

2022-10-07 09:44 UTC, jhoward1994 commented on packages/core/content-manager/server/routes/admin.js
> +    },
The FE has no access to a single types id from the EditView, therefore I think this route will need to run without access to the `id`
```suggestion
    {
      method: 'GET',
      path: '/single-types/:model/actions/numberOfDraftRelations',
      handler: 'single-types.getNumberOfDraftRelations',
      config: {
        middlewares: [routing],
        policies: [
          'admin::isAuthenticatedAdmin',
          {
            name: 'plugin::content-manager.hasPermissions',
            config: { actions: ['plugin::content-manager.explorer.read'] },
          },
        ],
      },
    },
```

2022-10-07 09:44 UTC, jhoward1994 commented on packages/core/content-manager/server/controllers/single-types.js
> +  },
We could then change the way we get the single type entity and pass in `entity.id` to the entityManager?
```suggestion
  async getNumberOfDraftRelations(ctx) {
    const { userAbility } = ctx.state;
    const { model } = ctx.params;

    const entityManager = getService('entity-manager');
    const permissionChecker = getService('permission-checker').create({ userAbility, model });

    if (permissionChecker.cannot.read()) {
      return ctx.forbidden();
    }

    const entity = await findEntity({}, model);
    if (!entity) {
      return ctx.notFound();
    }

    if (permissionChecker.cannot.read(entity)) {
      return ctx.forbidden();
    }

    return entityManager.getNumberOfDraftRelations(entity.id, model);
  },
```

2022-10-07 12:54 UTC, jhoward1994 approved these changes
Works well with my FE changes. I just had a couple of documentation ideas for the trickiest parts of this change. WDYT?

2022-10-07 12:54 UTC, jhoward1994 commented on packages/core/content-manager/server/services/utils/draft.js
> +
```suggestion
/**
 * sumDraftCounts works recursively on the attributes of a model counting the
 * number of draft relations
 * These relations can be direct to this content type or contained within components/dynamic zones
 * @param {Object} entity containing the draft relation counts
 * @param {String} uid of the content type
 * @returns {Number} of draft relations
 */
```

2022-10-07 12:54 UTC, jhoward1994 commented on packages/core/content-manager/server/services/utils/populate.js
> +
```suggestion
/**
 * getDeepPopulateDraftCount works recursively on the attributes of a model
 * creating a populate object to count all the unpublished relations within the model
 * These relations can be direct to this content type or contained within components/dynamic zones
 * @param {String} uid of the model
 * @returns {Object} populate
 * @returns {Boolean} hasRelations
 */
```

2022-10-07 13:59 UTC, petersg83 commented
Yes good idea! Done :)

2022-10-10 13:37 UTC, Marc-Roig commented on packages/core/content-manager/server/routes/admin.js
> +      path: '/single-types/:model/actions/numberOfDraftRelations',
should we add the new routes in [`Relations in main view`](https://www.notion.so/strapi/Relations-in-main-view-Architecture-c977fb72e36942a68be56d08c274bff5) notion page?

2022-10-10 14:15 UTC, Marc-Roig commented on packages/core/database/lib/query/helpers/populate/apply.js
> +        .execute({ mapResults: false });
Nevermind @petersg83  I was playing with the debugger, restarting the app and looking at it again gives me the correct query 🤔 .

2022-10-10 14:43 UTC, Marc-Roig approved these changes
LGTM

2022-10-10 15:18 UTC, merged