feat(wip): add visual reordering of relations
strapi/strapi pull request #14811
Opened 2022-11-08 12:21 UTC by joshuaellis

### What does it do?

* Adds keyboard-navigation for re-ordering relations
* Adds live region for announcing the actions during re-ordering

### Context
This follows the aria-spec to implement keyboard navigation with re-ordering that I had to source for numerous places, namely Atlassian's approach (which makes perfect sense imo). It's designed this way _because_ we have clickable areas inside our relations i.e. the link to the entity, therefore you need a button to attach too. It's also added this way in the `adobe spectrum` project.

### Why is it needed?

* Because some user's might not be able to use their mouse.

### How to test it?

* There are automated tests

### Related issue(s)/PR(s)

* should be merged after #14800
* resolves CONTENT-656

2022-11-09 10:56 UTC, jhoward1994 requested changes
I'm having an issue where I can't click on drag handle to move a relation around, only the main content of the relation item.

It seems to be because the click event of `IconButton` is fired on mouse up rather than mouse down.

2022-11-09 16:10 UTC, joshuaellis commented
> I'm having an issue where I can't click on drag handle to move a relation around, only the main content of the relation item.
> 
> It seems to be because the click event of `IconButton` is fired on mouse up rather than mouse down.

Hey @jhoward1994 what browser are you using? 🤔 I don't see this issue on my end rn but with more info i'll look into it 🕵🏼

2022-11-09 16:43 UTC, jhoward1994 commented
> > I'm having an issue where I can't click on drag handle to move a relation around, only the main content of the relation item.
> > It seems to be because the click event of `IconButton` is fired on mouse up rather than mouse down.
> 
> Hey @jhoward1994 what browser are you using? 🤔 I don't see this issue on my end rn but with more info i'll look into it 🕵🏼

Aha! I was testing with Firefox, it seems to be working for me in Brave/Chrome too

2022-11-10 10:18 UTC, jhoward1994 approved these changes
Looks good, working well for me now on all browsers

2022-11-10 12:12 UTC, gu-stav commented on packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
> +            {formatMessage({
Can we please pass that through as a prop? If we decide to move the component into the DS we shouldn't have a dependency on react-intl.

2022-11-11 11:03 UTC, gu-stav reviewed
The code looks good to me. Only two minor comments. During the test I found the following things a bit weird (they are not related to the PR but I wanted to mention them anyways):

- Icon outline overflows the label

<img width="455" alt="Screenshot 2022-11-11 at 11 54 30" src="https://user-images.githubusercontent.com/2244375/201327045-a06034ef-a5cf-4209-b9ff-b255be293b0d.png">

- If there is only one item the handler is not visible: I understand where this is coming from, but I don't like the visual shift tbh. What do you think about checking with Maeva to see if we should disable it instead?

<img width="455" alt="Screenshot 2022-11-11 at 11 56 02" src="https://user-images.githubusercontent.com/2244375/201327024-27562de1-b7b0-445f-95da-9a80a9dc0d75.png">

- the state is already updated on `drag` which causes the `save` button to flicker (from disabled to enabled) even though I have not dropped the item yet. Do you think it is worth doing something about that?

2022-11-11 11:09 UTC, joshuaellis commented
> the state is already updated on drag which causes the save button to flicker (from disabled to enabled) even though I have not dropped the item yet. Do you think it is worth doing something about that?

Whilst I agree this is a bit annoying, this would require more of a refactor i.e. we have to clone (as opposed to use) `modifiedData` state into `RelationInputDataManager`component and use that and then at point X replace that in the store.
IMO this is a problem with our implementation of the `save` button, a better way to do it in the future could be "canSave" in the store so we can have better control over when it changes as opposed to see if there are changes in `modifiedData`.

> If there is only one item the handler is not visible: I understand where this is coming from, but I don't like the visual shift tbh. What do you think about checking with Maeva to see if we should disable it instead?

cc @maevalienard for some design guidance.

> Icon outline overflows the label

This is because the `IconButton` has it's own padding which the design does not adhere too. cc @maevalienard for more design guidance

2022-11-11 11:10 UTC, joshuaellis commented on packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
> +  listAriaDescription: PropTypes.string,
> pass in the translated string

we do already I believe. But yes, we can make them required & remove their defaults.

2022-11-14 10:03 UTC, maevalienard commented
> If there is only one item the handler is not visible: I understand where this is coming from, but I don't like the visual shift tbh. What do you think about checking with Maeva to see if we should disable it instead?

Interesting. Here are my thoughts:
- For one-way relations: no icon displayed at all.
- For many-ways relations: icon always displayed. Even if you only have selected one relation. And no disable at all, because that's still fun to play around, we could benefit from the discoverability :) 

> Icon outline overflows the label
I assume the drag&drop icon has been added via an iconButton so there are no possibilities to actually reduce the hit zone of this component for this usecase? I think we could consider having a slightly more padding-left on the relation label to avoid that. What do you think?

2022-11-14 12:21 UTC, gu-stav commented on packages/core/admin/admin/src/content-manager/components/RelationInput/components/RelationItem.js
> +
What do you think about using `Stack spacing={1}` as a wrapper below instead?

2022-11-14 12:23 UTC, gu-stav commented on packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
> +      toOneRelation={toOneRelation}
What do you think about passing `canReorder` down instead? It makes the implementation a bit more independent ...

2022-11-14 15:18 UTC, gu-stav requested changes
It works really well for me now! Thanks.

I've noticed a visual glitch though, if the content of the main field is too long:

<img width="353" alt="Screenshot 2022-11-14 at 16 14 46" src="https://user-images.githubusercontent.com/2244375/201696679-044e824e-ad2b-407b-bef6-c45a678a0f87.png">

Also: the `Status` is no longer aligned at the end.

2022-11-14 15:21 UTC, joshuaellis commented
Thanks, I assume this is to do with wrapping the icon and description in Stack. 

I'll take a look to see if it's easily solvable, otherwise I'll revert back to the previous solution of using a wrapper.

2022-11-15 08:43 UTC, ronronscelestes requested changes
great work 🔥
still seeing an issue with alignment of the status badge on my side 😬 status should be stacked next to the cross icon: 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/71838159/201871762-484ee82c-3d11-4ff9-9bbc-bebcc9ef42f2.png">

no more overflow issue though 💃
<img width="240" alt="image" src="https://user-images.githubusercontent.com/71838159/201871903-dfe31027-d662-41ef-b02c-2f0ef5987985.png">

2022-11-15 08:57 UTC, ronronscelestes approved these changes
LGTM ✨🙏

2022-11-15 10:52 UTC, merged