update Traditional Chinese translation
strapi/strapi pull request #14922
Opened 2022-11-18 04:47 UTC by 5idereal

2022-11-18 04:47 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=14922) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=14922) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=14922) it.</sub>

2022-11-22 10:50 UTC, ronronscelestes requested changes
hi @5idereal, thank you for those great translation improvements!
I highlighted 3 translations key are missing their Chinese translations (they are still in English) 🙂

2022-11-22 10:50 UTC, ronronscelestes commented on packages/core/content-type-builder/admin/src/translations/zh.json
> +  "components.SelectComponents.displayed-value": "{number, plural, =0 {# components} one {# component} other {# components}} selected",
I think this one is missing its translation? 👀

2022-11-22 10:50 UTC, ronronscelestes commented on packages/core/content-type-builder/admin/src/translations/zh.json
> +  "notification.error.dynamiczone-min.validation": "At least one component is required in a dynamic zone to be able to save a content type",
this one too :)

2022-11-22 10:50 UTC, ronronscelestes commented on packages/plugins/i18n/admin/src/translations/zh.json
> +  "Settings.list.empty.description": "This is not a usual behavior, meaning that you have eventually modified the database manually. Make sure to have at least one locale saved in your database in or
this one too

2022-11-22 12:27 UTC, 5idereal commented
Thanks for the review! I've updated the translation files.

2022-11-22 12:53 UTC, ronronscelestes approved these changes
thank you for the fixes @5idereal :)
I'll merge your PR once the tests are ✅

2022-11-22 15:03 UTC, merged