Add Turkish translation
strapi/strapi pull request #15145
Opened 2022-12-10 20:09 UTC by bdaylik

### What does it do?

Added Turkish translation. No code changes.

### Why is it needed?

To better serve Turkish speaking users.

### How to test it?

Just select Turkish language in your profile settings.

### Related issue(s)/PR(s)

None I know of.

2022-12-10 20:10 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=15145) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=15145) before we can accept your contribution.<br/><hr/>**Baris Can Daylik** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=15145) it.</sub>

2022-12-12 15:05 UTC, ronronscelestes requested changes
hi @bdaylik - that's a huge and great addition, thank you!
left a small comment about a translation file not being translated 😊

2022-12-12 15:28 UTC, bdaylik commented on packages/plugins/i18n/admin/src/translations/tr.json
> +  "CMEditViewCopyLocale.copy-failure": "Failed to copy locale",
oops missed that one, good catch.
I'll get back to work then :)

2022-12-12 21:43 UTC, bdaylik commented on packages/plugins/i18n/admin/src/translations/tr.json
> +  "CMEditViewCopyLocale.copy-failure": "Failed to copy locale",
I've translated the I18N plugin as well. Can you recheck?

2022-12-13 10:48 UTC, bdaylik commented
@ronronscelestes Looks like all checks are passed. Can you please merge this in?

2022-12-13 10:50 UTC, merged

2022-12-21 13:45 UTC, SalahAdDin commented
Thanks big bro, it helps a lot!