Add tiny piece of documentation around the relation component structure
strapi/strapi pull request #15223
Opened 2022-12-20 15:22 UTC by gu-stav

### What does it do?

Adds a few words of documentation about how and why the components for relations are structured the way they are.

### Why is it needed?

Completes documentation.

### Related issue(s)/PR(s)

https://strapi-inc.atlassian.net/browse/CONTENT-661

2022-12-20 15:26 UTC, joshuaellis requested changes

2022-12-20 15:26 UTC, joshuaellis commented on docs/docs/core/content-manager/relations.mdx
> +The API to update the entiy expects relations to be categorised into two groups, a `connect` array and `disconnect` array.
```suggestion
The API to update the entity expects relations to be categorised into two groups, a `connect` array and `disconnect` array.
```

lol nice try 😉

2022-12-20 15:26 UTC, joshuaellis commented on docs/docs/core/content-manager/relations.mdx
> +### `RelationInputDataManager`
Should we be adding how the useRelation hook works?

2023-01-18 07:46 UTC, gu-stav commented on docs/docs/core/content-manager/relations.mdx
> +  onLoad: ({ target: { name: string, value: RelationResults }}):void => {};
@joshuaellis Can you help me here to properly express the type? 😨

2023-01-18 08:42 UTC, joshuaellis approved these changes

2023-01-18 08:46 UTC, merged