E2E Signup
strapi/strapi pull request #15595
Opened 2023-01-26 11:48 UTC by jhoward1994

2023-02-07 12:24 UTC, joshuaellis requested changes
Biggest concern is how small these tests are and how much setup they require. This is up for discussion but if we look at the password stuff it could just be one test? Or even more they're quite "unit based" would it make more sense to make them user-flow?

so for example, one test could be `test("that a user cannot submit the signup form if the email is not lowercase or not an email address")`

2023-02-07 13:48 UTC, ronronscelestes commented
interesting thoughts @joshuaellis - if we agree on that idea I'd have to try and merge some of login tests too 👀

2023-02-07 16:54 UTC, jhoward1994 commented
@joshuaellis thanks that makes sense. Just to double check, is this the approach you're suggesting? (e.g. of email test case)

```
  test('that a user cannot submit the signup form if the email is not lowercase or not an email address', async ({
    page,
  }) => {
    await fillValidSignUpForm({ page });

    const emailInput = page.getByRole('textbox', { name: 'Email *' });

    await emailInput.fill('ADMIN@ADMIN.COM');
    await page.getByRole('button', { name: "Let's start" }).click();

    await expect(page.getByText('The value must be a lowercase string')).toBeVisible();
    await expect(emailInput).toBeFocused();

    await emailInput.fill('notanemail');
    await page.getByRole('button', { name: "Let's start" }).click();

    await expect(page.getByText('Value is an invalid email')).toBeVisible();
    await expect(emailInput).toBeFocused();
  });
```

2023-02-07 17:07 UTC, Boegie19 commented
I think you would need unit tests to validate that the validation is correct aka upercease character two @ s in 1 email this will be much faster then doing that all in an end to end test.


Still that still requires 2 times end to end test checking 1 if the validation is actually used properly 
and 1 where you go trough all the correct staps and it works

Also if you where to go for the above approach would make every fill its own test since now if one expects you only know that one of the 10 tests you do is broken  since all tests after that will be ignored since it is in the same test and it already expect and errored 

aka 
that a user cannot submit the signup form if the email is not lowercase
is one
that a user cannot submit the signup form if not an valid email address

2023-02-07 18:20 UTC, Boegie19 commented
> Yes @jhoward1994 E2E tests take ages to run especially with the DTS stuff so it's best to try and do as much as reasonably possible in one test imo. @gu-stav would you agree?

Still would it not be better to use a BeforeAll to set it up and the test environment and then you can put them all in different tests and use the same environment Like what you are trying to do with putting as many tests as possible in 1 test block is just bad practice and the reason the BeforeAll hook exists

2023-02-07 18:43 UTC, joshuaellis commented
> > Yes @jhoward1994 E2E tests take ages to run especially with the DTS stuff so it's best to try and do as much as reasonably possible in one test imo. @gu-stav would you agree?
> 
> Still would it not be better to use a BeforeAll to set it up and the test environment and then you can put them all in different tests and use the same environment Like what you are trying to do with putting as many tests as possible in 1 test block is just bad practice and the reason the BeforeAll hook exists

Respectfully, we've taken quite a lot of time to get to this point of doing tests and it's why we're doing it internally and it's your opinion that it's bad practice. Other people would disagree. E2E tests are not unit, they should be long flows imo. 

It's all a WIP and we'll be changing things as we go along.

2023-02-07 22:23 UTC, derrickmehaffy commented
> 

Is it the tests themselves that eat up most of the time? From when I was diving into them it wasn't so much each individual test that was taking that much time but the suites were not really optimized (we have a ton of legacy tests that really don't test anything valuable or their results when they do fail don't really point to the failure root cause).

Wouldn't it be a better idea to instead create more tests and simplify what we are testing and ideally build them in such a way we could run some in parallel?

2023-02-08 07:59 UTC, joshuaellis commented
> Is it the tests themselves that eat up most of the time? From when I was diving into them it wasn't so much each individual test that was taking that much time but the suites were not really optimized (we have a ton of legacy tests that really don't test anything valuable or their results when they do fail don't really point to the failure root cause).

These are actual E2E tests, not the API ones that just test the BE so i'd say this is a little different and could be addressed separately.

> Wouldn't it be a better idea to instead create more tests and simplify what we are testing and ideally build them in such a way we could run some in parallel?

This is something that can be looked into (i'd expect DX to take this up in the future) for now it's OSS as we're trying to get "some" level of confidence in not breaking the core flows of the application, we're just starting at authentication because it's a small enough surface to spot a lot of issues in the playwright setup.

I also imagine when Marion is back that QA will have more of a role in it too.

2023-02-08 12:00 UTC, jhoward1994 commented
@joshuaellis the tests have been refactored in [`2816774` (#15595)](https://github.com/strapi/strapi/pull/15595/commits/2816774303353d7fb0ac23bd1827e9be7e99ffab)

2023-02-10 11:39 UTC, gu-stav commented on e2e/authentication/signup.spec.js
> +    ).toBeTruthy();
I wouldn't test it that way, because it tests internals: instead: I'd leave the field empty and submit the form, which shouldn't work.

2023-02-10 11:39 UTC, gu-stav commented on e2e/authentication/signup.spec.js
> +    expect(await emailInput.getAttribute('aria-required')).toBeTruthy();
Same about this one.

2023-02-10 11:39 UTC, gu-stav commented on e2e/authentication/signup.spec.js
> +    await fillEmailAndSubmit('ADMIN@ADMIN.COM');
Could you use the global email address here?

2023-02-10 11:39 UTC, gu-stav commented on e2e/authentication/signup.spec.js
> +    });
Same about this.

2023-02-10 11:39 UTC, gu-stav commented on e2e/authentication/utils/index.js
> +};
Should we make this a local function in the spec until it needs to be shared one day eventually?

2023-02-10 12:34 UTC, joshuaellis approved these changes

2023-02-10 12:34 UTC, joshuaellis commented
Great job 💪🏼

2023-02-10 12:35 UTC, gu-stav approved these changes
👏🏼

2023-02-10 13:05 UTC, merged