Prevent uploading files that have unallowed file type
strapi/strapi pull request #15612
Opened 2023-01-27 18:19 UTC by M-tarek93

### What does it do?
Inspired from @joshuaellis [#15458](https://github.com/strapi/strapi/pull/15458), It prevents admin panel users from uploading different file types than the allowed types.
Ex: A user trying to upload a pdf while the field restricts uploads to only images.
Instead, it shows a notification telling the user that the file type isn't allowed.
### Why is it needed?
I tried the same issue after the latest release version(4.6.0) and found it still exists. So, I have moved the validation to the correct place and tested it.

### How to test it?
Refer to the first issue for re-producing it.

### Related issue(s)/PR(s)
Fixes: 
[#15608](https://github.com/strapi/strapi/issues/15608)
[#15486](https://github.com/strapi/strapi/issues/15486)
[#15326](https://github.com/strapi/strapi/issues/15326)

Related to:
[#15458](https://github.com/strapi/strapi/pull/15458)
[#15328](https://github.com/strapi/strapi/pull/15328)

2023-01-30 08:22 UTC, joshuaellis requested changes
Thanks for the PR! Would you be able to add some tests that specifically illustrate the problem your PR solves please? :) 

Also I know you've said look at the original template for "how to test", i'd really appreciate it if you could fill that section in thats specific to your changes. It would also help me understand more why moving the function helps better.

2023-01-30 10:27 UTC, M-tarek93 commented
Hi @joshuaellis,

I have added more details to the PR.

2023-02-01 08:38 UTC, joshuaellis commented
this now breaks if you try to "drop" an item in the media input that is a not a valid file type.

2023-02-07 17:21 UTC, joshuaellis submitted a review, later dismissed

2023-02-10 13:30 UTC, joshuaellis approved these changes

2023-02-10 14:23 UTC, merged