Add route to change rate limit + set default config
strapi/strapi pull request #15705
Opened 2023-02-03 11:19 UTC by petersg83

- Add route to change rate limit
- Set rate limit to false by default
- Set autoOpen to false by default

2023-02-03 11:23 UTC, ronronscelestes approved these changes
bioutiful ❤️

2023-02-03 11:24 UTC, jhoward1994 approved these changes
🚀

2023-02-03 11:31 UTC, gu-stav reviewed
Nice one!

Does the config.set approach work for any setting you have in the BE?

2023-02-03 14:55 UTC, petersg83 commented
@gu-stav Not all config
All config that is read dynamically on each request : yes
If it's read only at startup and not read again after : no

2023-02-03 17:19 UTC, petersg83 commented
I add you @joshuaellis as a reviewer as I needed to change some e2e setup so the API tests pass

2023-02-06 08:23 UTC, joshuaellis requested changes
small typo but otherwise thanks for doing this :)

2023-02-06 08:23 UTC, joshuaellis commented on package.json
> +    "test:e2e:setup": "yarn test:generate-app --appPath test-apps/playwright --template==../e2e/app-template",
```suggestion
    "test:e2e:setup": "yarn test:generate-app --appPath test-apps/playwright --template=../e2e/app-template",
```

2023-02-06 08:32 UTC, petersg83 commented on package.json
> +    "test:e2e:setup": "yarn test:generate-app --appPath test-apps/playwright --template==../e2e/app-template",
good eye :)

2023-02-06 09:19 UTC, petersg83 commented
Something is broken in the setup, working on it

2023-02-06 09:57 UTC, petersg83 commented
should be fixed now

2023-02-06 10:08 UTC, joshuaellis approved these changes

2023-02-06 10:56 UTC, gu-stav approved these changes

2023-02-06 14:36 UTC, merged