fix: remove expect-ct response header
strapi/strapi pull request #16292
Opened 2023-04-04 12:11 UTC by candidosales

### What does it do?

The `koa-helmet` 7.0.1 has the `helmet 6`and it `helmet.expectCt` is no longer set by default.

- `koa-helmet` 7.0.1: https://github.com/venables/koa-helmet/releases/tag/v7.0.1
- `helmet` 6.0.0: https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md#600---2022-08-26

<br class="Apple-interchange-newline">

### Why is it needed?

The `Expect-CT` header is deprecated and will be removed. Chrome requires Certificate Transparency for all publicly trusted certificates issued after April 30, 2018. 

![CleanShot 2023-04-04 at 08 01 19@2x](https://user-images.githubusercontent.com/186637/229787246-93092545-b95d-40dc-abc0-42d818adf447.png)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2023-04-04 12:11 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=16292) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=16292) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=16292) it.</sub>

2023-04-04 19:40 UTC, candidosales commented
@Convly , could you review it?

2023-04-04 19:43 UTC, candidosales commented
@nathan-pichon , could you review it?

2023-04-26 19:45 UTC, candidosales commented
@christiancp100 , could you review it?

2023-05-09 08:00 UTC, Convly approved these changes

2023-05-09 08:01 UTC, Convly requested changes
Could you update the yarn lock file too please?

2023-05-09 22:14 UTC, candidosales commented
@Convly, it's done.

2023-05-10 08:51 UTC, Convly approved these changes

2023-05-10 08:51 UTC, merged