Update DS to 1.7.0
strapi/strapi pull request #16500
Opened 2023-04-25 16:36 UTC by joshuaellis

### What does it do?

* Updates the design-system dependencies to use 1.7.0

### Why is it needed?

* Allows nested simple menus
* Refactored combobox & select

### How to test it?

* automated testing 🪄

2023-04-27 15:30 UTC, gu-stav requested changes

2023-05-02 09:07 UTC, gu-stav commented
@joshuaellis could you fix the tests and resolve the merge conflicts before I review again please?

2023-05-02 09:24 UTC, joshuaellis commented
> @joshuaellis could you fix the tests and resolve the merge conflicts before I review again please?

thanks for the reminder, i hadn't noticed. This should pass now 🤞🏼

2023-05-02 09:26 UTC, gu-stav commented on packages/core/admin/admin/src/pages/MarketplacePage/components/SortSelect/index.js
> +        label="Sort by"
Needs to be translated.

2023-05-02 11:12 UTC, gu-stav approved these changes

2023-05-02 11:18 UTC, merged