Fix/overlapping date type
strapi/strapi pull request #17030
Opened 2023-06-20 09:35 UTC by LuizPelegrini

### What does it do?

Enforces Typing System v1 to use Typescript Date in date fields.

### Why is it needed?

`DateValue` type was erroneously using `Attribute.OfType<'date'>` instead of Typescript Date. This causes `GetValues<'...'>` to infer dates as `Attribute.OfType<'date'>` preventing to perform Date operations on those date fields.

### How to test it?
- Create a ContentType or Component that includes a date field (type date)
- Generate the types using `strapi ts:generate` command.
- Use `GetValues` helper  from `@strapi/strapi` package to type a variable
```ts
const myComponent: GetValues<'category.component-name'> = {
  myDateField: new Date() // no complains from TS ✅ 
}

myComponent.myDateField.getUTCMinutes(); // Date API available ✅ 
```

2023-06-20 09:35 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=17030) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=17030) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=17030) it.</sub>

2023-06-20 15:57 UTC, Convly requested changes
Hi, thanks a lot for your vigilance, I've only one comment

2023-06-20 15:59 UTC, Convly commented on packages/core/strapi/lib/types/core/attributes/date.d.ts
> +export type DateValue = globalThis.Date;
The only caveat with a string though, is that you can actually have a Date for input (create/update) and it'll be converted to `string` upon reaching the DB (and then going out).

So maybe a better solution would be to have `globalThis.Date | string`?

2023-06-21 03:31 UTC, LuizPelegrini commented on packages/core/strapi/lib/types/core/attributes/date.d.ts
> +export type DateValue = globalThis.Date;
Indeed, thanks for pointing that out @Convly I pushed the change 🚀

2023-06-21 07:31 UTC, Convly approved these changes
LGTM

> Use GetValues helper from @strapi/strapi package to type a variable

I'll need to document the usage though. I wanted to wait a bit before documenting that and keep this utility internal for the moment (as I might want to change it a bit before considering stable).

Anyway, thanks for taking the time to prepare a fix for this.

2023-06-21 09:48 UTC, christiancp100 approved these changes

2023-06-21 12:50 UTC, merged

2023-06-21 12:51 UTC, Convly commented
@LuizPelegrini FYI this change will be released next Wednesday in the 4.11.3 version

2023-06-22 03:31 UTC, LuizPelegrini commented
no problem @Convly thanks for the heads-up and thanks a bunch on improving Strapi typing system! 🚀