Chore: Upgrade prettier to 3.0.0
strapi/strapi pull request #17377
Opened 2023-07-19 13:51 UTC by gu-stav

### What does it do?

Upgrades prettier to `3.0.0` and re-formats the repo.

### Why is it needed?

Right now is a good moment to do that, because all big features have been merged. Prettier@3 is much smaller due to the CJS drop and will therefore improve CI installation times.

2023-07-19 14:52 UTC, joshuaellis approved these changes

2023-07-19 14:55 UTC, alexandrebodin requested changes
Not sure why but the tests are very unhappy :/

2023-07-19 14:56 UTC, gu-stav commented
@alexandrebodin It looks like as if we are importing prettier at some point somewhere in a package. I'll investigate a bit tomorrow, because this IMO shouldn't happen.

2023-07-20 14:13 UTC, closed without merging

2023-07-20 16:35 UTC, alexandrebodin commented
> @alexandrebodin I've gotten to the bottom of this: the TS generator utils are importing prettier for a util called `format`, which I guess is used to format the generated code. Since this module is written in CJS this upgrade won't work until we've migrated.
> 
> https://github.com/strapi/strapi/blob/37d0f58de2ca81922539141edb2eaab810760fc0/packages/utils/typescript/lib/generators/utils.js#L60-L74

ho that's unfortunate. Thanks for the info 👍