[Helper-Plugin] Migrate useFieldHint to TS
strapi/strapi pull request #17780
Opened 2023-08-24 13:52 UTC by Feranchz

### What does it do?

Part of #17690 to migrate helper plugin to Typescript

### Related issue(s)/PR(s)

Relates to #17690

2023-08-25 07:06 UTC, joshuaellis requested changes
Some thoughts 🤔

2023-08-25 07:06 UTC, joshuaellis commented on packages/core/helper-plugin/src/hooks/tests/useFieldHint.test.tsx
> +export const IntlWrapper = ({ children }: { children: React.JSX.Element }) => (
```suggestion
const IntlWrapper = ({ children }: { children: React.ReactNode }) => (
```

I think this is the preferred definition for children, what makes you think it should be this? :) 

also does it need to be exported?

2023-08-25 07:06 UTC, joshuaellis commented on packages/core/helper-plugin/src/hooks/tests/useFieldHint.test.tsx
> +function setup(args: UseFieldHintProps): any {
Can you demystify the below setup? I don't think it needs to be wrapped in promise and act, this seems like either an issue in our tests or the hook 🤔

2023-08-25 07:06 UTC, joshuaellis commented on packages/core/helper-plugin/src/hooks/useFieldHint.tsx
> +  type?: string;
This is an interesting one, I suppose this should be something `Attribute.Kind` which is imported from `@strapi/strapi`?

2023-08-28 09:37 UTC, madhurisandbhor approved these changes
LGTM, please remove unnecessary await from tests.

2023-08-29 07:58 UTC, joshuaellis commented on packages/core/helper-plugin/src/hooks/tests/useFieldHint.test.tsx
> +  return renderHook(() => useFieldHint(args), { wrapper: IntlWrapper });
i'd inline the wrapper, avoids erroneous typing 👍🏼

2023-08-30 09:11 UTC, madhurisandbhor approved these changes

2023-08-30 12:59 UTC, merged