Add Utils.Expression Tests
strapi/strapi pull request #17905
Opened 2023-09-01 17:24 UTC by christiancp100

### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2023-09-04 09:07 UTC, Convly requested changes

2023-09-04 09:07 UTC, Convly commented on packages/core/strapi/lib/types/__tests__/definitions/utils/guard.d.ts
> +import { Utils } from '@strapi/strapi';
```suggestion
import type { Utils } from '@strapi/strapi';
```

2023-09-04 09:07 UTC, Convly commented on packages/core/strapi/lib/types/__tests__/test.utils.js
> +    ignoreProjectOptions: true,
Let's add a TODO since we'll need to remove those options when strapi/strapi will be converted to TS

2023-09-04 09:07 UTC, Convly commented on packages/core/strapi/lib/types/__tests__/definitions/utils/expression.d.ts
> +
Could we add a test for StrictEqual<'hello', string> or StrictEqual<1, number> to see if it ignores extendable types?

2023-09-08 08:44 UTC, Convly approved these changes

2023-09-19 14:27 UTC, innerdvations submitted a review, later dismissed
LGTM!

2023-09-21 14:14 UTC, innerdvations approved these changes
(still) LGTM!

2023-09-21 15:57 UTC, merged