migrate normalizeAPIError to TS
strapi/strapi pull request #17915
Opened 2023-09-04 08:48 UTC by Feranchz

Relates to https://github.com/strapi/strapi/issues/17690

2023-09-05 07:32 UTC, markkaylor approved these changes
LGTM

2023-09-05 12:24 UTC, joshuaellis requested changes
After some research the API error we're passing is one of the errors in `@strapi/utils`, they're classes but right now we can't access them. We can either delay this PR and probably #17922 until we've sorted `@strapi/utils` out (a couple of days max i imagine) or we can do a `namespace` to force the types. 

What do you think @markkaylor & @Feranchz?

2023-09-05 12:33 UTC, joshuaellis commented
I can add the namespace work to this PR @markkaylor if you want?

2023-09-06 08:06 UTC, joshuaellis commented on packages/core/utils/src/index.ts
> +namespace utils {
yep, don't worry i'm still looking at it 😄

2023-09-06 09:55 UTC, joshuaellis commented on packages/core/helper-plugin/declarations/@strapi/utils.d.ts
Right, this is my workaround at the moment. I tried to do what @alexandrebodin is doing on his `@strapi/strapi` branch at the moment but with classes it through the issue of two `utils` being defined at the same time. I tried _numerous_ times to get the `custom.d.ts` to work as well but again, it couldn't patch over the broken types so after a lot of trial and error and googling, this came up as the best solution for now...

This is something we're gonna have to do with `@strapi/permission` too and then implement the same way in other packages until those offending packages are bundled correctly, what does everyone else think – @markkaylor @Feranchz @gu-stav?

2023-09-06 15:43 UTC, joshuaellis approved these changes

2023-09-07 07:49 UTC, merged