migrate DateTimePicker to TS
strapi/strapi pull request #17923
Opened 2023-09-04 11:57 UTC by Feranchz

Relates to https://github.com/strapi/strapi/issues/17690

2023-09-04 12:15 UTC, joshuaellis commented on packages/core/helper-plugin/src/components/DateTimePicker.tsx
>      if (process.env.NODE_ENV === 'development') {
While we're here, can we change this code block so we're just doing the `once` method please? We should not need to use an effect nor check if the ENV is dev :)

2023-09-05 07:36 UTC, markkaylor approved these changes
lgtm

2023-09-05 07:37 UTC, joshuaellis requested changes
You need to declare the `once` function outside of react for it to work effectively :) You'll also most likely need to lint those changes fyi

2023-09-05 07:37 UTC, joshuaellis commented on packages/core/helper-plugin/src/components/DateTimePicker.tsx
> +import { once } from '../utils/once';
```suggestion
import { once } from '../utils/once';

const warnOnce = once(console.warn)
```

2023-09-05 07:37 UTC, joshuaellis commented on packages/core/helper-plugin/src/components/DateTimePicker.tsx
> +  });
```suggestion
  warnOnce(
    `
      Deprecation warning: Usage of "DateTimePicker" component from the helper-plugin is deprecated and will be removed in the next major release. Instead, use the DateTimePicker from the Design System: import { DateTimePicker } from '@strapi/design-system';"
    `
  );
```

2023-09-05 12:48 UTC, joshuaellis approved these changes
Nice job 😄

2023-09-05 13:19 UTC, merged