[Helper Plugin] Migrate CheckPermissions and CheckPermissions Page to TS
strapi/strapi pull request #17922
Opened 2023-09-04 11:43 UTC by Feranchz

Relates to https://github.com/strapi/strapi/issues/17690

Handle two migrations in the same PR because they are almost the same file

2023-09-05 07:36 UTC, markkaylor reviewed
The types look fine to me. I'm just wondering why we have to components that are almost identical. Which one should we deprecate?

2023-09-05 07:40 UTC, joshuaellis requested changes

2023-09-05 07:41 UTC, joshuaellis commented
> The types look fine to me. I'm just wondering why we have to components that are almost identical. Which one should we deprecate?

One of them handles redirects and loading states, I think we need to analyse where they're used in the codebase to see which is used when and where and why, otherwise we might be shooting ourselves in the foot 🥲

2023-09-05 08:27 UTC, joshuaellis commented
> @markkaylor @joshuaellis We are not using `CheckPage` on the codebase, so I guess we can safely deprecated it 🤔

You sure? I get 37 results (not all applicable ofc) for `<CheckPagePermissions`,  meanwhile only 11 for `<CheckPermissions`... the real question is do we want to refactor bits of the app to remove the `CheckPermissions` components in favour of `CheckPagePermissions`?

2023-09-07 08:33 UTC, joshuaellis requested changes

2023-09-07 08:33 UTC, joshuaellis commented on packages/core/helper-plugin/src/types.ts
> +}
you should be able to remove this now and import directly from the package :)

2023-09-07 08:37 UTC, joshuaellis approved these changes
![Mr Bean Thumbs Up GIF](https://media1.giphy.com/media/9Ai5dIk8xvBm0/200.gif)

2023-09-07 08:59 UTC, merged