[Blocks editor] Setup toolbar container
strapi/strapi pull request #17940
Opened 2023-09-05 15:44 UTC by remidej

### What does it do?

Sets up the container of the new block editor's toolbar.

Also sets the global stylings for the blocks editor (everything excluding the Editable component which @madhurisandbhor is working on)

It's exported from its own component because it will likely be reused for the popover feature.

### Why is it needed?

It will allow us to start building the different sections in parallel.

2023-09-05 17:16 UTC, joshuaellis requested changes
NGL have you considered just using Radix's toolbar? https://www.radix-ui.com/primitives/docs/components/toolbar

I think you're gonna spend an enormous amount of time implementing the accessibility requirements for an actual toolbar...

2023-09-05 17:16 UTC, joshuaellis commented on packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
> +  return <SectionWrapper gap={1}>{children}</SectionWrapper>;
this should have role group :)

2023-09-05 17:16 UTC, joshuaellis commented on packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
> +export default Toolbar;
named exports are preferred 👍🏼

2023-09-05 17:16 UTC, joshuaellis commented on packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
> +  }
I think for accessibility you're supposed to have an element with role `separator`

2023-09-06 09:17 UTC, remidej commented
Yes, I quite like the DX! asChild is very neat

2023-09-06 09:23 UTC, merged

2023-09-06 09:34 UTC, joshuaellis commented
> Yes, I quite like the DX! asChild is very neat

it's coming to the DS in v2 👀