R[Helper Plugin] migrate ReactSelect to TypeScript
strapi/strapi pull request #17985
Opened 2023-09-08 18:54 UTC by JuliusGudni

### Related PR
#17690

2023-09-08 18:54 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=17985) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=17985) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=17985) it.</sub>

2023-09-08 19:06 UTC, JuliusGudni commented
I noticed that ReactSelect has no storybook file. Shall I take a look at that in this PR or is that stuff for a seperate PR?

2023-09-11 07:15 UTC, joshuaellis commented
> I noticed that ReactSelect has no storybook file. Shall I take a look at that in this PR or is that stuff for a seperate PR?

I'd leave it, we're deprecating using this.

2023-09-11 07:19 UTC, joshuaellis requested changes
See inline comments 👍🏼

2023-09-11 07:19 UTC, joshuaellis commented on packages/core/helper-plugin/src/components/ReactSelect.tsx
> +};
This should be extending the `Props` from `react-select`

2023-09-11 07:19 UTC, joshuaellis commented on packages/core/helper-plugin/src/components/ReactSelect.tsx
> +  theme: StrapiTheme,
This should be `DefaultTheme` from `styled-components`

2023-09-11 07:19 UTC, joshuaellis commented on packages/core/helper-plugin/src/components/ReactSelect.tsx
> +const DropdownIndicator = ({ innerProps, innerRef }: any) => {
How come you've not typed this? :)

2023-09-11 14:44 UTC, joshuaellis requested changes
minor tweaks but pretty much there.

2023-09-11 14:44 UTC, joshuaellis commented on packages/core/helper-plugin/src/components/ReactSelect.tsx
> +};
```suggestion
export interface ReactSelectProps extends RSProps {
  error?: string;
  ariaErrorMessage?: string;
};
```

2023-09-11 14:44 UTC, joshuaellis commented on packages/core/helper-plugin/src/components/ReactSelect.tsx
> +}: RSProps & ReactSelectProps) => {
```suggestion
}: ReactSelectProps) => {
```

2023-09-11 16:49 UTC, joshuaellis approved these changes

2023-09-12 13:21 UTC, merged