fix: content manager action buttons not triggering
strapi/strapi pull request #18182
Opened 2023-09-27 10:47 UTC by amerikan

### What does it do?

Wraps action buttons component in a `<Td>` to handle propagation for us.

### Why is it needed?

To solve bug reported in https://github.com/strapi/strapi/issues/17880

### How to test it?

Attempt to delete or duplicate an entry by clicking the corresponding action buttons.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/17880

2023-10-02 08:45 UTC, joshuaellis requested changes
your E2E tests are failing.

2023-10-02 20:53 UTC, amerikan commented
@joshuaellis I ran the 2 commands listed on https://github.com/strapi/strapi/blob/main/CONTRIBUTING.md#contribution-prerequisites and both of them passed for me. Is there other scripts that I should be running?

2023-10-05 00:46 UTC, amerikan commented
@joshuaellis can you re-run tests if needed. I dropped some commits.

2023-10-17 07:19 UTC, joshuaellis approved these changes

2023-10-17 07:38 UTC, merged