fix: language-change-issue
strapi/strapi pull request #18270
Opened 2023-10-03 22:50 UTC by kunalvirk

### What does it do?
Fix #18156

Describe the technical changes you did.
Removed the `usePersistentState` and made `lang` local to AssetPreview component.

### Why is it needed?

The media editor dialog was changing the `strapi-admin-language` to `en` which was overriding the locale chosen by the user.

### How to test it?

1. Change the language to anything other than english in `Profile` page and save
2. Then navigate to 'Media Library', select a preuploaded media and click `Edit asset`. Hit refresh, it should not change the language back to english

Thanks,

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2023-10-03 22:50 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=18270) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=18270) before we can accept your contribution.<br/><hr/>**Kunal Virk** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=18270) it.</sub>

2023-10-05 13:09 UTC, Boegie19 approved these changes
@joshuaellis checked the PR fixes the issues only thing what I am not sure about is that is changes the srcLang of the track to be always English. so I am not sure if that could cause a problem.

2024-03-26 18:05 UTC, innerdvations commented
Thanks for your PR! Could you please target the `develop` branch instead of `main`?

2024-03-27 08:12 UTC, joshuaellis requested changes

2024-03-27 08:12 UTC, joshuaellis commented on packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/AssetPreview.js
> +  const lang = 'en';
I actually think we can just get rid of this and the prop `srcLang` it's not really needed and iirc you need to know the language of the video, which might not be `en`.

2024-09-18 19:20 UTC, alexandrebodin commented
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR targets version 4, it has been automatically closed. However, we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

2024-09-18 19:20 UTC, closed without merging