Auto Orientation issue fixed
strapi/strapi pull request #18377
Opened 2023-10-10 11:26 UTC by PrathameshGujar08

### What does it do?

The issue as being said **Auto orientation is not applied on responsive friendly image** was that If one uploads a image the orientation was changed or thumbnail view of the image did not align with the actual image uploaded.
The sharp libarary used to check the Auto Orientation as I found always gave the variable to be false resulting in not executing the conditional statement responsible for orientation of Image. As per my knowledge the rotate function checks the orientation status by itself and rotates the image if needed. No manual checking was needed to orient it. 

### Why is it needed?

It is needed to store the data as it was meant to be without any changes being made to it.

### How to test it?

The setup of the environment is same and to test it the original image which was being used to test can be used again. From my side I used some other images clicked from my phone with different camera orientation and some images were dowloaded from the internet.

### Related issue(s)/PR(s)

This is related to issue marked as

2023-10-10 11:26 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=18377) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=18377) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=18377) it.</sub>

2023-10-10 11:27 UTC, Boegie19 commented
fixes https://github.com/strapi/strapi/issues/18338

2023-10-10 11:33 UTC, Boegie19 requested changes

2023-10-10 11:33 UTC, Boegie19 commented on packages/core/upload/server/services/image-manipulation.js
> -    if (autoOrientation) {
removing autoOrientation flag is not the solution.
Goal was to figure out why autoOrientation is set for A but not for B.
aka it should rotate everything or noting but this flag needs to stay intact.

2023-10-10 12:10 UTC, DKdev117 reviewed
Not right you have changed code and maybe  it is not the right solution

2023-10-12 11:20 UTC, PrathameshGujar08 commented
> @PrathameshGujar08 Not right you have changed code and maybe it is not the right solution
Did you get any lead over it bro? I would like to discuss it over Discord if you are fine with it

2023-10-12 11:41 UTC, PrathameshGujar08 commented
@Boegie19  Can you review it again? The exif data seems to be lost during sharp.resize() as I read online. So I retained the metadata while resizing which now shows the correct behaviour.

2023-10-12 13:29 UTC, Boegie19 commented
@PrathameshGujar08 It works and nice spot. mind making the PR ready to review?

2023-10-12 13:30 UTC, Boegie19 approved these changes
Tested it and solves the issue.

2024-05-07 01:17 UTC, ch-jwoo commented
@Boegie19 
Thank you for your hard work

When are you going to merge this pr?
Is there any remain process?

2024-07-04 06:32 UTC, PrathameshGujar08 commented
> Tested it and solves the issue.

Any update for this?

2024-09-18 19:20 UTC, alexandrebodin commented
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR targets version 4, it has been automatically closed. However, we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

2024-09-18 19:20 UTC, closed without merging