feat(Blocks): Move blocks
strapi/strapi pull request #18690
Opened 2023-11-07 14:42 UTC by madhurisandbhor

### What does it do?

Adds the ability to move the blocks around in editor

### How to test it?

On hover user would be able to see drag option and able to drag simple block items.
For now moving simple blocks is working, moving list items is yet to be completed.

2023-11-08 15:01 UTC, joshuaellis requested changes
I've not tested but just read the code and noted some areas of potential improvement. I think your PR description could be better, you've not just added drag and drop – you've also changed the universal hook `useDragAndDrop` for instance. So you should also add a why section even if one of the items is just "feature improvement" etc.

2023-11-08 15:01 UTC, joshuaellis commented on packages/core/admin/admin/src/content-manager/hooks/useDragAndDrop.js
Can you explain the changes here?

2023-11-08 16:15 UTC, remidej reviewed
there will be lots of conflicts to fix, but it's really cool to see this feature

you'll also need to add tests, probably E2E ones

2023-11-16 07:00 UTC, madhurisandbhor commented on packages/core/admin/admin/src/content-manager/components/BlocksEditor/BlocksInput/index.js
> +      },
Here, I am trying to limit dnd over List block (not list items), even though you mark an item as not draggable, it still becomes droppable(using drop ref) as they are different sources, drag source and drop target.

2023-11-16 07:07 UTC, madhurisandbhor commented
@joshuaellis @remidej Thank you for your valuable feedback 👍 , actually I didn't get time to review PR myself. I asked feedback a bit earlier as I was going to be away for a week. 
Also there are new updates on merging branches and typescript in place in blocks, I will create a new PR soon.

2023-11-17 06:24 UTC, closed without merging