Fix: Catch Error in forgot password function.
strapi/strapi pull request #19021
Opened 2023-12-11 03:22 UTC by baronha

### What does it do?

- Changed error handling in exceptions in the forgot password feature.
```packages/plugins/users-permissions/server/controllers/auth.js```

### Why is it needed?

- In case the Email does not exist or the user is in a blocked state in the DB, the response returned is valid
`return ctx.send({ ok: true });`

### How to test it?

- On my real project

2023-12-11 03:22 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=19021) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=19021) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=19021) it.</sub>

2023-12-11 03:23 UTC, baronha commented
Hey @joshuaellis, can you please take a look?

2023-12-15 11:18 UTC, Convly requested changes
Hi, thanks for taking the time to open a PR.

Sending information about which user exists or is blocked to a public endpoint would be a consequent security risk.

I highly recommend against implementing this.

2023-12-15 11:28 UTC, innerdvations commented
I do appreciate the cleanup here (exceptions + parallelization) but as @Convly said, this is intentional, although admittedly we should add a comment stating the reason.

If this is behaviour you would like in your project, I recommend writing a custom controller that implements it.

2023-12-15 11:29 UTC, closed without merging