chore(sentry): convert to typescript
strapi/strapi pull request #19128
Opened 2023-12-29 18:57 UTC by remidej

### What does it do?

Converts the Sentry plugin codebase to TypeScript

### Why is it needed?

TS all the things

2024-01-02 17:08 UTC, Feranchz approved these changes
Types looks good and I tried use it with a personal sentry account and I received the errors with all the info 👍

2024-01-02 17:10 UTC, remidej commented on packages/plugins/sentry/server/src/middlewares/sentry.ts
> +  const sentryService: ReturnType<typeof createSentryService> = strapi
it was a nice workaround here since strapi.service loses the type info :)

2024-01-03 08:27 UTC, joshuaellis requested changes
Minor feedback, otherwise solid work ✨

2024-01-03 08:27 UTC, joshuaellis commented on packages/plugins/sentry/admin/.eslintrc.js
I'm not sure this is quite correct – because non-ts files won't ever be linted, instead I would do:

```json
{
  "root": true,
  "extends": ["custom/front/typescript"],
}
```

2024-01-03 08:27 UTC, joshuaellis commented on packages/plugins/sentry/server/src/config.ts
> +  } as Config,
i think `satisfies` is better here because you're checking as opposed to enforcing?

2024-01-03 11:23 UTC, joshuaellis approved these changes
Niceeee, lets ensure we squash-merge so we get some clean commits 🧽

2024-01-03 12:51 UTC, merged