18562: Enable Relative Links in Blocks Editor
strapi/strapi pull request #19197
Opened 2024-01-11 08:22 UTC by Ben-Zahler

### What does it do?

Allows authors to create relative links in the blocks editor

### Why is it needed?

Currently, links cannot be saved when entering relative links in the blocks editor.

### How to test it?

- open the new blocks editor
- create a link
- enter any relative link as the link target (e.g. /about-strapi)
expected: the user can save the link and save the block

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/18562

2024-01-11 08:24 UTC, Ben-Zahler commented
@remidej this is a follow up to the PR I raised last week. For me all other cases in https://github.com/strapi/strapi/issues/18562 were working when I tested this on the 4.17 branch.

2024-01-17 09:16 UTC, remidej requested changes
Hey, thanks for following up. I wasn't sure initially, but I think it's a good idea to support relative links indeed.

There's just 1 thing to add. The validations also happen in the backend, so I believe here even though the admin will let you add the link, you won't be able to save the content.

Could you also update the validations in the backend? The idea would be to use a custom yup.string().test to do the same as the frontend, instead of yup.string().url(). It happens [in the blocks-validators file](https://github.com/strapi/strapi/blob/334c95408abdd9ecc0ece0e8c0fd5eb0024ad027/packages/core/strapi/src/services/entity-validator/blocks-validator.ts#L23).

2024-01-17 12:09 UTC, Ben-Zahler commented
@remidej when I tested this on the 4.17 branch, backend validations did not kick in and I was able to save.
As mentioned, I did not investigate on the validation but was happy that it worked :-)

2024-01-23 10:22 UTC, remidej commented on packages/core/strapi/src/services/entity-validator/blocks-validator.ts
> +  console.log(`validating online node of of ${value.type}`);
can you remove this log?

2024-01-23 13:08 UTC, Ben-Zahler commented
@remidej @innerdvations the backend validation should now be implemented as suggested by @remidej .
I hope the linter passes, I don't trust my setup 100%. Do the test have to be triggered manually?

2024-01-29 21:49 UTC, lzhou-aops commented
I would love to see this added as well!

2024-02-02 08:20 UTC, Ben-Zahler commented
hi @remidej , thanks for the Preview deployment, is there anything esle I can do to support this PR?

2024-02-09 09:18 UTC, remidej approved these changes

2024-02-09 09:19 UTC, merged