fix(cm): manage when we're creating entries derivatively in the CM
strapi/strapi pull request #19209
Opened 2024-01-12 09:51 UTC by joshuaellis

### What does it do?

* removes the calls of directly setting state to whether we're creating an entry or not in the CM & instead derives the state value from the URL params

### Why is it needed?

* Primarily to handle singleTypes we were originally check if there's an ID present to see if we're creating an entry, single types dont have IDs so when we've done the call to fetch the data we manually flipped this. In the case of switching locales e.g. i have an EN entry and I need to make a DE entry, we wouldn't change the state from "not creating" to "creating" leaving an infinite loop. Using an effect is probably a bad idea because we can derive from the URL if we're making an entry & because we're never making a single-type (they always exist because they're singletons) we can omit the `useState`.

### How to test it?

*locales*
* Go to an localised content-type.
* Make the default content-type & save
* Switch to a locale you've not made – it should load the create form correctly

*single-types*
* Navigate to your single-type that you've never made before
* Should show you the empty form
* fill in & save
* refresh the page
* you should see the saved data & be able to still update the form

### Related issue(s)/PR(s)

* resolves #19206

2024-01-12 16:27 UTC, jhoward1994 commented
The behaviour you mentioned is fixed for me. I spotted something else in testing, is it related or not?

All locales of a single type seem to share values. e.g. updating the name of the french single type updates all locales

https://github.com/strapi/strapi/assets/48524071/cd52ca6e-1ddd-4de5-97df-02aadde0e95e

2024-01-12 16:51 UTC, joshuaellis commented
> The behaviour you mentioned is fixed for me. I spotted something else in testing, is it related or not?
> 
> All locales of a single type seem to share values. e.g. updating the name of the french single type updates all locales
> 
>  Screen.Recording.2024-01-12.at.16.25.01.mov 
> Sorry I should've zoomed in, hopefully it's clear?

either way it needs fixing.

2024-01-15 09:30 UTC, jhoward1994 requested changes
See comment above

2024-01-15 09:56 UTC, Marc-Roig commented
I have validated the steps you provided and everything seems to work. I could not replicate Jamie's error though.

I saw a couple of other details that I might mention but I do think they are not related to this PR. will prepare a video

2024-01-15 10:58 UTC, Marc-Roig commented
Sooo, here it is. Probably all of this have nothing to do with this PR, but just in case :) 

- The locale that is selected, is not displayed with a "green" dot in the locale dropwdown to represent it exists (don't know if it's intended) 
![image](https://github.com/strapi/strapi/assets/20578351/3f64e9b4-9bd7-4361-9d2e-2b0f326ed44f)


- I am seeing the review workflow fields even if RW is not enabled for that content type
https://github.com/strapi/strapi/assets/20578351/74fc47d7-8f70-4693-b867-18be8f29e0b0

Does this happen to you too? I wonder if this is a front or backend issue.

2024-01-15 13:23 UTC, joshuaellis commented
These are probably FE issues, but they shouldn't be too hard to fix... I will open new PRs aimed at develop for them to keep this hotfix isolated. @jhoward1994 I did reproduce your error – are you able to test again please 🙏🏼

2024-01-15 15:23 UTC, jhoward1994 approved these changes
👍🏻👍🏻👍🏻

2024-01-15 15:51 UTC, merged