Add first CLI Tests for data transfer
strapi/strapi pull request #19242
Opened 2024-01-17 11:46 UTC by christiancp100

### What does it do?
It adds the first CLI tests for Data Transfer.

### Why is it needed?

To test data transfer CLi.

### How to test it?

Execute `yarn test:cli` at the root level of the process.

2024-01-18 10:04 UTC, Convly reviewed
On my side, trying to run the test fails [with the following errors](https://github.com/strapi/strapi/assets/25851739/ee7e3159-dc5c-47b0-a14a-48e4d4e0d810)

2024-01-18 11:27 UTC, christiancp100 commented
> Member

Yeah that's what I commented in the Slack team channel, It's the same error we have when running the Api tests locally. In order to make them work locally you have to create a `yarn.lock` file and do `yarn install` inside the test-app-0. I couldn't find out why that's happening, but in the CI it seems to work for the API Tests

2024-01-25 10:12 UTC, innerdvations requested changes
LGTM! The only thing we need is a detailed comment about why we have to use 'npm' here instead of 'yarn' so that we don't have to rip our hair out in the future, and I'll click 'approve' :laughing:

2024-01-25 13:43 UTC, Convly requested changes
Seems like the tests are failing but are not reported as such by the task

![image](https://github.com/strapi/strapi/assets/25851739/e26136a7-858d-48b2-9ce2-290cbb1bb254)

2024-01-25 16:54 UTC, christiancp100 commented
> LGTM! The only thing we need is a detailed comment about why we have to use 'npm' here instead of 'yarn' so that we don't have to rip our hair out in the future, and I'll click 'approve' 😆

What would you say is the most suitable place to put this?

2024-02-09 08:22 UTC, innerdvations reviewed
Awesome! Just a few text comments

2024-02-09 08:22 UTC, innerdvations commented on cli-tests/tests/strapi/data-transfer/export.test.cli.js
> +  it('should export the data', async () => {
```suggestion
  it('should export data without error', async () => {
```

2024-02-09 08:22 UTC, innerdvations commented on cli-tests/tests/strapi/data-transfer/import.test.cli.js
> +  it('should import the data', async () => {
```suggestion
  it('should prompt for confirmation before importing data', async () => {
```

2024-02-09 08:22 UTC, innerdvations commented on cli-tests/tests/strapi/data-transfer/import.test.cli.js
> +  it('should import the data without asking for confirmation', async () => {
```suggestion
  it('should import data without asking for confirmation with --force', async () => {
```

2024-02-09 08:22 UTC, innerdvations commented on cli-tests/tests/strapi/version/version.test.cli.js
> +  it('should output version', async () => {
```suggestion
  it('should output version with argument', async () => {
```

2024-02-09 08:22 UTC, innerdvations commented on test/scripts/run-cli-tests.js
> +                    '--runInBand',
```suggestion
                    '--runInBand', // tests must not run concurrently
```

2024-02-09 09:43 UTC, Convly approved these changes

2024-02-09 09:44 UTC, merged