fix(admin): adjust onClick of create webhook button in empty state
strapi/strapi pull request #19258
Opened 2024-01-17 21:47 UTC by Tonours

### What does it do?

Adjust onClick props of "create new webhook" button of Settings -> Webhook page to make it works with `goTo` helper.

### Why is it needed?

It's needed because otherwise the button doesn't redirect the user to the webhook creation page.

### How to test it?

1. Navigate to "Settings" -> "Webhook"
2. Ensure to have no webhooks in your database
3. Click on "create new webhook" button diplayed in the content area of the page
4. Notice that you are now redirected to the creation page of a webhook

### Related issue(s)/PR(s)

Related to this issue #19257

2024-01-17 21:47 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=19258) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=19258) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=19258) it.</sub>

2024-02-16 16:43 UTC, simotae14 commented on packages/core/admin/admin/src/pages/Settings/pages/Webhooks/ListPage.tsx
> +                  onClick={canCreate ? goTo('create') : undefined}
```suggestion
                  onClick={canCreate && goTo('create')}
```

2024-02-16 16:43 UTC, simotae14 requested changes
It works ✨  Please try my suggestion, thanks

2024-02-26 09:14 UTC, joshuaellis requested changes

2024-02-26 09:14 UTC, joshuaellis commented on packages/core/admin/admin/src/pages/Settings/pages/Webhooks/ListPage.tsx
> +                  onClick={canCreate && goTo('create')}
we should just disabled the button if the user cannot create?

2024-03-28 10:19 UTC, joshuaellis commented
Closing this PR due to inactivity.

2024-03-28 10:19 UTC, closed without merging