Hide Locale column and grouping option when i18n plugin is not installed
strapi/strapi pull request #19358
Opened 2024-01-29 11:26 UTC by simotae14

### What does it do?

It checks if the i18n plugin is installed, if not we need to hide the Locale column in the Release Details page and also the Grouping locale option.

### Why is it needed?

We want to replicate a similar behavior as in the CM. In the Release Details we can have entries from multiple collections so it is not possible to hide the column when a Collection is not using the i18n plugin (and also the entries can be grouped by Locale or actions).

### How to test it?

Check a Release Details page with the i18n plugin installed and then remove it with
```
yarn remove @strapi/plugin-i18n 
```
and re run the application, the locale option in the Grouping dropdown and the locale column need to be removed

### Related issue(s)/PR(s)

CS-549

2024-01-29 11:35 UTC, joshuaellis requested changes
I'm not sure about this @simotae14 this goes against how plugins work interacting with core plugins. IMO we should be injecting this from the i18n plugin.

What was the reasoning for doing it this way round?

2024-04-05 09:06 UTC, joshuaellis commented on packages/core/admin/admin/src/StrapiApp.tsx
Would it make more sense to add `createHook` to the bootstrap function of plugins, have the releases plugin "create" it's hook so again, it's locked to the plugin?

2024-04-05 09:08 UTC, joshuaellis reviewed
I think this is highlighting the need for a generic table API that can apply across the whole application 🤔 not suggesting you do this now of course, but long term – what do you think?

2024-04-05 09:30 UTC, simotae14 commented
Yes, I agree, there are different places where we can inject or remove columns based on conditions

2024-04-05 10:50 UTC, joshuaellis approved these changes
Not tested, but code changes 🌟

2024-04-08 15:35 UTC, remidej commented
I'm not able to test it, after uninstalling i18n I get this error:

```sh
TypeError: Cannot read properties of undefined (reading 'service')
at disableContentTypeLocalized (strapi/packages/core/content-releases/server/src/migrations/index.ts:197:51)
```

2024-04-08 16:06 UTC, remidej approved these changes
the problem is in the backend, but I can confirm the frontend part works as expected

2024-04-08 19:43 UTC, merged