Remove add another field button if it's dynamic zone fromm CTB
strapi/strapi pull request #19639
Opened 2024-02-29 14:29 UTC by Bassel17

### What does it do?

Adds another check in the List component to not show "add another field" button incase the list was a dynamic zone list

### Why is it needed?

- Currently it's showing a button that shouldn't be there (Add another field button)
- When clicking the button an error occurs for the users

### How to test it?

How it currently is:
<img width="1151" alt="image" src="https://github.com/strapi/strapi/assets/37274596/bc112dc5-412f-448d-ab6b-2105e5e5ded4">

How it should look like:
<img width="1151" alt="image" src="https://github.com/strapi/strapi/assets/37274596/0f6603f0-dba6-4ec7-b03f-e7148fa0856f">

How a component list should stay:
<img width="1956" alt="image" src="https://github.com/strapi/strapi/assets/37274596/d785f622-53fc-4176-bd9e-6c6e40d6f69a">

2024-03-04 09:12 UTC, christiancp100 approved these changes
Code LGTM

2024-03-04 14:16 UTC, joshuaellis requested changes

2024-03-04 14:16 UTC, joshuaellis commented on e2e/tests/content-type-builder/ctb.spec.ts
can you name this better as to what you're actually testing please?

2024-03-04 14:16 UTC, joshuaellis commented on e2e/tests/content-type-builder/ctb.spec.ts
> +    ).toBeVisible();
Can you look at the other e2e tests and see how most people have written comments to explain what's ging on?

it's not quite clear at the moment which might make it harder to maintain in the long run :)

2024-03-04 14:16 UTC, joshuaellis commented on e2e/tests/content-type-builder/ctb.spec.ts
`editview` might be clearer?

2024-03-04 14:55 UTC, joshuaellis approved these changes
Great work!! ⭐

2024-03-05 09:10 UTC, innerdvations approved these changes

2024-03-05 09:10 UTC, innerdvations commented on e2e/tests/content-type-builder/ctb-edit-view.spec.ts
> +    await expect(
Glad you got the tests working! Could we add one that checks the button isn't visible on dzs?

I think you can use something like `expect(locator).toHaveCount(0)` on it, and to find it you can look for the button within the same row as "dynamic zone" so maybe something like `await expect(page.getByRole('row', { name: 'Dynamic Zone' }).getByRole('button', {name: 'Add a component'}).toHaveCount(0)`

2024-03-07 11:19 UTC, merged