Feature/sizeofimage
strapi/strapi pull request #20022
Opened 2024-04-04 00:43 UTC by dplumptre

### What does it do?

Describe the technical changes you did.
I changed the height and width of the svg to be ore visible 

### Why is it needed?

Describe the issue you are solving.
I anticipate that the SVG icon representing the file upload functionality within the application should be more prominent in size, which  would contribute to a more intuitive and user-friendly experience, as it ensures that users can readily discern and utilize this essential functionality without ambiguity or uncertainty.

### How to test it?

Provide information about the environment and the path to verify the behaviour.
Go to Strapi Dasboard --> Media Library
Click on "Add new assets"
See the image svg icon above "Drag & Drop here or" is tiny
Inspect the code for the svg

### Related issue(s)/PR(s)
Image SVG Icon too small when adding new assets to Media Library #16244

Let us know if this is related to any issue/pull request

2024-04-04 00:43 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=20022) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=20022) before we can accept your contribution.<br/>**4** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: markkaylor<br/>:white_check_mark: Marc-Roig<br/>:white_check_mark: alexandrebodin<br/>:white_check_mark: Convly<br/>:x: Ademola plumptre<br/><hr/>**Ademola plumptre** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=20022) it.</sub>

2024-09-18 19:28 UTC, alexandrebodin commented
> [!IMPORTANT] 
> With the release of Strapi 5, we have lifted the code freeze. To ensure we can effectively review and assist with contributions, we are now only accepting PRs targeting version 5 (the develop branch).<br/> 
> As your PR is targeting some of the most recent v4 version, We we would greatly appreciate it if you could update your contribution to align with version 5 and resubmit!

2025-01-31 16:07 UTC, simotae14 commented
hello @dplumptre thanks for your contribution and sorry for the late response. I asked the opinion of a designer in our team, in the meantime if you want to fix the unit test step failing you need to update the snapshot, thanks

2025-01-31 16:20 UTC, simotae14 requested changes
please read my comments and modify a little bit your PR, thanks

2025-01-31 16:20 UTC, simotae14 commented on packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/FromComputerForm.jsx
> +                  <PicturePlus width={50} height={50} aria-hidden />
please use 32x32 because 50 is too much, thanks

2025-07-21 14:46 UTC, closed without merging