chore: integrate beta.5 of the design-system
strapi/strapi pull request #20431
Opened 2024-06-04 16:51 UTC by joshuaellis

### What does it do?

* integrates beta.5 of the DS

### Related issue(s)/PR(s)

* resolves DX-1418

2024-06-05 10:04 UTC, jhoward1994 commented
The code looks good. Nice new animations!

I've noticed these UI things running this and v5/main side by side 

Icon color at http://localhost:1337/admin/settings/documentation
<img width="154" alt="image" src="https://github.com/strapi/strapi/assets/48524071/cb92f355-857c-4558-b2bf-27e69e7ea4ce">

CTB add field footer - e.g. http://localhost:1337/admin/plugins/content-type-builder/content-types/api::temp.temp
<img width="842" alt="image" src="https://github.com/strapi/strapi/assets/48524071/3bc113f3-0870-4cd8-aa51-d0006315f082">

CTB Model creation modals - This seems to be related to tab navigation within the modals?

https://github.com/strapi/strapi/assets/48524071/a3708c3b-3076-4f84-b27e-dada020ddf25

2024-06-06 07:36 UTC, simotae14 commented on packages/core/upload/admin/src/pages/App/components/Filters.jsx
> +import React from 'react';
```suggestion
import * as React from 'react';
```
just to respect our standard

2024-06-06 07:39 UTC, simotae14 commented on packages/core/upload/admin/src/pages/App/components/BulkDeleteButton.jsx
> +import React from 'react';
```suggestion
import * as React from 'react';
```

2024-06-06 07:40 UTC, simotae14 commented on packages/core/upload/admin/src/pages/App/MediaLibrary/tests/MediaLibrary.test.jsx
> +      it.skip('should render the table headers', () => {
Why are you skipping this test?

2024-06-06 08:28 UTC, simotae14 commented on packages/core/admin/admin/src/pages/Settings/pages/Roles/components/ConditionsButton.tsx
> +const ConditionsButtonImpl = forwardRef<HTMLButtonElement, ConditionsButtonProps>(
```suggestion
const ConditionsButtonImpl = React.forwardRef<HTMLButtonElement, ConditionsButtonProps>(
```

2024-06-06 12:27 UTC, simotae14 commented on packages/core/content-type-builder/admin/src/components/FormModal/FormModal.tsx
> +  const [activeTab, setActiveTab] = useState('base');
```suggestion
  const [activeTab, setActiveTab] = React.useState('base');
```

2024-06-06 13:22 UTC, simotae14 commented on packages/core/upload/admin/src/components/AssetDialog/BrowseStep/Filters.jsx
> +import React from 'react';
```suggestion
import * as React from 'react';
```

2024-06-06 13:24 UTC, simotae14 commented on packages/core/upload/admin/src/components/AssetDialog/DialogFooter.jsx
>  import React from 'react';
```suggestion
import * as React from 'react';
```

2024-06-06 13:28 UTC, simotae14 commented on packages/core/upload/admin/src/components/EditAssetDialog/DialogHeader.jsx
>  import React from 'react';
```suggestion
import * as React from 'react';
```

2024-06-06 15:30 UTC, simotae14 commented on packages/core/upload/admin/src/pages/App/MediaLibrary/components/BulkDeleteButton.jsx
> +import React from 'react';
```suggestion
import * as React from 'react';
```

2024-06-07 14:23 UTC, simotae14 requested changes
I found some stuff to check, I don t know if they are issues that we had already in v5 or these issues are introduced in this version (because I compared v4 and v5). For sure are stuff that we need to fix, thanks for the great effort you made in this PR

2024-06-07 14:23 UTC, simotae14 commented on packages/core/admin/admin/src/pages/Marketplace/MarketplacePage.tsx
another difference between marketplace page in v4 
<img width="1512" alt="Schermata 2024-06-07 alle 16 16 39" src="https://github.com/strapi/strapi/assets/2589748/ca869e39-6c5a-41df-8dd5-2853faa2f459">
and the one in this PR
<img width="1433" alt="Schermata 2024-06-07 alle 16 16 25" src="https://github.com/strapi/strapi/assets/2589748/3109922c-8af9-41c7-ad4e-ee47e072a6ba">

2024-06-07 14:34 UTC, joshuaellis commented on packages/core/admin/admin/src/components/Form.tsx
This will be solved in the next DS release.

2024-06-07 15:02 UTC, joshuaellis commented on packages/core/admin/admin/src/components/ConfirmDialog.tsx
Thanks, the message was never defined for that modal & was using the old default which has changed for v5 – you could make an issue for that? I've changed the other bits, the bin icon has been removed because you're not always deleting something with a confirm dialog.

2024-06-07 15:03 UTC, joshuaellis commented on packages/plugins/cloud/admin/src/components/Github.tsx
> +  &:hover {
yeah i don't like it either. Unfortunately, this button is weird and goes against the design-system so sadly have to do it this way 🙃

2024-06-10 09:30 UTC, jhoward1994 commented
Hey I found a few more things with a v5/main -> this PR comparison

- Input padding Examples:
- u&p
<img width="263" alt="Screenshot 2024-06-10 at 10 07 59" src="https://github.com/strapi/strapi/assets/48524071/1b478264-b036-4903-bf5c-18e6bda523d3">
- Upload 
<img width="351" alt="Screenshot 2024-06-10 at 10 21 05" src="https://github.com/strapi/strapi/assets/48524071/698c917e-9dd3-4f7a-8ad3-924e4844d702">

- Label colour of back button (example from user and permissions again)
- On v5 main the arrow is blue
<img width="93" alt="Screenshot 2024-06-10 at 10 08 45" src="https://github.com/strapi/strapi/assets/48524071/24d8898e-59a9-46d7-a357-a0d4e8d8e284">

- Checkbox styling - Users and permissions role edit page
<img width="552" alt="Screenshot 2024-06-10 at 10 09 03" src="https://github.com/strapi/strapi/assets/48524071/157d5578-fa08-4f8f-8bcb-b8c685d110fc">

- i18n - Unable to click outside of the modal to close it
<img width="1511" alt="Screenshot 2024-06-10 at 10 16 22" src="https://github.com/strapi/strapi/assets/48524071/007cd692-9add-43a8-8ed7-fad299a98320">

- Upload - Folder icon style in list view
<img width="1344" alt="Screenshot 2024-06-10 at 10 21 28" src="https://github.com/strapi/strapi/assets/48524071/c4253dce-1c55-4834-8099-32387d6cc078">

- Releases - Tab navigation - URL query param does not change
<img width="419" alt="Screenshot 2024-06-10 at 10 23 34" src="https://github.com/strapi/strapi/assets/48524071/780fb6c1-f6d0-4c92-ab66-57b30b39012f">

2024-06-10 09:37 UTC, joshuaellis commented
> Input padding Examples:

known issue fixed in the next DS release

> i18n - Unable to click outside of the modal to close it

That's actually an accessibility standard of an `alertdialog` because the user is required to do an explicit action.

I'll check the rest out.

2024-06-10 13:38 UTC, jhoward1994 approved these changes

2024-06-10 13:50 UTC, merged

2024-06-10 13:50 UTC, simotae14 commented on packages/core/admin/admin/src/components/ConfirmDialog.tsx
https://github.com/strapi/strapi/issues/20482