feat(create-strapi-app): remove the cloud project creation part
strapi/strapi pull request #20561
Opened 2024-06-19 14:49 UTC by nathan-pichon

### What does it do?

Removing the cloud project creation part on create-strapi-app.

### Why is it needed?

As we experienced some issues with the actual flow, we decided to remove that part.

Issues:
- Delays the strapi project creation by ~10s
- Active the free trial when the project is generated
- If the user remove his project and creates another, he cannot re-use the Cloud CLI to create a project as he as already used his free trial.

### How to test it?

 The create-strapi-app command should not create a project on Cloud anymore.
The project should be created on Cloud during the first `strapi deploy` command (this is already handled in the deploy command).

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2024-06-25 08:06 UTC, Jimimimi requested changes
Some small recommendations

2024-06-25 08:06 UTC, Jimimimi commented on packages/cli/create-strapi-app/src/cloud.ts
> +              : 'We are sorry, but we are not able to login you to Strapi Cloud.';
```suggestion
              : 'We are sorry, but we are not able to log you into Strapi Cloud at the moment.';
```

2024-06-25 08:06 UTC, Jimimimi commented on packages/cli/create-strapi-app/src/cloud.ts
> +export async function handleCloudProject(): Promise<void> {
```suggestion
export async function handleCloudLogin(): Promise<void> {
```
Probably better to rename the function to something more representative

2024-06-25 08:06 UTC, Jimimimi commented on packages/cli/create-strapi-app/src/create-strapi-app.ts
> +    await handleCloudProject();
```suggestion
    await handleCloudLogin();
```

Probably better to rename the function to something more representative

2024-06-25 08:13 UTC, Jimimimi approved these changes
![](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZmd6eDc2YXd4bnZubWt5dGl2ZGxzcnlydmU5MDVvZDJ0YXBpcGdkZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/YKdm91XONLTaw/giphy.webp)

2024-06-26 08:52 UTC, abdallahmz approved these changes
Tested locally, looks all good!

2024-06-26 09:01 UTC, merged