Fix(content-manager): Clicking a filter deletes the filter instead of allowing you to edit it.
strapi/strapi pull request #20997
Opened 2024-08-12 12:55 UTC by moeez506

### What does it do?

Filter edit functionality added. Clicking a filter other than the "x" will allow you to edit that filter.

### Why is it needed?

Clicking a filter anywhere deletes it rather than allowing you to edit it

### How to test it?

Navigate to content manager and add any filter then click on it, will allow you to edit.

### Related issue(s)/PR(s)
#20967 

### Need Assitance. 
 I have solved 90% issue but the design part is ambigous, right now the edit modal is stick to the top right corner which should be exactly below the filter being edited. Needed some guidance regarding that. 
 Attached recording for refrence 
 https://www.loom.com/share/07f37672aaeb4860b3eefe14c53cdf03?sid=40084628-af47-4d91-a237-0c201da496f5
 
 PS: New to strapi codebase, it's my first contribution here.

2024-08-12 12:55 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=20997) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=20997) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=20997) it.</sub>

2024-09-23 13:39 UTC, simotae14 requested changes
Hello @moeez506, thanks a lot for your contribution,
please take a look at my comments and before submitting your code check locally if it passed all the necessary steps (run prettier command, unit and e2e tests, build the package you changed), thanks in advance

2024-09-23 13:39 UTC, simotae14 commented on packages/core/helper-plugin/src/components/FilterListURLQuery.tsx
> +        <span onClick={handleContentClick}>{content}</span>
please, span is a text, its behaviour is not to have an onClick, if you want to handle the onClick in different way you can add a condition in the handleClick handler, there is not need of two handlers for the same thing, you can differentiate the behaviour base on the event target element that triggered the handleClick for example

2024-09-23 13:39 UTC, simotae14 commented on packages/core/helper-plugin/src/components/FilterListURLQuery.tsx
> +      )}
to change the position of this dropdown you need to assign the buttonRef to a button but in your case you are passing it just to the FilterPopoverURLQuery component
Please take a look how the FilterPopoverURLQuery is used in other places for example in this file packages/core/admin/admin/src/pages/Settings/components/Filters.tsx

2024-12-17 10:46 UTC, closed without merging

2024-12-17 10:46 UTC, alexandrebodin commented
HI @moeez506 we will be closing this PR as staled but if you eventually have time to work on it if we haven't done it in the future feel free to ping us to reopen 🙏  

Thank you for contributing!