fix: yarn 4 support
strapi/strapi pull request #21329
Opened 2024-09-18 16:12 UTC by innerdvations

### What does it do?

when using create-strapi-app with yarn 4, use env YARN_NETWORK_TIMEOUT instead of `--network-timeout` command line option

### Why is it needed?

yarn 4 has removed --network-timeout as a cli option and it was failing with an error when it tried to run `yarn install --network-timeout 1000000`

### How to test it?

create-strapi-app should work with yarn 4 as well as previous versions of yarn, and still work with `pnpm` and `npm`

### Related issue(s)/PR(s)

DX-1611
https://github.com/strapi/strapi/pull/21271

2024-09-23 13:13 UTC, alexandrebodin approved these changes
I won't have time to QA today. the code LGTM if you can make an experimental for testing that would help 👍

2024-09-23 13:13 UTC, alexandrebodin commented on packages/cli/create-strapi-app/src/utils/get-package-manager-args.ts
> +  npm: {
Looks like these could be omitted

2024-09-24 07:12 UTC, Bassel17 commented
experimental: `0.0.0-experimental.117b0ba4c41638592858ef7c29fec09396cf01be`

2024-09-24 07:37 UTC, Bassel17 requested changes
encountered a different error while using the experimental for this 

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/1d325f49-841f-4c6b-a0b1-8d8aad20f841">

2024-09-24 07:42 UTC, innerdvations commented
Oops, which version of yarn is that with? I might have broken something in one of my last commits

2024-09-24 07:55 UTC, Bassel17 commented
> Oops, which version of yarn is that with? I might have broken something in one of my last commits

this is `Yarn 4.5.0`

2024-09-24 07:59 UTC, innerdvations commented
Yeah, my bad, I must have done something last minute and broke the one thing this was attempting to fix 😆

2024-09-24 10:55 UTC, innerdvations commented
Generating another experimental, the command run by execa for `yarn version`  and `yarn install` were running in different locations with differnt env options, which was causing version mismatches where it thought the system installed pm version was the same version that would run the install, but it wasn't necessarily

2024-09-24 11:47 UTC, innerdvations commented
Ok, finally got it I think: 0.0.0-experimental.d3243594aea3e6fa0ef08580192bb0df29c9162d

2024-09-24 11:57 UTC, Bassel17 approved these changes
LGTM ! tested with the latest experimental seems to be working now

2024-09-24 12:37 UTC, merged