fix: Error MISSING_TRANSLATION errors for locale 'ru'
strapi/strapi pull request #21575
Opened 2024-10-03 14:21 UTC by dkochetkov

Fixed some MISSING_TRANSLATION errors for locale 'ru' & added or supplemented some of 'ru' translations.

### What does it do?

Fixed errors in some 'ru' translation files, fixed an error due to the missing 'id' class in the 'packages/core/admin/admin/src/pages/Auth/components/Register.tsx' file

### Why is it needed?

A lot of errors in the console are annoying.

### How to test it?

Run new project in dev mode with 'ru' translation enabled, open admin panel in browser, open console and watch errors.

2024-10-03 14:26 UTC, dkochetkov commented
If someone helps to remove the error from the screenshot, I will be very glad.

<img width="1008" alt="Screenshot" src="https://github.com/user-attachments/assets/2cd15f9c-d949-4996-9fd1-f150b7bfeef9">

2024-10-03 14:51 UTC, hanpaine commented
hey @dkochetkov thanks for your contribution - we'll take a look very soon 🙏

2025-04-29 14:05 UTC, roslovets commented
> hey @dkochetkov thanks for your contribution - we'll take a look very soon 🙏

Any progress on this? RU locale is partially broken and cannot be used in production.

2025-04-29 15:12 UTC, hanpaine submitted a review, later dismissed

2025-04-29 15:15 UTC, hanpaine commented
Uber patience there @dkochetkov, thank you for following up!! Looking now...

2025-04-30 10:09 UTC, jhoward1994 commented on examples/getstarted/src/admin/app.jsx
> +  locales: ['it', 'es', 'en', 'en-GB', 'ru'],
```suggestion
  locales: ['it', 'es', 'en', 'en-GB'],
```

Hi, this PR looks good thanks!

If you could please just remove the addition of the russian locale here. We don't really want to change the default config of this example 🙏🏻

2025-04-30 10:15 UTC, jhoward1994 requested changes
Thanks for the PR, see my other comment

2025-04-30 13:39 UTC, jhoward1994 approved these changes

2025-04-30 13:41 UTC, merged

2025-04-30 13:41 UTC, jhoward1994 commented
Thank you 🙏🏻