fix(strapi/types): add Attribute column type for v5
strapi/strapi pull request #21858
Opened 2024-10-15 16:16 UTC by iamandrewluca

### What does it do?

Types the `Attribute.column` for Strapi v5

### Why is it needed?

Missing `column` type when create schema attributes

### Related issue(s)/PR(s)

#21577 #21580

2024-10-17 13:22 UTC, Convly approved these changes

2024-10-17 13:23 UTC, Convly requested changes
It seems the prettier check fails on this. Could you format the code to make it green? :slightly_smiling_face:

2024-10-17 13:26 UTC, iamandrewluca commented
Fixed

2024-10-18 09:08 UTC, Convly approved these changes

2024-10-18 09:08 UTC, merged