fix: Cleaner fallback for documents and audio files in the Media Libr…
strapi/strapi pull request #22378
Opened 2024-12-09 18:10 UTC by dilshad-knk

resolves #22211 

**Before** 

![image](https://github.com/user-attachments/assets/238016ed-833a-4b1a-8a92-025a9cb40f06)

**Now**

![Screenshot 2024-12-09 231747](https://github.com/user-attachments/assets/e5ca1c8b-654c-4a1f-9886-74e731fb7460)
![Screenshot 2024-12-09 231806](https://github.com/user-attachments/assets/303f5cc7-c9ad-40e2-8ef4-9620e33d791f)

2024-12-10 09:54 UTC, lucasboilly commented
Hi @dilshad-knk 🙂

All good on the design side, thanks a lot!

I'm gonna share the PR to the team 👍

2025-01-28 11:14 UTC, simotae14 requested changes
Hello @dilshad-knk thanks a lot for your contribution
Please take a look at my comments and also there is a FE unit test failing, can you please give it a look? thanks

2025-01-28 11:14 UTC, simotae14 commented on packages/core/upload/admin/src/components/TableList/PreviewCell.tsx
> +  switch (fileExtension) {
Instead of using a switch you can try to create a map like this one
`const DOC_ICON_MAP: Record<string, React.ComponentType<any>> = {
  pdf: FilePdf,
  csv: FileCsv,
  xls: FileXls,
  zip: FileZip,
} as const;`
and handle the document types in this way 
`const fileExtension = getFileExtension(ext);
  const DocIcon = DOC_ICON_MAP[fileExtension] ?? FileIcon;
  return (
    <Flex
      justifyContent="center"
      borderRadius="100%"
      background="neutral100"
      color="neutral500"
      width="3.2rem"
      height="3.2rem"
    >
      <DocIcon width={16} height={16} />
    </Flex>
  );`

2025-03-05 08:41 UTC, simotae14 commented
hello @dilshad-knk , thanks again for your contribution, can you please take a look at my comments and fix the issues with unit tests and e2e tests, thanks

2025-03-11 16:13 UTC, dilshad-knk commented
![image](https://github.com/user-attachments/assets/d10b25f9-ed34-49e5-a1c4-d9d757743155)

why iam getting this error in set up....its wsl

2025-06-12 12:57 UTC, Adzouz commented
Hey @simotae14, I made the changes inspired by your comment. Let me know if it's good for you so we can merge! 🚀

2025-06-17 14:29 UTC, simotae14 requested changes
Could we avoid having snapshot tests and instead replace them with a meaningful unit test? we are trying to remove all the useless snapshot tests

2025-06-26 08:38 UTC, Adzouz commented
> Could we avoid having snapshot tests and instead replace them with a meaningful unit test? we are trying to remove all the useless snapshot tests

Hey @simotae14, you're right, this snapshop is useless and we are already testing the functionality so I removed all match to snapshot in order to get rid of it.

2025-06-27 07:37 UTC, simotae14 approved these changes
well done

2025-06-27 07:39 UTC, merged