chore(telemetry): smooth event rate limiting
strapi/strapi pull request #22465
Opened 2024-12-18 13:15 UTC by Baldinof

### What does it do?

Rate limited events now resets 24h after the last event (or process start), instead of each day at midnight.

### Why is it needed?

It will smooth the sending of events, and avoid receiving a burst of events at midnight on the telemetry server.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2024-12-18 13:29 UTC, Convly requested changes
Code and behavior LGTM.

Could you run `yarn format:code` to solve the prettier issue?

2024-12-20 08:08 UTC, Convly approved these changes

2024-12-20 10:16 UTC, innerdvations approved these changes
LGTM, but I'm also curious why it's only once per day and not something like every 6 hours or 12 hours to smooth it out more

2024-12-23 07:57 UTC, Baldinof commented
Mainly to keep the rate the same, if it is reset every 12h, rate limited events will send more events.

2025-01-21 08:39 UTC, merged