chore: use rollup & nx watch mode
strapi/strapi pull request #22466
Opened 2024-12-18 15:38 UTC by alexandrebodin

### What does it do?

use rollup & nx watch mode to build code & typings of the monorepo for a better contibuting dx

2025-01-09 09:57 UTC, remidej commented on packages/core/admin/admin/src/utils/baseQuery.ts
Why are these changes (beyond packup/rollup stuff) needed?

2025-01-10 07:44 UTC, alexandrebodin commented on packages/core/admin/admin/src/utils/baseQuery.ts
All the code changes were made to fix typescript issues that poped during the setup of rollup because I used the ts typechecker natiely instead of how packup works

2025-01-10 09:32 UTC, remidej reviewed
it's not really possible to review all those changes, but they generally look good to me if we can make the tests pass

I'm also reaaally looking forward to that global watch mode 🙂

2025-01-16 16:19 UTC, markkaylor reviewed
Is there a reason in some rollup.config files you import from 'path' and other times 'node:path'?

I get some errors related to `path` receiving `undefined` in some rollup config files when ever build:code is called...but I'm guessing you don't have that on your end 🤔 :

<img width="1087" alt="Screenshot 2025-01-16 at 16 54 15" src="https://github.com/user-attachments/assets/d24fa3f0-b5d0-4003-b664-0c93fee8ca18" />
<img width="1085" alt="Screenshot 2025-01-16 at 16 56 47" src="https://github.com/user-attachments/assets/6bc5f403-3825-4a9b-9844-4e366481229a" />

It's definitely awesome to taste the XP of running a single command, make a change anywhere, and see the build triggered. But on my end I'm still stuck with these errors 😞

2025-01-16 16:21 UTC, alexandrebodin commented
> Is there a reason in some rollup.config files you `import path from 'path'` and other times `'node:path'`?
> 
> I get some errors related to `path` receiving `undefined` in some rollup config files when ever build:code is called...but I'm guessing you don't have that on your end 🤔 :
> 
> <img alt="Screenshot 2025-01-16 at 16 54 15" width="1087" src="https://private-user-images.githubusercontent.com/26598053/403941376-d24fa3f0-b5d0-4003-b664-0c93fee8ca18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwNDQ3MjIsIm5iZiI6MTczNzA0NDQyMiwicGF0aCI6Ii8yNjU5ODA1My80MDM5NDEzNzYtZDI0ZmEzZjAtYjVkMC00MDAzLWI2NjQtMGM5M2ZlZThjYTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE2VDE2MjAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkM2MwNzRkNWM2Mjg4MzUzNjY4YzZjMTBlMmVkZjAxMDNlOGI0MjE5YmViMTE5NWUxNDE1NDVjMTE5ZDhiNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AQQ1jz3Ss0uVM7iwIMGY9xHuIR83y4jR1sI5oaBfQuY"> <img alt="Screenshot 2025-01-16 at 16 56 47" width="1085" src="https://private-user-images.githubusercontent.com/26598053/403941427-6bc5f403-3825-4a9b-9844-4e366481229a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwNDQ3MjIsIm5iZiI6MTczNzA0NDQyMiwicGF0aCI6Ii8yNjU5ODA1My80MDM5NDE0MjctNmJjNWY0MDMtMzgyNS00YTliLTk4NDQtNGUzNjY0ODEyMjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE2VDE2MjAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMDA2M2RjOWQ2YjJjMzkzZTUyNDQwOTA5ZDJmMmZlOWMxZjA3OTE4YzI0M2ZmM2ZhNWM5M2YxZmZkY2NkMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nKNTsKDqygIqPEWu8RSfK-LVw3bIfcfMx8tHIfFOC94">
> It's definitely awesome to taste the XP of running a single command, make a change anywhere, and see the build triggered. But on my end I'm still stuck with these errors 😞

nope that's supposed to be equivalent. What version of node are you using ?

2025-01-17 10:26 UTC, markkaylor commented
> nope that's supposed to be equivalent. What version of node are you using ?

v20.0.0

2025-01-23 14:04 UTC, MarionLemaire commented
Tested today : 
I've tested the Admin and everything went smooth.
I did a quick QA round on the CTB, CM and MediaLib for safety, everything was fine except one random error at the first entry creation of my new CT (see screenshot) but just refreshing solved the problem.
Only thing I can report, but I have no idea if this could be related to the PR or to my new Mac setup still to be improved, is that I faced many issues about building Sharp when starting to launch my app, and many dependency conflits.
<img width="867" alt="Screenshot 2025-01-23 at 14 56 24" src="https://github.com/user-attachments/assets/bb01c80f-400f-41a4-b84f-d299d2892f89" />

2025-01-23 14:09 UTC, alexandrebodin commented
> Tested today : I've tested the Admin and everything went smooth. I did a quick QA round on the CTB, CM and MediaLib for safety, everything was fine except one random error at the first entry creation of my new CT (see screenshot) but just refreshing solved the problem. Only thing I can report, but I have no idea if this could be related to the PR or to my new Mac setup still to be improved, is that I faced many issues about building Sharp when starting to launch my app, and many dependency conflits. <img alt="Screenshot 2025-01-23 at 14 56 24" width="867" src="https://private-user-images.githubusercontent.com/97893822/406059261-bb01c80f-400f-41a4-b84f-d299d2892f89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc2NDE2NjAsIm5iZiI6MTczNzY0MTM2MCwicGF0aCI6Ii85Nzg5MzgyMi80MDYwNTkyNjEtYmIwMWM4MGYtNDAwZi00MWE0LWI4NGYtZDI5OWQyODkyZjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTIzVDE0MDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZTA5MjM3MzJjNGRmNjAzZjhhYjZhZWI5MTYxMzI4YWE2NmM2MTVlNmExY2EwZDM4NDBkNDI2ZmVmNjVkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aJYdRA1DLGblTBX7aG-L9XccRn-DSiwRnrnZdcc570o">

thanks I'll be able to look into it !

2025-01-24 13:30 UTC, innerdvations reviewed
So excited for this that I reviewed every file

2025-01-24 13:30 UTC, innerdvations commented on packages/generators/generators/src/plops/__tests__/content-type.test.ts
> +  }, 30000);
urghhhh, we still have "unit" tests with file effects, I might add this to the tech debt db 😆

2025-01-24 13:38 UTC, innerdvations commented
Follow-up to @remidej 's comments about the front-end changes, is there any way this could affect user code and make them change anything?

2025-01-24 15:02 UTC, Convly requested changes
Love it

2025-01-24 16:22 UTC, alexandrebodin commented on packages/core/core/src/services/document-service/transform/__tests__/utils.ts
> +import type { Schema, Common } from '@strapi/types';
Will fix it in passing then :D

2025-01-24 16:22 UTC, alexandrebodin commented on packages/core/core/src/utils/update-notifier/index.ts
> +import pkg from '../../../package.json';
def

2025-01-24 16:22 UTC, alexandrebodin commented on tests/api/core/strapi/filtering.test.api.js
> +  describe.only('Basic filters', () => {
:facepalm

2025-01-24 16:24 UTC, alexandrebodin commented on packages/generators/generators/src/plops/__tests__/content-type.test.ts
> +  }, 30000);
yeah not gonna fix it in there we have enough changes already :D

2025-01-24 16:24 UTC, alexandrebodin commented on nx.json
> +      "dependsOn": ["^build:types"],
yes it's the dependency graph so it will enforce ordering of building

2025-01-24 16:26 UTC, alexandrebodin commented on packages/plugins/users-permissions/server/register.js
> +    const specPath = path.join(__dirname, '../../documentation/content-api.yaml');
the dist was generated inside a sub folder, not anymore so the relative path after build has changed

2025-01-24 16:27 UTC, alexandrebodin commented on packages/core/types/package.json
> +    "watch": "run -T tsc -p tsconfig.build.json -w"
swc doesn't do delcaration generation we can't sadly

2025-01-24 16:28 UTC, alexandrebodin commented on packages/core/review-workflows/admin/src/utils/cm-hooks.ts
> +import { REVIEW_WORKFLOW_COLUMNS } from '../routes/content-manager/model/constants';
I'll check I think it's filename for cm-hooks needs to be camelCase

2025-01-24 16:28 UTC, alexandrebodin commented on packages/core/content-type-builder/admin/src/index.ts
> +        defaultMessage: 'Content-Type Builder',
actually I noticed this because the translations didn't work at 1st and it broke a test :)

2025-01-24 16:28 UTC, alexandrebodin commented on packages/core/admin/admin/src/index.ts
> +} from './utils/getFetchClient';
I'll check I think I export everything anyway

2025-01-24 20:42 UTC, alexandrebodin commented on packages/core/admin/ee/server/src/audit-logs/services/__tests__/audit-logs.test.ts
> +import createEventHub from '../../../../../../../core/src/services/event-hub';
where do you see this error ?

2025-01-27 08:56 UTC, alexandrebodin commented on packages/utils/typescript/package.json
> +    "typescript": "5.4.4"
Docusaurs isn't happy about it I'll leave it as is for now

2025-01-27 09:05 UTC, alexandrebodin commented on packages/core/upload/server/src/controllers/validation/admin/folder-file.ts
> +        .filter((folder: any) => isFolderOrChild(destinationFolder, folder))
I typed the db response instead

2025-01-27 09:14 UTC, alexandrebodin commented on packages/core/admin/admin/src/index.ts
> +} from './utils/getFetchClient';
Ok found a way to reuse the old export, had to change one above as the ApiError has moved and needs to be export from somewhere else, but won't change anything for end users

2025-01-27 15:44 UTC, innerdvations commented
Tried to build an experimental and it [failed on @strapi/upgrade](https://github.com/strapi/strapi/actions/runs/12992574463/job/36232731787) but seems like a minor issue

2025-01-27 16:19 UTC, Convly commented
(hopefully) Fixed in c4796a8 and triggered another xp at https://github.com/strapi/strapi/actions/runs/12993386971

2025-01-27 16:22 UTC, Convly commented
> Tried to build an experimental and it [failed on @strapi/upgrade](https://github.com/strapi/strapi/actions/runs/12992574463/job/36232731787) but seems like a minor issue

Seems fixed

![image](https://github.com/user-attachments/assets/6a0ac2af-ed4e-4b1f-8e99-fb6b0ffb0714)

2025-01-28 10:40 UTC, innerdvations commented
![image](https://github.com/user-attachments/assets/0f0f79ac-31f0-41d1-ba45-38c80e17f13c)

Looks like something changed with exports, this is what I get when creating a seeded project with the experimental

2025-01-28 10:41 UTC, alexandrebodin commented on packages/core/admin/ee/server/src/audit-logs/services/__tests__/audit-logs.test.ts
> +import createEventHub from '../../../../../../../core/src/services/event-hub';
I fixed it in the last changes

2025-01-28 11:38 UTC, Bassel17 commented
@alexandrebodin you probably need to update the build scripts in the publishing scripts, pre-publish.sh and publish.sh

2025-01-28 13:36 UTC, alexandrebodin commented
Ok @innerdvations I just pushed again if you want to test it wasn't happy becuse the core pkg only had the `exports` key and no root `types` key.

2025-01-29 08:12 UTC, alexandrebodin commented
Latest pre publish https://github.com/strapi/strapi/actions/runs/13016924632/job/36308324320

2025-01-29 10:28 UTC, innerdvations submitted a review, later dismissed
It's all working for me now!

I checked that Strapi projects themselves still build and run with Node 20.9, so that issue should only affect developers on the monorepo, which we may want to point out somewhere like contributor docs.

2025-01-29 13:36 UTC, Convly approved these changes
LGTM, tested and everything builds correctly

2025-01-29 18:19 UTC, merged