reduce batchSize to 500 to support sqlite
strapi/strapi pull request #22503
Opened 2024-12-24 07:58 UTC by laurenskling

### What does it do?

sqlite queries crash when setting over 500 relations. Thus migration a contentType with over 500 entries with relations will make this migration fail. Limiting to 500 batchSize fixes this.

### Why is it needed?

Right now, the migration fails and the startup will crash. You are not able to start a v5 project with a v4 db with 500+ entries with over relations.

### How to test it?

Migrate with it.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/22318

2024-12-24 09:10 UTC, derrickmehaffy approved these changes

2024-12-24 09:12 UTC, derrickmehaffy requested changes
Can you fix your commit message, it's failing linting

2024-12-27 09:31 UTC, derrickmehaffy approved these changes

2025-01-06 09:28 UTC, Convly commented
Hey, 

> sqlite queries crash when setting over 500 relations.

Is 500 the exact limit? Or is it an arbitrary number? I haven't really worked on this specific migration but it's quite interesting :thinking: 

Is the crash because of the transaction size? (although I doubt it is) or more about the sql engine itself that cannot handle that many updates at once?

2025-01-06 09:31 UTC, laurenskling commented
It crashes on `too many terms in compound SELECT`. I'm no SQL expert. But it's making one big query sqlite is refusing. going over 500 makes it `too many`.

2025-01-06 10:48 UTC, jhoward1994 commented
I'd be a bit concerned about reducing the `batchSize` in every case. I think this could slow down the migration on DB engines where that isn't necessary. & I believe this is configurable anyway in sqlite through `SQLITE_LIMIT_COMPOUND_SELECT`

Would something like this make more sense?
```
// SQLite has a limit on terms in compound SELECT queries (default limit: 500).
// Reducing batch size to 500 prevents crashes during migration.
const DEFAULT_BATCH_SIZE = db.client.config.client === 'sqlite3' ? 500 : 1000;
```

2025-01-06 10:49 UTC, laurenskling commented
I would be happy with everything that doesn't crash on sqlite :)

2025-01-07 10:02 UTC, jhoward1994 commented on packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts
>    trx: Knex;
Could I suggest we do this then? wdyt @Convly? (suggestion for the entire function)
```suggestion
/**
 * Load a batch of versions to discard.
 *
 * Versions with only a draft version will be ignored.
 * Only versions with a published version (which always have a draft version) will be discarded.
 */
export async function* getBatchToDiscard({
  db,
  trx,
  uid,
  defaultBatchSize = 1000,
}: {
  db: Database;
  trx: Knex;
  uid: string;
  defaultBatchSize?: number;
}) {
  const client = db.config.connection.client;
  const isSQLite = ['sqlite', 'sqlite3', 'better-sqlite3'].includes(client as any);

  const batchSize = isSQLite ? 500 : defaultBatchSize;

  let offset = 0;
  let hasMore = true;

  while (hasMore) {
    // Look for the published entries to discard
    const batch: DocumentVersion[] = await db
      .queryBuilder(uid)
      .select(['id', 'documentId', 'locale'])
      .where({ publishedAt: { $ne: null } })
      .limit(batchSize)
      .offset(offset)
      .orderBy('id')
      .transacting(trx)
      .execute();

    if (batch.length < batchSize) {
      hasMore = false;
    }

    offset += batchSize;
    yield batch;
  }
}
```

2025-01-07 13:44 UTC, Convly commented on packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts
>    trx: Knex;
If we can get rid of the any + add a small explanation, it looks good to me

For example, we can reference https://www.sqlite.org/limits.html (7) or directly quote an extract of

```
Maximum Number Of Terms In A Compound SELECT Statement

A compound  SELECT statement is two or more SELECT statements connected by operators UNION, UNION ALL, EXCEPT, or INTERSECT. We call each individual SELECT statement within a compound SELECT a "term".

The code generator in SQLite processes compound SELECT statements using a recursive algorithm. In order to limit the size of the stack, we therefore limit the number of terms in a compound SELECT. The maximum number of terms is SQLITE_MAX_COMPOUND_SELECT which defaults to 500. We think this is a generous allotment since in practice we almost never see the number of terms in a compound select exceed single digits.
```

2025-01-09 16:52 UTC, jhoward1994 commented
@Convly @laurenskling please could you take a look at the latest commit and let me know if you're happy with that solution

@laurenskling I hope you're okay with me pushing directly to your branch 🙏🏻

2025-01-09 16:58 UTC, Convly commented on packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts
> +  const batchSize = isSQLite ? 500 : defaultBatchSize;
Shouldn't this be the following to avoid overriding a lower batch size on SQLite (manually defined)? 

```suggestion
  const batchSize = isSQLite ? Math.min(defaultBatchSize, 500) : defaultBatchSize;
```

2025-01-09 19:11 UTC, laurenskling commented
> @laurenskling I hope you're okay with me pushing directly to your branch 🙏🏻

go for it mate. Just like to see it working :) don't care how. 
Thanks for doing the work

2025-01-10 13:48 UTC, Convly approved these changes

2025-01-10 17:40 UTC, merged

2025-01-13 07:57 UTC, laurenskling commented
Thanks for the work friends