Add LinkedIn auth provider
strapi/strapi pull request #7490
Opened 2020-08-16 12:57 UTC by abolkog

#### Description of what you did:
Added **LinkedIn** auth provider to support login via LinkedIn

2020-08-18 07:28 UTC, lauriejim commented
Hello @abolkog !

Thank you for this integration.

Can you please add the documentation related to the settings of this provider.
Here is the page where you have to add the documentation.
To do so, you will have to update the `docs/v3.x/plugins/users-permissions.md` file.
For the format, please, follow the same as the other provider.

Thank you.

2020-08-18 12:16 UTC, abolkog commented
Hey @lauriejim I have added the documentation.

2020-08-24 10:42 UTC, abolkog commented
hey @lauriejim any chance we can get this PR reviewed 😅

2020-08-24 15:02 UTC, derrickmehaffy commented
Hi @abolkog let me poke @petersg83

2020-09-03 09:16 UTC, petersg83 requested changes
Hi ! Thank you for your contribution, I just tried it and it works well :)
I've noticed a few typos, can you fix them please? Then we're good to merge!
Also if you can rebase your branch on master so there are no conflicts it would be perfect. Thanks!

2020-09-04 08:29 UTC, abolkog commented on docs/v3.x/plugins/users-permissions.md
> +  - **App Logo**: Upload a square image that at least 100x100 pixel.
Fixed

2020-09-04 08:29 UTC, abolkog commented on docs/v3.x/plugins/users-permissions.md
> +  - **LinkedIn Page**: Enter a LinkedIn page name to associate with the app or click **Create a new LinkedInPage** to create a new one
Fixed

2020-09-04 08:30 UTC, abolkog commented
Thanks @petersg83  for the review. I have fixed the typos and rebased to master.

2020-09-04 10:20 UTC, petersg83 commented
Hi ! Thanks :) It seems you have un unexpected file in your PR : `packages/strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js`
Can you fix that please? :)

2020-09-04 12:34 UTC, abolkog commented
@petersg83 removed the additional file

2020-09-04 12:36 UTC, petersg83 approved these changes
LGTM thanks for your contribution ! :D

2020-09-04 12:37 UTC, merged