Update file info mutation
strapi/strapi pull request #7691
Opened 2020-09-02 08:02 UTC by Cr0s4k

#### Description of what you did:
Adds a new mutation that allows to update file information. Fixes https://github.com/strapi/strapi/issues/7406

State: **WIP**

2020-09-02 15:16 UTC, alexandrebodin requested changes

2020-09-02 15:16 UTC, alexandrebodin commented on packages/strapi-plugin-upload/config/schema.graphql.js
> +    updateFileInfo(id: ID!, name: String, alternativeText: String, caption: String): UploadFile!
can you create a fileInfo input type :)

2020-09-03 09:18 UTC, Cr0s4k commented on packages/strapi-plugin-upload/config/schema.graphql.js
> +    updateFileInfo(id: ID!, name: String, alternativeText: String, caption: String): UploadFile!
Sure!

2020-09-03 10:17 UTC, alexandrebodin approved these changes
LGTM

2020-09-03 10:17 UTC, merged