Assume selection is text when creating a link
strapi/strapi pull request #8071
Opened 2020-09-27 17:46 UTC by jlsjonas

Fixes #7890

#### Description of what you did:
Title says it all, when replacing a selection, assume the selection is text and not a link; as per the issue

2020-09-28 12:38 UTC, sam-pires commented
Hello @jlsjonas,
Thanks for the PR 👍 

I still have the same behavior as the current one. It has not changed.
@soupette wdyt?

2020-09-28 14:03 UTC, soupette requested changes
In order to make the selected change you'll also need to update `Wysiwyg/constants.js` file L.79 with the following:


```
{
  label: 'Link',
  style: 'LINK',
  className: 'link',
  hideLabel: true,
  handler: 'addContent',
  text: '[textToReplace](link)',
},
```

2020-09-28 14:03 UTC, soupette commented on packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/helpers.js
> +        endReplacer: '](https://example.org)',
the endReplacer could just be `]`

2020-09-28 15:32 UTC, soupette approved these changes
LGTM!

Thanks a lot for your contribution.

2020-09-29 11:20 UTC, jlsjonas commented
@soupette You're welcome!
What do we do with the coverage report failing at -0% due to lack of testing in that area of the code?

2020-09-29 11:48 UTC, soupette commented
> @soupette You're welcome!
> What do we do with the coverage report failing at -0% due to lack of testing in that area of the code?

Appart from adding some tests to this component not much. Even though the coverage doesn't pass we will still merge this PR.

2020-09-29 12:13 UTC, merged