Split init route to init & information endpoints
strapi/strapi pull request #8160
Opened 2020-10-02 15:11 UTC by Convly

2020-10-02 15:18 UTC, alexandrebodin requested changes
a Unit test ?

2020-10-06 07:55 UTC, petersg83 requested changes
A little remark

2020-10-06 07:55 UTC, petersg83 commented on packages/strapi-admin/controllers/__tests__/admin.test.js
> +// const createContext = require('../../../../test/helpers/create-context');
Should we remove this comment?

2020-10-06 08:01 UTC, Convly commented on packages/strapi-admin/controllers/__tests__/admin.test.js
> +// const createContext = require('../../../../test/helpers/create-context');
Thanks, fixed :tada:

2020-10-06 09:13 UTC, petersg83 approved these changes
LGTM :)

2020-10-06 09:26 UTC, merged