Clarify some of the template creation steps
strapi/strapi pull request #8482
Opened 2020-10-26 16:16 UTC by jorisw

### What does it do?

Clarifies some of the steps for creating a template.

### Why is it needed?

Without the changes, I found some of the steps ambiguous.

### Related issue(s)/PR(s)

None

2020-10-27 08:30 UTC, remidej requested changes
Thanks for the suggestions, we're always happy to make the docs clearer. Please just review my 2 comments so we can merge

2020-10-27 08:30 UTC, remidej commented on docs/v3.x/concepts/templates.md
>  7. Think of all the files you have modified in your app, and copy them to the `/template` directory
Maybe replace `/template` with `template` for consistency

```suggestion
7. Think of all the files you have modified in your app, and copy them to the `template` directory
```

2020-10-27 08:30 UTC, remidej commented on docs/v3.x/concepts/templates.md
> +5. If you have modified your app's `package.json`, include these changes (and _only_ these changes) in `template.json`, in a `package` property. Otherwise, have the template file represent an empty o
> have the template file represent 

I think there should be a better way to phrase this. As a non-native, it seems odd to me

2020-10-28 09:31 UTC, remidej commented
Thanks! Now @jorisw you just need to sign your commits so we can merge. See [the instructions on the DCO check](https://github.com/strapi/strapi/pull/8482/checks?check_run_id=1319567242)

2020-11-30 14:34 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=8482) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=8482) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=8482) it.</sub>

2020-11-30 17:56 UTC, remidej approved these changes
Hello @jorisw

Good news: we don't need you to sign your commits anymore to merge this. Instead, you can click the [link](https://cla.strapi.io/strapi/strapi?pullRequest=8482) shared by the Strapi CLA bot, and follow the process there.

2020-11-30 18:33 UTC, derrickmehaffy approved these changes
LGTM

2020-11-30 18:33 UTC, merged