Update databases.md
strapi/strapi pull request #8523
Opened 2020-10-30 14:47 UTC by bigpreshy

Without removal of these first string, it bring some error messages:
'replicaSet' is not recognized as an internal or external command,
operable program or batch file.
'authSource' is not recognized as an internal or external command,
operable program or batch file.
'retryWrites' is not recognized as an internal or external command,
operable program or batch file.
'w' is not recognized as an internal or external command,
operable program or batch file.

and the build fails.

### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2020-10-30 14:50 UTC, bigpreshy commented
Without removal of these first string, it bring some error messages which makes it fails to build

2020-10-30 18:14 UTC, bigpreshy commented on docs/v3.x/guides/databases.md
> +You **must** use remove some string and it has to look like so:
Ok

2020-11-02 10:01 UTC, meganelacheny commented on docs/v3.x/guides/databases.md
> +You **must** use remove some string and it has to look like so:
Hello 👋 
Yes @derrickmehaffy I agree with the rephrasing you suggested. However, no need to put "must" in bold.

2020-11-02 10:07 UTC, bigpreshy commented on docs/v3.x/guides/databases.md
> +You **must** use remove some string and it has to look like so:
Ok...
I also have found a way to connect to mongo dB atlas without having to have mongo dB installed locally first as suggested by the documentation...

I am working on an article for this...

2020-11-02 18:36 UTC, derrickmehaffy commented on docs/v3.x/guides/databases.md
> +You **must** use remove some string and it has to look like so:
Do you want me to hold this PR then @bigpreshy ?

2020-11-09 06:50 UTC, bigpreshy commented on docs/v3.x/guides/databases.md
> +You **must** use remove some string and it has to look like so:
No, you can go ahead... The article will different from this issue. Just that you one won't encounter this issue when deploying

2020-11-09 14:22 UTC, derrickmehaffy requested changes

2020-11-09 14:22 UTC, derrickmehaffy commented on docs/v3.x/guides/databases.md
> +You **must** use remove some string and it has to look like so:
Can you make the change that @meganelacheny suggested and remove the bold around `must`

2020-11-30 14:34 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=8523) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=8523) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=8523) it.</sub>

2020-11-30 16:01 UTC, derrickmehaffy requested changes

2020-11-30 16:01 UTC, derrickmehaffy commented on docs/v3.x/guides/databases.md
> +You **must** use remove some string and it has to look like so:
Can you remove the `**` around `must` please then I can merge this in

2020-11-30 17:10 UTC, derrickmehaffy approved these changes
LGTM

2020-11-30 17:11 UTC, merged