RBAC : Decorrelate create action, fix bugs, some refacto
strapi/strapi pull request #8572
Opened 2020-11-04 14:15 UTC by HichamELBSI

### What does it do?

- Scope : RBAC
- Decorrelate the create action of the required fields for the EE.
- Fix the conditions bullet bug
- Some code refacto (Still need some refacto)

### Why is it needed?

Describe the issue you are solving.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2020-11-04 14:19 UTC, HichamELBSI commented on packages/strapi-admin/admin/src/components/Roles/Permissions/requiredActions.js
> +export default requiredActions;
Not a useless file because the EE equivalent is different.

2020-11-17 17:56 UTC, soupette requested changes

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/ContentTypesAttributes/AttributeRow.js
> +        type: 'ALL_CONTENT_TYPE_PERMISSIONS_SELECT',
Also, you don't need the `shouldEnable` constant and the `contentType.uid` you can use the target

```
const handleCheckAllActions = ({ target: {  name, value }) => {
  // In order to have the name matches the content type uid you need to change the name of the checkbox to contentType.uid
  dispatch({ type, attributes, shouldEnable: value, subject: name})
}
```

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
> +    const existingActions = getAllAttributesActions(contentType.uid, contentTypesPermissions);
Can you declare a constant so you don't have to compute the getAllAttributesAction twice ?

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
> +    dispatch({
Same here about the shouldEnable you can use `target.value`

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
> +              /* eslint-disable */
`/* eslint-disable indent */`

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
> +              /* eslint-enable */
`/* eslint-enable indent */`

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
> +                    onChange: () => handleActionSelect(action),
`handleActionSelect` and `handleContentTypeActionSelect`  are not defined in CE.

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/ContentTypesRow/ComponentsAttributes/ComponentAttributeRow.js
> +      const shouldSetRequiredFields = action === `${contentManagerPermissionPrefix}.create`;
Here you can use the target as well,

```
useCallback(({ target: { name, value}, action ) => { // you'll need to update the name of the checkbox so it matches the content type uid

if (isCollapsable) { 
  dispatch({
    type: 'SELECT_MULTIPLE_ATTRIBUTE',
    subject: contentTypeUid, // this should be the name of the synthetic event.
    shouldEnable: value,
    attributes: recursiveAttributes,
    action,
  });
}

```

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/ContentTypesRow/ComponentsAttributes/ComponentAttributeRow.js
> +                onChange={() => handleCheck(action)}
`onChange={e => handleCheck(e, action)}` // it might be worth to create a component here.

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/ContentTypesRow/ContentTypesAttributes/AttributeRow.js
> +  const handleCheckAllAction = useCallback(() => {
Same here about the target.

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/ContentTypesRow/ContentTypesAttributes/AttributeRow.js
> +  const handleCheckCollapsable = useCallback(
Same here as well

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/useFillRequiredPermissions.js
> +  const { contentTypesPermissions, components, dispatch } = usePermissionsContext();
I think this should be done in the reducer instead of having a hook. I'll let you decide if you think it is relevant.

2020-11-17 17:56 UTC, soupette commented on packages/strapi-admin/ee/admin/components/Roles/Permissions/PluginsAndSettingsPermissions/PermissionRow/SubCategory/index.js
> +    dispatch({
I think you can use the target here as well.

2020-11-19 12:15 UTC, HichamELBSI commented on packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/PermissionsHeader/index.js
> +      dispatch({
This comment is also related to the content types in the reducer. I will centralize those comments to not forget this refacto 👍🏽

2020-11-19 15:15 UTC, soupette approved these changes
LGTM

2020-11-30 14:33 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=8572) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=8572) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=8572) it.</sub>

2020-12-10 15:27 UTC, HichamELBSI commented on packages/strapi-admin/admin/src/translations/en.json
> +  "Settings.permissions.conditions.no-actions": "You first need to select actions (create, read, update, ...) before defining conditions on them.",
https://www.notion.so/strapi/UX-UI-Enhancements-b86acfc398f34936ae7ca4b64ca28bab?p=54cd50c0db314769a401bd108fb16e12

2020-12-10 15:27 UTC, HichamELBSI commented on packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
> +          headerBreadCrumbs={[contentType.name, 'app.components.LeftMenuLinkContainer.settings']}
https://www.notion.so/strapi/UX-UI-Enhancements-b86acfc398f34936ae7ca4b64ca28bab?p=73b4559a3dfc4cd8ab8da59d7d6d4b49

2020-12-11 07:46 UTC, soupette submitted a review, later dismissed
LGTM

2020-12-16 09:01 UTC, merged