update mailgun readme
strapi/strapi pull request #8674
Opened 2020-11-17 15:54 UTC by andyatflocc

fix #8492 
Ready to be merged.

### What does it do?

One additional line of example config 

### Why is it needed?

If you use mailgun's EU servers, without this one line, the plugin does not work

### Related issue(s)/PR(s)
https://github.com/strapi/strapi/issues/8492
Let us know if this is related to any issue/pull request

2020-11-17 21:53 UTC, derrickmehaffy requested changes
Please also set the source branch and target branch for the PR as `documentation` and not the `master` branch.

https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#documentation

2020-11-17 21:53 UTC, derrickmehaffy commented on packages/strapi-provider-email-mailgun/README.md
> +      host: env('MAILGUN_HOST') // If you are using EU servers, you need to specify the host. api.eu.mailgun.net for EU Servers (or api.mailgun.net for US servers)
If this is optional it needs to have the default value in the env function. 

`env('MAILGUN_HOST', 'whatever the default is')`

2020-11-30 14:33 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=8674) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=8674) before we can accept your contribution.<br/>**0** out of **5** committers have signed the CLA.<br/><br/>:x: dependabot[bot]<br/>:x: soupette<br/>:x: alexandrebodin<br/>:x: Convly<br/>:x: andyatflocc<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=8674) it.</sub>

2020-12-04 10:02 UTC, alexandrebodin commented
Hi, you branch is out of sync with the repo. I think you started from master & switched to documentation but you brought with it a few commits. can you make sure your PR only contains what you did ?

2021-01-14 09:52 UTC, alexandrebodin commented
Hello, I'm going to close this PR because of inactivity. Feel free to open a new on or ping me here if you want to finish it ;)

2021-01-14 09:52 UTC, closed without merging