Split providers and grant config to a new file
strapi/strapi pull request #8741
Opened 2020-11-25 17:23 UTC by abdonrd

### What does it do?

Split providers and grant config to a new file

### Why is it needed?

To create new providers more easily.

2020-11-30 14:32 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=8741) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=8741) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=8741) it.</sub>

2020-12-04 09:54 UTC, alexandrebodin requested changes
Hi @abdonrd thanks for this cleanup. Unfortunately this will break our documentation on how to contribute to this. Can you make an update and check with @derrickmehaffy ?

2020-12-04 10:31 UTC, abdonrd commented
@alexandrebodin @derrickmehaffy new PR for the documentation! https://github.com/strapi/strapi/pull/8794

2020-12-18 14:33 UTC, alexandrebodin requested changes

2020-12-18 14:33 UTC, alexandrebodin commented on packages/strapi-plugin-users-permissions/services/Providers.js
> +const providers = require('./ProviderList');
can you please use kebab-case-naming for the new file :)

2020-12-18 14:33 UTC, alexandrebodin commented on packages/strapi-plugin-users-permissions/services/Providers.js
> +    await providers[provider](grant, access_token, query, callback);
can you pass an object instead 

```js
const context = { grant, access_token, query }
providers[provider](context, callback)
```

2020-12-18 16:49 UTC, abdonrd commented
@alexandrebodin thanks for the review!

I created another PR (https://github.com/strapi/strapi/pull/8942) because this appears broken for a reason that I do not understand:

<img width="191" alt="Screenshot 2020-12-18 at 17 48 35" src="https://user-images.githubusercontent.com/1007051/102639476-69ed8280-4159-11eb-87c5-1195c609a814.png">

2020-12-18 16:51 UTC, closed without merging