Documentation
strapi/strapi pull request #8765
Opened 2020-11-28 08:46 UTC by tobyglei

### What does it do?

Add Hosting Provider Guides for 21YunBox

### Why is it needed?

The current hosting providers on the documents don't work in China because the Great Firewall of China. 21YunBox is here to solve the problem.

### Related issue(s)/PR(s)

na.

2020-11-30 14:32 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=8765) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=8765) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=8765) it.</sub>

2020-12-11 02:40 UTC, tobyglei commented
can anyone review this? Thanks

2020-12-14 23:10 UTC, derrickmehaffy commented
@tobyglei the SVG you are using appears to be clipped: 

![image](https://user-images.githubusercontent.com/8593673/102146842-89657200-3e1e-11eb-8d47-ac7171e8a01b.png)

2020-12-14 23:12 UTC, derrickmehaffy requested changes

2020-12-14 23:12 UTC, derrickmehaffy commented on docs/v3.x/deployment/21yunbox.md
> +   |                       |                                                  |
Please add headers to your table

2020-12-14 23:12 UTC, derrickmehaffy commented on docs/v3.x/deployment/21yunbox.md
> +   |                       |                                                  |
Also, needs table headers

2020-12-14 23:12 UTC, derrickmehaffy commented on docs/v3.x/getting-started/deployment.md
> +    <svg width="64" height="64" xmlns="http://www.w3.org/2000/svg"><defs><filter id="a"><feColorMatrix in="SourceGraphic" values="0 0 0 0 1.000000 0 0 0 0 1.000000 0 0 0 0 1.000000 0 0 0 1.000000 0"/
As mentioned in my comment, your SVG is being clipped, you may need to adjust the SVG to get it to fit properly.

2020-12-14 23:13 UTC, derrickmehaffy commented
We are in the process of moving to a new Documentation repo, we may need to close this PR and have it reopened on the new repo here: https://github.com/strapi/documentation unless the changes can be made in the next 24 hours.

2020-12-15 22:15 UTC, derrickmehaffy commented
Closing, please take my review comments and submit a PR to the new documentation repo.

2020-12-15 22:15 UTC, closed without merging