Fix migration when disabling dp on sqlite
strapi/strapi pull request #8768
Opened 2020-11-30 11:08 UTC by petersg83

After disabling _draft&publish_ with _sqlite_, the indexes were gone.
It's because of this bug: https://github.com/knex/knex/issues/631

2020-11-30 14:32 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=8768) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=8768) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=8768) it.</sub>

2020-12-04 10:39 UTC, alexandrebodin requested changes
What about implementing a "correct" version of dropColumn ? (reusing part of the logic we already have with rebuilding a sqlite table)

I would rather we avoid passing infos from the hooks to the migration function. it should be  more standard like updating the schema in the hooks so that the next step just look at the schemas and knows it needs to be recreated.

2020-12-04 14:34 UTC, petersg83 commented
> What about implementing a "correct" version of dropColumn ? (reusing part of the logic we already have with rebuilding a sqlite table)
> 
> I would rather we avoid passing infos from the hooks to the migration function. it should be more standard like updating the schema in the hooks so that the next step just look at the schemas and knows it needs to be recreated.

I thought about it but it would mean thinking of refacto of the whole file no ? I prefered to be quick and wait for when we will have time to think about it deeper, as it is just a fix for the moment.

2020-12-08 16:16 UTC, alexandrebodin commented on packages/strapi-connector-bookshelf/lib/migrations/create-migration-runner.js
> +    const migrationInfos = await beforeHook(options);
we could create a context to pass to the hooks. so the gooks can set the recreateTable option to true and just interpret this option in the next step

2020-12-16 16:42 UTC, petersg83 commented on packages/strapi-connector-bookshelf/lib/build-database-schema.js
> +  if (definition.client === 'sqlite3') {
It would be misleading too no ? having `columnsToAlter.length > 0 || context.recreateSqliteTable` even if we use postgres

2020-12-16 16:57 UTC, alexandrebodin commented on packages/strapi-connector-bookshelf/lib/build-database-schema.js
> +  if (definition.client === 'sqlite3') {
I thought it was just recreateTable my bad :D

I would add the client in the condition too to make it clear indeed 
```
const shouldRebuild = columnsToAlter.length > 0 || (client === sqlite3 && context.recreateSqliteTable)

if (shouldRebuild) {
  switch (client) {
    sqlite3: { /* rebuild */}
    default: { /* alter */ }
  }
}
```

2020-12-16 17:11 UTC, petersg83 commented on packages/strapi-connector-bookshelf/lib/build-database-schema.js
> +  if (definition.client === 'sqlite3') {
ok, good for me :) on it

2020-12-17 10:21 UTC, alexandrebodin requested changes

2020-12-17 10:21 UTC, alexandrebodin commented on packages/strapi-connector-bookshelf/lib/build-database-schema.js
> +        if (columnsToAlter.length > 0) {
you don't need this condition anymore here :)

2020-12-17 11:32 UTC, alexandrebodin approved these changes

2020-12-17 11:33 UTC, merged