strapi-provider-email-mailgun: updates documentation
strapi/strapi pull request #8891
Opened 2020-12-14 18:09 UTC by meck93

Signed-off-by: Moritz Eck <moritz.eck@gmail.com>

### What does it do?
- updates the documentation

### Why is it needed?
- Saves users with a European mailgun host some time during the setup and the integration. 

### Related issue(s)/PR(s)
- None, I noticed it when I tried to use the mailgun email provider.

2020-12-14 18:09 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=8891) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=8891) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=8891) it.</sub>

2020-12-14 22:53 UTC, derrickmehaffy requested changes
We will need this changes made here soon as we are moving our documentation to a new repo. If you are unable to make the changes in the next few hours, I will close this and make the changes on our new repo here: https://github.com/strapi/documentation

2020-12-14 22:53 UTC, derrickmehaffy commented on packages/strapi-provider-email-mailgun/README.md
> +      // Required if you have an account with multiple domains
Please keep comments in line with the config option

2020-12-14 22:53 UTC, derrickmehaffy commented on packages/strapi-provider-email-mailgun/README.md
> +      domain: env('MAILGUN_DOMAIN'),
Please state this is optional and try to shorten the comment to a single line with the config option. Default should be `api.us.mailgun.net`

2020-12-15 07:43 UTC, meck93 commented
Hi @derrickmehaffy, thanks for the review. I have updated the documentation according to your feedback.

2020-12-15 16:05 UTC, derrickmehaffy requested changes

2020-12-15 16:05 UTC, derrickmehaffy commented on packages/strapi-provider-email-mailgun/README.md
> +      host: 'api.us.mailgun.net', //Optional. If domain region is Europe: 'api.eu.mailgun.net'
It should be `host: env('MAILGUN_HOST', 'api.us.mailgun.net')`

2020-12-17 22:03 UTC, derrickmehaffy approved these changes
LGTM

2020-12-17 22:04 UTC, derrickmehaffy commented
Pending tests then good to merge

2020-12-18 14:55 UTC, merged