Add auth providers list and page to the EE login workflow
strapi/strapi pull request #8973
Opened 2020-12-22 10:04 UTC by HichamELBSI

### What does it do?

Describe the technical changes you did.

### Why is it needed?

Describe the issue you are solving.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2020-12-23 09:00 UTC, soupette requested changes

2020-12-23 12:47 UTC, HichamELBSI commented on packages/strapi-admin/ee/admin/containers/AuthPage/components/Login/index.js
> +/* eslint-disable jsx-a11y/click-events-have-key-events */
This rule isn't needed anymore as ProviderButton is now an `a` HTML element so the accessibility is natively activated (Navigated between providers with `tab`, press `enter` to select a provider).

2020-12-23 12:49 UTC, pelumiojebode commented
I provide

On Wed, Dec 23, 2020 at 1:47 PM ELABBASSI Hicham <notifications@github.com>
wrote:

> *@HichamELBSI* commented on this pull request.
> ------------------------------
>
> In
> packages/strapi-admin/ee/admin/containers/AuthPage/components/Login/index.js
> <https://github.com/strapi/strapi/pull/8973#discussion_r547942376>:
>
> > @@ -0,0 +1,82 @@
> +/* eslint-disable jsx-a11y/click-events-have-key-events */
>
> This rule isn't needed anymore as ProviderButton is now an a HTML element
> so the accessibility is natively activated (Navigated between providers
> with tab, press enter to select a provider).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/strapi/strapi/pull/8973#discussion_r547942376>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR6UBOKYDAADNCPFEN76STDSWHRHDANCNFSM4VFNHKNA>
> .
>

2020-12-23 16:17 UTC, HichamELBSI commented on packages/strapi-admin/ee/admin/containers/AuthPage/components/Login/index.js
> +/* eslint-disable jsx-a11y/click-events-have-key-events */
This rule isn't needed anymore as ProviderButton is now an `a` HTML element so the accessibility is natively activated (Navigated between providers with tab, press enter to select a provider).

2020-12-24 14:20 UTC, soupette approved these changes
LGTM

2020-12-24 14:23 UTC, soupette approved these changes

2020-12-24 14:55 UTC, merged