Features/sso
strapi/strapi pull request #9009
Opened 2020-12-28 14:10 UTC by Convly

Adds SSO capability

2021-02-01 17:22 UTC, alexandrebodin requested changes

2021-02-01 17:22 UTC, alexandrebodin commented on packages/strapi-admin/services/role.js
> +  await checkRolesIdForDeletion(ids);
check the error message in the frontend

2021-02-01 17:22 UTC, alexandrebodin commented on packages/strapi-admin/ee/validation/authentication.js
> +      return strapi.admin.services.role.exists({ id: roleId });
verify test can be a promise ?

2021-02-17 08:42 UTC, sam-pires commented on packages/strapi-admin/admin/src/translations/en.json
> +  "app.components.Users.MagicLink.connect.sso": "Send this link to the user, the first login can be mage via a SSO provider",
```suggestion
  "app.components.Users.MagicLink.connect.sso": "Send this link to the user, the first login can be made via a SSO provider",
```

2021-02-17 17:29 UTC, merged

2021-02-17 17:34 UTC, sam-pires commented
🎉