Fix is-creator condition not applied on find
strapi/strapi pull request #9213
Opened 2021-01-25 16:31 UTC by alexandrebodin

Fix conditions not use to buildfind queries in CM.

Fix https://github.com/strapi/strapi/issues/9187

2021-01-25 16:46 UTC, Convly requested changes
Some questions :slightly_smiling_face:

2021-01-25 16:46 UTC, Convly commented on packages/strapi-admin/services/permission/permissions-manager/index.js
> +    const caslQuery = this.getQuery(action);
Here, you get the strapi-formatted query, not the Casl one

```javascript
getQuery() {
    ...
    return buildStrapiQuery(buildCaslQuery(ability, queryAction, model));
}
```

2021-01-25 16:46 UTC, Convly commented on packages/strapi-admin/services/permission/permissions-manager/index.js
> +    if (_.isUndefined(queryAction)) {
As it was discussed elsewhere, shouldn't we prefer the fp method over the regular one?

2021-01-25 16:46 UTC, Convly commented on packages/strapi-plugin-content-manager/services/permission-checker.js
> +  const buildDeleteQuery = query => buildPermissionQuery(query, ACTIONS.delete);
Why declaring helpers only for `read` & `delete`? Is it to keep it simple as long as we don't need the other ones?

2021-01-25 21:05 UTC, derrickmehaffy commented
Validated the fix worked with current code, not including any of the PR feedback: 
![image](https://user-images.githubusercontent.com/8593673/105765893-4e268a80-5f16-11eb-8e29-979d583b7399.png)

2021-01-26 09:18 UTC, Convly approved these changes
Nice, thanks :slightly_smiling_face:

2021-01-26 09:18 UTC, merged