Korean Translation for 3.4.5
strapi/strapi pull request #9287
Opened 2021-02-02 02:41 UTC by kimtj12

### What does it do?

Korean Translation Update for 3.4.5

### Why is it needed?

Korean Translation for 3.4.5

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

2021-02-02 02:41 UTC, strapi-cla commented
[![CLA assistant check](https://cla.strapi.io/pull/badge/not_signed)](https://cla.strapi.io/strapi/strapi?pullRequest=9287) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.strapi.io/strapi/strapi?pullRequest=9287) before we can accept your contribution.<br/><hr/>**mini** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.strapi.io/check/strapi/strapi?pullRequest=9287) it.</sub>

2021-02-02 10:24 UTC, iicdii requested changes

2021-02-02 10:24 UTC, iicdii commented on packages/strapi-admin/admin/src/translations/ko.json
> +  "components.ErrorBoundary.title": "에러가 발생했습니다... ㅠㅠ",
I think this line is unnecessary change.

2021-02-02 10:24 UTC, iicdii commented on packages/strapi-admin/admin/src/translations/ko.json
> +  "components.WysiwygBottomControls.uploadFiles": "파일을 끌어 놓거나, 클립보드에서 붙혀넣거나, {browse} 하세요",
"클립보드에서 붙여 넣거나," is the correct grammar. origin translation was wrong, too. Can you correct it?

2021-02-02 10:24 UTC, iicdii commented on packages/strapi-admin/admin/src/translations/ko.json
> +  "notification.error": "에러가 발생했습니다 ㅜㅜ",
Here again, I think "에러가 발생했습니다." is enough.

2021-02-15 08:36 UTC, alexandrebodin commented
Hi @kimtj12 anyway you can check the few commentson your PR ? would love to merge it asap :)

2021-03-11 13:09 UTC, alexandrebodin commented
Hi, closing for inactivity. Feel free to ping me if you want to take it up sometime in the future :)

2021-03-11 13:09 UTC, closed without merging