Do not use npm v7 on new projects
strapi/strapi pull request #9330
Opened 2021-02-05 17:26 UTC by derrickmehaffy

Signed-off-by: Derrick Mehaffy <derrickmehaffy@gmail.com>

### What does it do?

Sets the default npm version to npm v6 in the package.json engines

### Why is it needed?

There are currently some breaking changes in npm v7 which has now gone into general release. This should stop providers like Heroku from trying to use npm v7 by default

### Related issue(s)/PR(s)

Related to the following comment: https://github.com/strapi/strapi/issues/9206#issuecomment-773036382

2021-02-08 08:57 UTC, alexandrebodin requested changes

2021-02-08 08:57 UTC, alexandrebodin commented on packages/strapi-generate-new/lib/resources/json/package.json.js
> +      npm: '<=6.x.x',
pleas use `^6.0.0` instead we don't want v5 either

2021-02-09 15:49 UTC, pesinasiller submitted a review, later dismissed

2021-02-10 16:34 UTC, alexandrebodin approved these changes
LGTM thanks !

2021-02-10 16:35 UTC, merged