handle toggle i18n on CT and fields
strapi/strapi pull request #9392
Opened 2021-02-12 10:31 UTC by petersg83

2021-02-12 14:14 UTC, alexandrebodin reviewed
LGTM. Just wondering why you removed the isVisible flag ?

2021-02-12 15:05 UTC, petersg83 commented
> LGTM. Just wondering why you removed the isVisible flag ?

I thought the front was handling directly the option by reading `pluginOptions` but after checking it's not the case.
I put it back

2021-02-12 15:49 UTC, alexandrebodin requested changes
LGTM just adding a few tests would be great :)

2021-02-15 11:09 UTC, alexandrebodin approved these changes
LGTM

2021-02-15 11:09 UTC, merged

2021-04-12 15:12 UTC, gfpacheco commented
I need the 
>Ability to add custom keys in the attributes schema (such as "index" for mongo) : based on discussion #8022

Is there any plans on supporting this before i18n is released?