Add migration when i18n is disabled on a CT
strapi/strapi pull request #9843
Opened 2021-03-26 11:16 UTC by petersg83

2021-03-26 12:21 UTC, alexandrebodin requested changes
LGTM jut some linting to fix ;)

2021-03-26 12:21 UTC, alexandrebodin commented on packages/strapi-plugin-i18n/config/functions/migrations/content-type/disable/migrate-for-bookshelf.js
> +  await ORM.knex.schema.dropTable(localizationsTable);
you can add ifExists just for safety

2021-03-26 14:21 UTC, petersg83 commented
Some changed were not commited, it should be better now :)

2021-03-26 20:06 UTC, alexandrebodin commented on packages/strapi-plugin-i18n/config/functions/migrations/content-type/disable/migrate-for-bookshelf.js
> +  const tableExists = await ORM.knex.schema.hasTable(localizationsTable);
you can use knex.schema.dropTableIfExists instead of doing the check manually

2021-03-29 14:56 UTC, alexandrebodin approved these changes
works like a charm

2021-03-29 14:56 UTC, merged